### ISSUE TITLE
Use of the devfile universal images in Che samples

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20507]
### Is your enhancement related to a problem? Please describe

- The number of images to maintain: we have almost a distinct image for each of our samples and plugins 
- We do not have a default image for component-less workspaces (we currently use Theia sidecar, that’s ok for nodejs but for the rest?)
- To cache our sample images for faster startup we need to pre-pull 20+ images on every single node of the cluster
- Developers should not leave a workspace to use a command line tool (for example while coding in Java a developer may want use python or kubectl)
- The images for the samples and plugins need to be kept in sync

![image](https://user-images.githubusercontent.com/606959/137415239-fe559eb2-df6d-4d45-9ad8-550bb8a0dcd3.png)

### Describe the solution you'd like

- [x] Define a [Universal Developer Image](https://github.com/devfile/api/issues/616) that include every tool required
  - [x] by the commands in our samples 
  - [x] by the vs extensions included in our samples
  - [ ] by the top 10 VS Code extensions in the marketplace
- [x] Use the Universal Developer image as the main component of every sample devfile
- [x] When Theia is the editor: run the extensions in the main devfile component
- [x] When VS Code is the editor: run both the editor and the extensions in the main devfile component
- [ ] When IntelliJ is the editor: run the editor in the main devfile component

![image](https://user-images.githubusercontent.com/606959/137416074-fab63a5b-44fa-4775-964f-b626d056be61.png)

### Additional context

We should update only Devfile v2 examples
We should continue to build the plugins sidecar images for when the developer specify `sidecar-policy: MERGE_IMAGE`
