### ISSUE TITLE
Warn users when they are trying to run a workspace that is likely to fail

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20509]
### Is your enhancement related to a problem? Please describe

The user have to wait tens of seconds or even minutes before they get notified that his request to start a workspace failed. Because resources are not enough, the devfile is not valid, the required resources (volumes, cpu or memory) are not available, the user do not have privileges etc…

### Describe the solution you'd like

- [ ] evaluate if there is some pods attached to the volumes that would prevent the workspace to start (see [1](https://github.com/eclipse/che/issues/19259) and [2](https://github.com/eclipse/che/issues/20052#issuecomment-872777868))
- [ ] evaluate the devfile images and entrypoints before the user click the start button
- [ ] evaluate the resources (pv, cpu, memory) available for a user
- [ ] evaluate the devfile syntax before the user click the start button
- [ ] evaluate the devfile memory req before the user click the start button
- [ ] evaluate the devfile cpu req before the user click the start button
- [ ] evaluate the devfile pv req before the user click the start button
- [ ] cache devfile evaluations
- [ ] cache the evaluation of the resources availble for a user

**Comment by benoitf** [comment]
I've assigned dashboard as area but maybe @sleshchenko you see other areas
