### ISSUE TITLE
Plugins Sprint 208

### ISSUE THREAD

**Issue by svor** [eclipse/che#20531]
### CRW
* [ ] CRW doesn't allow MTA(Migration Toolkit for Applications) Plugin to show MTA configuration [CRW-2133](https://issues.redhat.com/browse/CRW-2133) @vitaliy-guliy 
* [ ] Update openshift connector to latest version (support for devfile 2.0) [CRW-1733](https://issues.redhat.com/browse/CRW-1733) @vinokurig 
* [ ] Update golang stack/sidecar to include go 1.15 [CRW-1308](https://issues.redhat.com/browse/CRW-1308) @svor 
* [ ] Please clarify, ensure consistency of views for Tasks [CRW-2052](https://issues.redhat.com/browse/CRW-2052) @tsmaeder 
* [x] Specify plugins memory requests [CRW-2238](https://issues.redhat.com/browse/CRW-2238) @vitaliy-guliy 
* [ ] Clone from GitHub is not possible using IDE UI [CRW-2290](https://issues.redhat.com/browse/CRW-2290) @vinokurig 

### Bugs
* [x] Tasks are not ended properly #19821 @svor 
* [ ] Clone from GitHub is not possible using IDE UI #20316 @vinokurig
* [x] OpenShift Connector does not work on workspaces.openshift.com #20229 @vinokurig
* [ ] Commands are not displayed in the sidecar component #20498 @tsmaeder 
* [x] [plugins] Cannot read property 'getExtension' of vscode.extensions #19172 @tsmaeder 
* [x] Theia fails to load plugins when it's run as DevWorkspace on OpenShift behind OAuth #20448 @vitaliy-guliy 
* [x] Failed to debug java spring sample with devworkspace engine #20536 @svor 

### Enhancements
* [x] [devfile registry]: decouple oci image lifecycle #19695 @vitaliy-guliy 
* [ ] Update vscode-java extension to the latest version #20134 @tsmaeder 
* [ ] Create v2 devfiles for Getting Started samples #19341 @svor 
* [ ] (Investigation) Performance of vscode.workspace.fs.readDirectory(Uri) is worse by *100 compared to vscode eclipse-theia/theia#9514 @tsmaeder 
* [x] The name of the workspace view should be improved #19214 @vinokurig 
* [x] List Che 3rd party runtime dependencies #20543 @svor 
    
### QE
* [x] Release testing @Ohrimenko1988
* [x] Update plugins tests for fixing failures [CRW-2309](https://issues.redhat.com/browse/CRW-2309) @Ohrimenko1988 

### Unplanned
* [x] [devfile registry]: rework/stabilize release scripts after reworking of sidecars lifecycle #20603 @vitaliy-guliy 
* [ ] debug: clean up debug session management eclipse-theia/theia#10164 @tsmaeder 

### Open PRs From Last Sprint
* [x] Implement Inline and Named Pipe Debug Adapters eclipse-theia/theia#10163 @tsmaeder
* [ ] Introduce proper custom execution lifecycle eclipse-theia/theia#9559 @tsmaeder 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 13 | 8 |
| @vinokurig  | 10 | 6 |
| @tsmaeder | 13 | 8 |
| @svor | 13 | 8 |
| @Ohrimenko1988 | 4 | 2 |

October 8 - HnH day
October 14 - Holiday in UA

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Commands are not displayed in the sidecar component #20498 |
| 2 | [plugins] Cannot read property 'getExtension' of vscode.extensions #19172 |
| 3 | (Investigation) Performance of vscode.workspace.fs.readDirectory(Uri) is worse by *100 compared to vscode eclipse-theia/theia#9514 |
| 4 | Update vscode-java extension to the latest version #20134 |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Failed to debug java spring sample with devworkspace engine #20536 |
| 2 | List Che 3rd party runtime dependencies #20543 |
| 3 | Create v2 devfiles for Getting Started samples #19341 |
| 4 | Update golang stack/sidecar to include go 1.15 [CRW-1308](https://issues.redhat.com/browse/CRW-1308) |
| 5 | Tasks are not ended properly #19821 |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 | Clone from GitHub is not possible using IDE UI #20316 |
| 2 | OpenShift Connector does not work on workspaces.openshift.com #20229 |
| 3 | Update openshift connector to latest version (support for devfile 2.0) [CRW-1733](https://issues.redhat.com/browse/CRW-1733) |
| 4 | The name of the workspace view should be improved #19214 |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | [devfile registry]: decouple oci image lifecycle #19695 |
| 2 | Theia fails to load plugins when it's run as DevWorkspace on OpenShift behind OAuth #20448 |
| 3 | Specify plugins memory requests [CRW-2238](https://issues.redhat.com/browse/CRW-2238) |
| 4 | CRW doesn't allow MTA(Migration Toolkit for Applications) Plugin to show MTA configuration [CRW-2133](https://issues.redhat.com/browse/CRW-2133) |

##### @Ohrimenko1988
| Priority  | Item |
| ------------- | ------------- |
| 1 | Release testing |
| 2 | Update plugins tests for fixing failures [CRW-2309](https://issues.redhat.com/browse/CRW-2309) |

**Comment by svor** [comment]
Superseded by https://github.com/eclipse/che/issues/20653
