### ISSUE TITLE
Airgap support for VS Code as an Eclipse Che editor

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20549]
(was: Check if che plug-in registry could provide the VS Code marketplace API)

### Is your task related to a problem? Please describe

For offline/airgap mode, we will need a private registry to provide vsix files.
OpenVSX requires a database + elasticsearch (and oAuth is only github)

So we should check if we can propose basic API on top of existing plug-in registry to provide these offline features if people don't need a '3-tier service' for that purpose.

### Describe the solution you'd like

Layer providing queries/download of VSIX files

### Describe alternatives you've considered

Allow to set by preferences of the user the registry to use (like Eclipse OpenVSX instance, in-house OpenVSX, etc.)

### Additional context

- [x] https://github.com/eclipse/che/issues/21598
- [x] https://github.com/eclipse/che/issues/21611
- [x] https://github.com/eclipse/che/issues/21600
- [x] https://github.com/eclipse-che/che-plugin-registry/pull/1324
- [x] https://github.com/eclipse/che/issues/21601
- [x] https://github.com/che-incubator/che-code/pull/85
- [x] https://github.com/eclipse/openvsx/pull/499
- [x] https://github.com/eclipse-che/che-operator/pull/1464
- [x] https://github.com/eclipse/che/issues/21620
- [x] https://github.com/eclipse/che/issues/21654
- [x] https://github.com/eclipse/che/issues/21662

### Release Notes Text

It's now possible to run an Eclipse Che workspace using VS Code as editor in a cluster with a restricted/disconnected network (air gap). Eclipse Che is now able to run a local open-vsx registry instance within the plugin-registry pod so that VS Code editors running in workspaces can use it to manage extensions. To control what instance of open-vsx should be used in the workspaces we have introduced a new field in`CheCluster` CR to specify the open-vsx URL.

**Comment by tsmaeder** [comment]
Wouldn't it make more sense to improve the upstream open-vsx code base to make it more modular? It would allow other open-vsx clients to benefit, as well.

**Comment by nickboldt** [comment]
Upstream issues that may block this implementation for downstream include:
* https://github.com/eclipse/openvsx/issues/229 
* https://github.com/eclipse/openvsx/issues/263
* https://github.com/eclipse/openvsx/issues/314
* https://github.com/eclipse/openvsx/issues/37
* https://github.com/eclipse/openvsx/issues/341#issuecomment-943534198 (if we want to differentiate by license type to better filter out non-free and depends-on-non-free ("contrib") stuff)
