### ISSUE TITLE
Avoid re-downloading the same extension again and again

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20592]
### Is your enhancement related to a problem? Please describe

Che-Theia based workspaces download the same vsix files **at every restart**. That is a waste of time and bandwidth.

Che-Theia doesn't automatically update the extensions included in a workspace when new versions are available.

### Describe the solution you'd like

- [ ] If the workspace configuration doesn't change, the extensions should NOT be re-downloaded.
  - [ ] Che Theia
  - [ ] IntelliJ
  - [ ] VS Code 

- [ ] If the workspace configuration changes, new extensions should be downloaded, removed extensions should be deleted only if they are not required by existing workspaces.
  - [ ] Che Theia
  - [ ] IntelliJ
  - [ ] VS Code 

- [ ] When a workspace is deleted, its extensions should be deleted only if they are not required by existing workspaces.
  - [ ] Che Theia
  - [ ] IntelliJ
  - [ ] VS Code 

- [ ] Extensions should be shared among workspaces: if a new workspace include an already downloaded extension, that should NOT be re-downloaded. (depends on feature from DWO https://github.com/devfile/devworkspace-operator/issues/630)
  - [ ] Che Theia
  - [ ] IntelliJ
  - [ ] VS Code 

- [ ] Editors should update an extension as soon as a new version is available AND that extension should not be re-downloaded at subsequent worksapce re-starts
  - [ ] Che Theia
  - [ ] IntelliJ
  - [ ] VS Code 

### Describe alternatives you've considered

In case of ephemeral workspaces the plugins won't be cached and will need to be re-downloaded at every workspace restart.
