### ISSUE TITLE
Production-ready support of JetBrains IDEs as a Che editor

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20591]
### Is your enhancement related to a problem? Please describe

This is a follow up of [Introduce a Projector-based IDEA Che editor](https://github.com/eclipse/che/issues/19596) and similarly to the [VS Code epic ](https://github.com/eclipse/che/issues/20500) the goal is to support JetBrains IDE at the same level as Che-Theia is supported.

### Describe the solution you'd like

- [x] https://github.com/eclipse/che/issues/20863 @azatsarynnyy
- [x] https://github.com/eclipse/che/issues/21011
- [x] https://github.com/eclipse/che/issues/20852 @azatsarynnyy
- [x] https://github.com/eclipse/che/issues/21003
- [x] https://github.com/eclipse/che/issues/21029 @azatsarynnyy
- [x] https://github.com/eclipse/che/issues/21116
- [x] https://github.com/eclipse/che/issues/21100
- [x] https://github.com/eclipse/che/issues/21110
- [x] https://github.com/eclipse/che/issues/21124
- [x] #21212
- [x] #21141
- [x] #21139 
- [x] #21140
- [x] https://github.com/eclipse/che/issues/20508 @sleshchenko 
- [ ] https://github.com/eclipse/che/issues/20345 @sleshchenko 
- [x] https://github.com/eclipse/che/issues/20523 @sleshchenko
- [ ] CI to update to lastest upstream JetBrain IDEs (through PR and checks) @azatsarynnyy 
- [ ] Documentation updates @themr0c 
- [ ] QE: add an happy path test using IntelliJ @dmytro-ndp 
- [ ] https://github.com/eclipse/che/issues/20242 @azatsarynnyy

**Comment by azatsarynnyy** [comment]
Added a couple of more sub-tasks that appeared after reworking the image to sidecar-less model:
- #21011
- #21003

**Comment by azatsarynnyy** [comment]
added
- #21029

**Comment by azatsarynnyy** [comment]
added
- https://github.com/eclipse/che/issues/21116
- https://github.com/eclipse/che/issues/21100
- https://github.com/eclipse/che/issues/21110

**Comment by l0rd** [comment]
@azatsarynnyy is currently idling supported for intellij and pycharm?

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy is currently idling supported for intellij and pycharm?

@l0rd it's not supported

**Comment by l0rd** [comment]
I am closing this issue as we are not going to invest in the Projector based IntelliJ anymore but we are shifting the the [Gateway based JetBrain IDEs](https://github.com/eclipse/che/issues/21412).
