### ISSUE TITLE
Che-Theia Plugins view support for DevWorkspace based workspaces

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse/che#20638]
### Is your task related to a problem? Please describe

The existing functionality that installing a plugin adds a component to the devfile
```
components:
  - type: chePlugin
    id: che-incubator/typescript/latest
    ...
```
It works only for devfile V1 workspaces, but does not work for Devfile V2 as it's completely different.

To add vscode extension to devfile V2 workspace it needs to add the extension ID to `.vscode/extensions.json` as in the example
https://github.com/che-samples/java-spring-petclinic/blob/devfilev2/.vscode/extensions.json

It's not a big deal for plugins, that are running in the same container withing Che-Theia. It's possible to take an extension ID or even URI (if it works) and add it to `extensions.json`.

But it needs to be discusses as well what shall we do with plugins, that are running inside separate container.

### Describe the solution you'd like

Find a way to install a plugin from `che-pluin-registry` to devfile V2 workspace.

### Release Notes Text

Che-Theia now supports plugins management from the built-in Plugin View for DevWorkspace based workspaces as well.

**Comment by max-cx** [comment]
Hi, a question to the assignee of this issue:

Will the outcome require any changes to the relevant content of the _Installation Guide_ or _Administration Guide_ or _End-user Guide_?

Yes/No?

**Comment by vitaliy-guliy** [comment]
@max-cx I think we don't need to change any documentation

**Comment by vitaliy-guliy** [comment]
To have the perfect UX flow we need to have
- [ ] fixed restarting the workspace after updating the devfile https://github.com/eclipse/che/issues/20910
- [ ] somehow avoid the workspace autorestart when changing the devfile https://github.com/eclipse/che/issues/20920. In the devfile v2 we inject all the plugins, that are running in the sidecar, into developer container.
- [ ] allow to restart the workspsace on demand to ally the changes https://github.com/eclipse/che/issues/20921

**Comment by benoitf** [comment]
moving issue to 7.42 milestone as this issue is part of the endgame

**Comment by vitaliy-guliy** [comment]
Feature has been merged.
Devfile to test https://github.com/vitaliy-guliy/java-spring-petclinic/tree/devfilev2-plugin-installation
