### ISSUE TITLE
Plugins Sprint 209

### ISSUE THREAD

**Issue by svor** [eclipse/che#20653]
### Blockers
* [x] [devfile registry] update happy-path image consistently with other sidecars #20667 @vitaliy-guliy 

### CRW
* [x] CRW doesn't allow MTA(Migration Toolkit for Applications) Plugin to show MTA configuration [CRW-2133](https://issues.redhat.com/browse/CRW-2133) @vitaliy-guliy 
* [x] Update openshift connector to latest version (support for devfile 2.0) [CRW-1733](https://issues.redhat.com/browse/CRW-1733) @vinokurig 
* [x] Update golang stack/sidecar to include go 1.15 [CRW-1308](https://issues.redhat.com/browse/CRW-1308) @svor 
* [ ] Please clarify, ensure consistency of views for Tasks [CRW-2052](https://issues.redhat.com/browse/CRW-2052) @tsmaeder 
* [x] Clone from GitHub is not possible using IDE UI [CRW-2290](https://issues.redhat.com/browse/CRW-2290) @vinokurig 
* [x] Node-js configmap workspace shows error as getting config message [CRW-2325](https://issues.redhat.com/browse/CRW-2325) @svor 
* [ ] Move a functionality to run executable endpoint from sidecar plugins to Dockerfiles [CRW-1924](https://issues.redhat.com/browse/CRW-1924) @vitaliy-guliy 

### Bugs
* [ ] Clone from GitHub is not possible using IDE UI #20316 @vinokurig
* [x] In hosted-instance-log: "TypeError: Cannot read property 'path' of undefined" from vscode-builtin-json-language-feature #19485 @tsmaeder 
* [ ] Commands are not displayed in the sidecar component #20498 @tsmaeder 
* [ ] debug: clean up debug session management eclipse-theia/theia#10164 @tsmaeder 
* [x] [regression]Failed to run the "vscode-xml" plugin because of absence of the "redhat.vscode-commons" dependency #20094 @vitaliy-guliy 

### Enhancements
* [x] Evaluate current list of samples #19442 @svor 
* [x] Update existing devfiles v2 to use Universal image #20657 @vitaliy-guliy 
* [ ] Support overriding Che Theia plugins preferences and sidecar through .che/che-theia-plugins.yaml #20596 @vinokurig 
* [ ] Create v2 devfiles for Getting Started samples #19341
  - * [x] Java+MongoDB @vitaliy-guliy 
  - * [x] Go @vinokurig 
* [ ] Persist Che-Theia preferences when DW is enabled #20622 @vinokurig 
* [ ] (Investigation) Performance of vscode.workspace.fs.readDirectory(Uri) is worse by *100 compared to vscode eclipse-theia/theia#9514 @tsmaeder 
    
### QE
* [ ] Release testing @Ohrimenko1988 
* [x] Add secrets to the openshift CI for fixing the 'GitHubPullRequestPlugin' test #20658 @Ohrimenko1988 

### Unplanned
* [x] The nightly plugins tests are failed on the openshift CI because reached the docker pull limit #20700 @Ohrimenko1988 
* [x] Simplify the local launching of plugins tests #20703 @Ohrimenko1988
* [x] Single-arch devfiles (Red Hat Fuse, EAP Maven, Dotnet, camelK) switch from zip to git for project reference [CRW-2403](https://issues.redhat.com/browse/CRW-2403) @svor 
* [x] [devworkspaces] maven-based tasks don't work in a container, created from universal developer image #20699 @vitaliy-guliy 

### Open PRs From Last Sprint
* [ ] Introduce proper custom execution lifecycle eclipse-theia/theia#9559 @tsmaeder 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 13 | 8 |
| @vinokurig  | 13 | 8 |
| @tsmaeder | 12 | 7 |
| @svor | 13 | 8 |
| @Ohrimenko1988 | 13 | 8 |

October 22th - Recharge day
October 29th - H&H 

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1 | debug: clean up debug session management eclipse-theia/theia#10164 |
| 2 | In hosted-instance-log: "TypeError: Cannot read property 'path' of undefined" from vscode-builtin-json-language-feature #19485 |
| 3 | (Investigation) Performance of vscode.workspace.fs.readDirectory(Uri) is worse by *100 compared to vscode eclipse-theia/theia#9514 |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Evaluate current list of samples #19442 |
| 2 | Node-js configmap workspace shows error as getting config message [CRW-2325](https://issues.redhat.com/browse/CRW-2325) |
| 3 | Update golang stack/sidecar to include go 1.15 [CRW-1308](https://issues.redhat.com/browse/CRW-1308)  |
| 4 | Create v2 devfiles for Getting Started samples #19341 |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 | Devfile version2 for  Go #19341 |
| 2 | Persist Che-Theia preferences when DW is enabled #20622 |
| 3 | Support overriding Che Theia plugins preferences and sidecar through .che/che-theia-plugins.yaml #20596 |
| 4 | Clone from GitHub is not possible using IDE UI #20316 |
| 5 | Update openshift connector to latest version (support for devfile 2.0) [CRW-1733](https://issues.redhat.com/browse/CRW-1733) |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | [devfile registry] update happy-path image consistently with other sidecars #20667  |
| 2 | Devfile version2 for Java+MongoDB  #19341 |
| 3 | Update existing devfiles v2 to use Universal image #20657 |
| 4 | [regression]Failed to run the "vscode-xml" plugin because of absence of the "redhat.vscode-commons" dependency #20094 |
| 5 | Move a functionality to run executable endpoint from sidecar plugins to Dockerfiles [CRW-1924](https://issues.redhat.com/browse/CRW-1924) |
| 6 | CRW doesn't allow MTA(Migration Toolkit for Applications) Plugin to show MTA configuration [CRW-2133](https://issues.redhat.com/browse/CRW-2133) |

##### @Ohrimenko1988
| Priority  | Item |
| ------------- | ------------- |
| 1 | Release testing |
| 2 | Add secrets to the openshift CI for fixing the 'GitHubPullRequestPlugin' test #20658 |

**Comment by svor** [comment]
Superseded by #20752
