### ISSUE TITLE
Plugins Sprint 210

### ISSUE THREAD

**Issue by svor** [eclipse/che#20752]
### CRW
* [x] Move a functionality to run executable endpoint from sidecar plugins to Dockerfiles [CRW-1924](https://issues.redhat.com/browse/CRW-1924) @vitaliy-guliy 
* [x] Failed login to the cluster in the "Openshift Connector" plugin [CRW-2440](https://issues.redhat.com/browse/CRW-2440) @vinokurig 
* [x] Bug fix: Quarkus plug-in recommendation is not working [CRW-2048](https://issues.redhat.com/browse/CRW-2048) @tsmaeder 

### Bugs
* [x] When DevWorkspace is enabled, the error "Linter not installed" is shown as soon as the Python sample workspace starts #20645 @svor 
* [ ] Clone from GitHub is not possible using IDE UI #20316 @svor 
* [x] debug: clean up debug session management eclipse-theia/theia#10164 @tsmaeder 
* [x] Recurrent GitHub PR vsx error when starting a workspace on RH developer sandbox #20689 @vinokurig 

### Enhancements
* [x] Support overriding Che Theia plugins preferences and sidecar through .che/che-theia-plugins.yaml #20596 @svor 
* [x] Create v2 devfiles for Getting Started samples #19341
  - * [x] cpp @svor 
  - * [x] java-mysql @vitaliy-guliy  
* [ ] Persist Che-Theia preferences when DW is enabled #20622 @vinokurig 
* [x] Pre-build DevWorkspace templates for devfile v2 of devfile registry #19718 @vinokurig 
* [ ] Allow to install plugins to Devfile V2 workspaces by using Che-Theia Plugins view #20638 @vitaliy-guliy 
* [x] Enable 'Try in Web IDE GitHub action' in every Eclipse Che related repository #20664 @svor 
* [x] (Investigation) Performance of vscode.workspace.fs.readDirectory(Uri) is worse by *100 compared to vscode eclipse-theia/theia#9514 @tsmaeder 
    
### QE
* [x] Release testing @Ohrimenko1988 

### Open PRs From Last Sprint
* [ ] Introduce proper custom execution lifecycle eclipse-theia/theia#9559 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 14 | 8 |
| @vinokurig  | 13 | 8 |
| @tsmaeder | 11 | 7 |
| @svor | 14 | 8 |
| @Ohrimenko1988 | 14 | 8 |

November 19th - H&H 

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Prepare to TheiaCon |
| 2 | debug: clean up debug session management eclipse-theia/theia#10164 |
| 3 | Bug fix: Quarkus plug-in recommendation is not working [CRW-2048](https://issues.redhat.com/browse/CRW-2048) |
| 4 | (Investigation) Performance of vscode.workspace.fs.readDirectory(Uri) is worse by *100 compared to vscode eclipse-theia/theia#9514 |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Enable 'Try in Web IDE GitHub action' in every Eclipse Che related repository #20664 |
| 2 | Support overriding Che Theia plugins preferences and sidecar through .che/che-theia-plugins.yaml #20596 |
| 3 | Create v2 devfiles for Getting Started samples #19341 cpp |
| 4 | When DevWorkspace is enabled, the error "Linter not installed" is shown as soon as the Python sample workspace starts #20645 |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 | Failed login to the cluster in the "Openshift Connector" plugin [CRW-2440](https://issues.redhat.com/browse/CRW-2440)  |
| 2 | Pre-build DevWorkspace templates for devfile v2 of devfile registry #19718 |
| 3 | Persist Che-Theia preferences when DW is enabled #20622 |
| 4 | Recurrent GitHub PR vsx error when starting a workspace on RH developer sandbox #20689 |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | Move a functionality to run executable endpoint from sidecar plugins to Dockerfiles [CRW-1924](https://issues.redhat.com/browse/CRW-1924) |
| 2 | Create v2 devfiles for Getting Started samples #19341 java-mysql |
| 3 | Allow to install plugins to Devfile V2 workspaces by using Che-Theia Plugins view #20638 |

##### @Ohrimenko1988
| Priority  | Item |
| ------------- | ------------- |
| 1 | Release testing |

**Comment by svor** [comment]
Superseded by #20848
