### ISSUE TITLE
[cross-project epic] Update ubi based go builds to 1.16

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#20774]
### Is your task related to a problem? Please describe

golang 1.16 is now out in RHEC UBI8 containers - `registry.access.redhat.com/ubi8/go-toolset:1.16`

So... downstream will be using 1.16 starting with 2.14 (or sooner in 2.13). 

We should use the same golang baseline in upstream too.

Affected projects include:
* che-operator
* backup-restore
* imagepuller
* jwtproxy
* machine-exec
* plugin broker artifacts
* plugin broker metadata
* dwo

### Describe the solution you'd like

update Dockerfiles to use go 1.16 and rhel8/ubi8-based dockerfiles to use go-toolset:1.16

### Describe alternatives you've considered

Do nothing. See how that turns out. :) 

### Additional context

* https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1 currently has 1.16.7
* che-operator already [updated](https://github.com/eclipse-che/che-operator/commit/5bf688a863999e8b4b4ffeca756e430088520b46) and [:next](https://quay.io/repository/eclipse/che-operator?tag=next&tab=tags) build built as sha `2ce8e7f655e3`.

**Comment by nickboldt** [comment]
Merged (because no controls over main branch, apparently. I'm shocked, I tell ya! I expected more PRs, less "sure just merge that".

- [x] che-operator: https://github.com/eclipse-che/che-operator/blob/main/Dockerfile#L13
- [x] backup: https://github.com/che-dockerfiles/che-backup-server-rest/commit/4f241f3854238f8e4d6f56fed18ffe8154fb9135
- [x] imagepuller operator: https://github.com/che-incubator/kubernetes-image-puller-operator/commit/838da44ca272532af3e7e58a00cecd3b9b1cfef8
- [x] imagepuller: https://github.com/che-incubator/kubernetes-image-puller/commit/56cab7e0a3e60be90ef719f660f4fdf2f9b060e5
- [x] jwtproxy: https://github.com/eclipse/che-jwtproxy/commit/8401af3d3a0e0c0b5f4e58f44b15a5db877fe0d0
- [x] machine-exec: https://github.com/eclipse-che/che-machine-exec/commit/da8d67f90b8846f4afa0e691fdee428abaa7c8ac

Awaiting PR review:

- [ ] plugin broker artifacts + plugin broker metadata: https://github.com/eclipse/che-plugin-broker/pull/124
- [ ] dwo: https://github.com/devfile/devworkspace-operator/pull/682

**Comment by nickboldt** [comment]
Done, as long as I didn't break anything :) 

- [x] operator: https://github.com/eclipse-che/che-operator/actions/workflows/next-build.yaml 
- [?] backup: https://quay.io/repository/crw/backup-rhel8?tab=tags (no next build workflow, only PR checks!)
  - [ ] add next build workflow?
- [x]  imagepuller operator: https://github.com/che-incubator/kubernetes-image-puller-operator/actions/workflows/next-build.yml
- [x]  imagepuller: https://github.com/che-incubator/kubernetes-image-puller/actions/workflows/next-build.yml
- [ ]  jwtproxy: https://github.com/eclipse/che-jwtproxy/actions/workflows/next-build.yml
- [x]  machine-exec: https://github.com/eclipse-che/che-machine-exec/actions/workflows/next-build.yaml
- [ ] plugin brokers: only pushed to main, need to respin in CRW to verify 
   - [ ] https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-pluginbroker-metadata_2.x/29/
   - [ ] https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-pluginbroker-artifacts_2.x/26/
- [ ] dwo: failing? https://github.com/devfile/devworkspace-operator/actions/runs/1493436692

**Comment by nickboldt** [comment]
Couple more tweaks in these workflows:

* https://github.com/eclipse/che-jwtproxy/actions/runs/1496502045 (fix wrong quay publishing credentials)
* https://github.com/che-dockerfiles/che-backup-server-rest/runs/4304269860?check_suite_focus=true (push :next tag as well as the short sha)
