### ISSUE TITLE
Adapt che-theia plugins to avoid requesting che-server API

### ISSUE THREAD

**Issue by svor** [eclipse/che#20788]
### Is your task related to a problem? Please describe

Che-theia plugins which require che-server API don't work when devWorkspace is enabled. 
The list of plugins which need to be adapted:
- [x] [openshift-auth](https://github.com/che-incubator/che-theia-openshift-auth) #20857
- [x] [ssh-plugin](https://github.com/eclipse-che/che-theia/tree/main/plugins/ssh-plugin) #20859
- [x] [github-auth-plugin](https://github.com/eclipse-che/che-theia/tree/main/plugins/github-auth-plugin) https://github.com/eclipse/che/issues/20860

### Describe the solution you'd like

Plugins should be adapted to work with Dev Workspace engine

**Comment by svor** [comment]
I've updated the description by removing Resource Monitor plugin form the list since the problem is'not related to requesting che-server API. Here is another issue for it: https://github.com/eclipse/che/issues/20800

**Comment by svor** [comment]
#20859 is not finished yet
