### ISSUE TITLE
Plugins Sprint 211

### ISSUE THREAD

**Issue by svor** [eclipse/che#20848]
### CRW
* [x] Migrate devfiles v1 to v2 [CRW-2412](https://issues.redhat.com/browse/CRW-2412) @svor 
* [x] Failed to fetch plugins and registries in CRW instance created in OCP 4.9 cluster [CRW-2490](https://issues.redhat.com/browse/CRW-2490) @svor 
* [ ] Pre-build DevWorkspace templates for devfile v2 of devfile registry [CRW-2500](https://issues.redhat.com/browse/CRW-2500) @vinokurig 
* [x] Used CPU of a plugin is higher than limit for the Java plugin [CRW-2453](https://issues.redhat.com/browse/CRW-2453) @svor  

### Bugs
* [x] Clone from GitHub is not possible using IDE UI #20316 @svor
* [ ] Resources Monitor Plugin doesn't work when devWorkspace engine is enable #20800 @svor 
* [ ] [devWorkspace] Adapt ssh-plugin to avoid requesting che-server API #20859 @vinokurig 
* [ ] [devworkspace] java-spring-petclinic sample cannot connect to mysql database, running in the neighbor container #20787 @vitaliy-guliy

### Enhancements
* [ ] Persist Che-Theia preferences when DW is enabled #20622 @vinokurig 
* [ ] Allow to install plugins to Devfile V2 workspaces by using Che-Theia Plugins view #20638 @vitaliy-guliy 
* [x] Devfile registry support for Devfile v2 zip files #20720 @vinokurig 
* [x] [che-devfile-registry]Release DevWorkspaceTemplates in devfile registry #20824 @svor 
* [x] Update vscode-java extension to the latest version #20134 @tsmaeder 
* [ ] Performance of vscode.workspace.fs.readDirectory(Uri) is worse by *100 compared to vscode eclipse-theia/theia#9514 @tsmaeder 
    
### Unplanned
* [x] [theia-devworkspace handler] store projects section when generating templates #20877 @vinokurig 
* [x]  .kube volume should be mounted into openshift-connector container https://issues.redhat.com/browse/CRW-2556 @svor
* [x] [plugin-registry] che-theia-openshift-auth plugin should contain sidecar information #20915 @svor

### Open PRs From Last Sprint
* [ ] Introduce proper custom execution lifecycle eclipse-theia/theia#9559 @tsmaeder 
* [ ] chore: Store user preferences in a config-map https://github.com/eclipse-che/che-theia/pull/1260 @vinokurig 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 13 | 8 |
| @vinokurig  | 13 | 8 |
| @tsmaeder | 10 | 6 |
| @svor | 13 | 8 |

December 3rd - Day of Learning
December 10th - Hack 'n' Hustle 

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1 | (Investigation) Performance of vscode.workspace.fs.readDirectory(Uri) is worse by *100 compared to vscode eclipse-theia/theia#9514 |
| 2 |  Update vscode-java extension to the latest version #20134 |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Resources Monitor Plugin doesn't work when devWorkspace engine is enable #20800 |
| 2 | [che-devfile-registry]Release DevWorkspaceTemplates in devfile registry #20824 |
| 3 | Used CPU of a plugin is higher than limit for the Java plugin [CRW-2453](https://issues.redhat.com/browse/CRW-2453) |
| 4 | Failed to fetch plugins and registries in CRW instance created in OCP 4.9 cluster [CRW-2490](https://issues.redhat.com/browse/CRW-2490) |
| 5 | Migrate devfiles v1 to v2 [CRW-2412](https://issues.redhat.com/browse/CRW-2412) |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 | Persist Che-Theia preferences when DW is enabled #20622 |
| 2 | Devfile registry support for Devfile v2 zip files #20720 |
| 3 | [devWorkspace] Adapt ssh-plugin to avoid requesting che-server API #20859 |
| 4 | Pre-build DevWorkspace templates for devfile v2 of devfile registry [CRW-2500](https://issues.redhat.com/browse/CRW-2500) |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | Allow to install plugins to Devfile V2 workspaces by using Che-Theia Plugins view #20638 |
| 2 | [devworkspace] java-spring-petclinic sample cannot connect to mysql database, running in the neighbor container #20787 |

**Comment by svor** [comment]
Superseded by https://github.com/eclipse/che/issues/20955
