### ISSUE TITLE
As a user, I want to have a possibility to convert old devfile v1 workspaces to the new v2 DevWorkspaces

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#20845]
### Is your task related to a problem? Please describe

As a user, I want to have a possibility to convert old devfile v1 workspaces to the new v2 DevWorkspaces, when DevWorkspace engine is enabled.

### Describe the solution you'd like

1. Admin enables DevWorkspace engine and switches to the AllNamepsaces mode, based on SOP https://github.com/eclipse/che/issues/20614
2. User logs in to Eclipse Che and opens User Dashboard
3. Old Che 7 devfile v1 Workspaces are displayed with a warning sign, deprecated tooltip, and the link to the documentation:

![image](https://user-images.githubusercontent.com/1461122/144039281-b0add872-78ab-4139-b427-1755145cfbb3.png)
![image](https://user-images.githubusercontent.com/1461122/144039396-cc1263af-6d4d-4538-9f0d-1faf12932cc9.png)

4. Old Che 7 devfile v1 Workspaces do NOT have the `Open` / `Start`  actions (`Delete` is still available) on Dashboard, but have a new "Convert" action
5. When the user clicks on the 'Convert' button / menu item, User Dashboard does the v1 -> v2 conversion using the library under the hood and starts the new Devworkspace (which mounts the same folder in the PVC in order to preserve workspace related files)
6. When the new DevWorkspace is started based on the converted devfile, a new attribute e.g. `converted`  is added to the old Che 7 workspace which is still stored in the db.
7. User Dashboard does not show old Che 7 workspaces with the `converted` attribute

### Describe alternatives you've considered

https://github.com/eclipse/che/issues/20254

### Additional context

It is planned NOT to delete old Che 7 devfile v1 workspaces from db after the conversion, because it will trigger the PVC cleanup and delete the workspace-related files mounted in the PVC. In the future, it is planned to get rid of the db and use k8s etcd instead

N.B. User still should be able to delete devfile v1 workspace instead of converting it.

### Sub-tasks

- [ ] Provide documentation for converting devfile v1 to devfile v2 (initial blog post at https://che.eclipseprojects.io/ ? ) https://github.com/eclipse/che/issues/21005 
- [x] Show old devfile v1 based workspaces with a warning sign and deprecated tooltip 

![image](https://user-images.githubusercontent.com/1461122/144039281-b0add872-78ab-4139-b427-1755145cfbb3.png)

- [x] Show a warning on the workspace overview page with a link to the documentation regarding devfile v1 deprecation and conversion instructions to devfile v2

![image](https://user-images.githubusercontent.com/1461122/144039396-cc1263af-6d4d-4538-9f0d-1faf12932cc9.png)

- [x] Hide `Open` / `Start` menu items for old devfile v1 workspaces
- [x] Do not allow edit devfile v1 workspaces in the Overview | Devfile editor (available in read-only mode)
- [x] Add `Show Original Devfile` action item for converted DevWorkspaces, that will allow to preview original devfile v1 
- [x] Replace `Open`  action link with the `Convert` button / menu item for creating a new DevWorkspace based on the old devfile v1 (under the hood the convertion lib is used - https://github.com/che-incubator/devfile-converter)
     - [x] in case of the successful conversion old workspace is updated with the 'converted' attribute and is not displayed on the UD.
     - [x] in case of failure the DevWorkspace is not created. Error message on the UD points to the documentation with manual instructions for converting devfile v1 to devfile v2

**Comment by ibuziuk** [comment]
@l0rd could you please review and share your thoughts? 
The suggested solution expects that che-server workspace API (GET, DELETE, UPDATE) is still working with the DevWorkspae engine enabled.

**Comment by l0rd** [comment]
> When the user clicks on the 'Convert' button / menu item, User Dashboard does the v1 -> v2 conversion using the library under the hood and starts the new Devworkspace

I would not start the new DevWorkspace. I would just create it.

> When the new DevWorkspace is started based on the converted devfile, a new attribute e.g. converted is added to the old Che 7 workspace which is still stored in the db.

We should document how to retrieve those old v1 devfiles in case of problems and add a link to that doc as well.

I would also describe what is expected if a conversion error occurs: we should probably restore the v1 devfile and provide a link to a documentation article that explains how convert a v1 devfile to v2.

**Comment by ibuziuk** [comment]
> I would not start the new DevWorkspace. I would just create it.

makes sense. 
- in case of the successful conversion old workspace is updated with the 'converted' attribute and is not displayed on the UD.
- in case of failure the DevWorkspace is not created. Error message on the UD points to the documentation

**Comment by nickboldt** [comment]
> what if the converted workspace fail to start for whatever reason

Could we...
* add a link to the v1->v2 conversion guide into the dashboard so it's prominently displayed any time a v1 devfile is loaded? 
* add a link to the v1->v2 conversion guide into the welcome page so any workspace that opens will have a reminder about how to convert older workspaces
* add a link to the v1->v2 conversion guide into [somewhere else that's prominent] ?

**Comment by ibuziuk** [comment]
at this point, it is not what is going to be the desired UX
this is really a PM call. The previous plan was https://github.com/eclipse/che/issues/20254 which more or less related to https://github.com/eclipse/che/issues/20845#issuecomment-984665539

**Comment by l0rd** [comment]
cc @kasturi1820

**Comment by ibuziuk** [comment]
The short-term plan for 7.41 - 7.42 is simply hiding v1 based workspaces on the UD level - https://github.com/eclipse/che/issues/20900

**Comment by ibuziuk** [comment]
PR has been merged - https://github.com/eclipse-che/che-dashboard/pull/441
There are separate issues for documentation and reusing the PVC (mount the sources from the Che 7 based workspaces during the conversion):
- https://github.com/eclipse/che/issues/21005
- https://github.com/eclipse/che/issues/21038
