### ISSUE TITLE
Migrate E2E Eclipse Che tests to DevWorkspace

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#20914]
### Is your task related to a problem? Please describe

DevWorkspace Switch - Endgame Plan: https://github.com/eclipse/che/issues/20830

Tasks:
- #20838
- #20913
- #20953
- #20985
- #20986
- #21127
- #21174
- #21175
- #21210
- #21240
- #21241
 

#### E2E tests to fix:
- [x]  DevWorkspace happy path tests

##### plugin tests:
- [x] [VSCodeYamlPluginTest](https://github.com/eclipse/che/issues/VscodeYamlPlugin.spec.ts) - [PR-21170](https://github.com/eclipse/che/pull/21170)
- [x] [TypescriptPluginTest](https://github.com/eclipse/che/blob/main/tests/e2e/tests/plugins/TypescriptPlugin.spec.ts) - [PR-21170](https://github.com/eclipse/che/pull/21170)
- [ ] InstallPluginUsingUI
- [x] JavaPlugin
- [ ] PhpPlugin
- [x] PythonPlugin
- [ ] VscodeKubernetesPlugin
- [ ] VscodeShellcheckPlugin
- [ ] VscodeValePlugin
- [ ] VscodeXmlPlugin
- [ ] GitHubPullRequestPlugin

##### factories tests(https://github.com/eclipse/che/issues/21241):
- [x] [DirectUrlFactoryWithKeepDirectoryTest](https://github.com/eclipse/che/blob/main/tests/e2e/tests/e2e/factories/DirectUrlFactoryWithKeepDirectoryTest.spec.ts) - [PR-21247](https://github.com/eclipse/che/pull/21247)
- [x] [DirectUrlFactoryWithRootFolderTest](https://github.com/eclipse/che/blob/main/tests/e2e/tests/e2e/factories/DirectUrlFactoryWithRootFolderTest.spec.ts)  - [PR-21247](https://github.com/eclipse/che/pull/21247)
- [x] [DirectUrlFactoryWithSpecificBranchTest](https://github.com/eclipse/che/blob/main/tests/e2e/tests/e2e/factories/DirectUrlFactoryWithSpecificBranchTest.spec.ts) - [PR-21247](https://github.com/eclipse/che/pull/21247)

Here an example of update of e2e Che plugins tests to run against **DevWorkspace** for _TypescriptPlugin_  and _VscodeYamlPlugin_ tests: https://github.com/eclipse/che/commit/f437b246c9a3eccc25b868032da7daeb23706ac3
Old devfilev.v1 from **Eclipse Che** repo had been replaced with **che-samples** devfile.v2 in there:
(1) https://raw.githubusercontent.com/eclipse/che/main/tests/e2e/files/devfiles/plugins/TypescriptNodeDebug2PluginTest.yaml
>
https://github.com/che-samples/web-nodejs-sample/tree/typescript-plugin
(2) https://raw.githubusercontent.com/eclipse/che/main/tests/e2e/files/devfiles/plugins/VscodeYamlPlugin.yaml
>
https://github.com/che-samples/web-nodejs-sample/tree/yaml-plugin (edited) 

### Describe the solution you'd like

We need to migrate existed E2E Eclipse Che tests to be run against DevWorkspace.

### Additional context

Switch to DevWorkspace: https://github.com/eclipse-che/che-operator/pull/1265

Happy Path E2E tests on CRW Jenkins CI need support of Eclipse Che installation on minikube started in 'none' driver mode: https://github.com/eclipse/che/issues/20969

**Comment by makambalaji** [comment]
Fixed the Python and Java plugin test cases as part of the pr: https://github.com/eclipse/che/pull/21269
