### ISSUE TITLE
Che Controller Sprint 212

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#20935]
This issue collects work items of the Controller Team for Sprint 211 (22 December - 11 January).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (December 22nd)

The previous sprint https://github.com/eclipse/che/issues/20842

## Sprint goals
- Finalize DevWorkspace Endgame related issues - https://github.com/eclipse/che/issues/20830
- Release DWO 0.11.0 / Start releasing 0.12.0 in early January 2022
- Che Dogfooding instance should use DevWorkspace engine
- Move Web Terminal Operator and DWO to 'crw' namespace on Developer Sandbox

### WTO / Developer Sandbox
- [ ] Move WTO and DWO to the dedicated namespace (currently installed in the `openshift-operators`) - https://issues.redhat.com/browse/CRT-1405

### DevWorkspace
- [x] Inject user kubeconfig into Che workspaces with DevWorkspace enabled #20782
- [x] https://github.com/eclipse/che/issues/20844
- [ ] Check that DWO is compatible with network-isolated clusters - https://github.com/devfile/devworkspace-operator/issues/668
- [x] Enable proxy support for DevWorkspaces https://github.com/devfile/devworkspace-operator/issues/678
- [ ] Create a test plan for DWO https://github.com/devfile/devworkspace-operator/issues/666

### Dashboard
- #20784
- #19633
- #20893
- #20829
- #20845
- #20956
- #20819

### Telemetry
- https://github.com/eclipse/che/issues/20090

### CRW
- Che Dogfooding instance should install DevWorkspace operator + use single-host - https://issues.redhat.com/browse/CRW-1639

### Docs
- Reviewing pull requests https://issues.redhat.com/browse/RHDEVDOCS-3522
- Contributing for the first time to a project https://issues.redhat.com/browse/RHDEVDOCS-3521

### QE
-  2.14.0 pre-release testing
- https://github.com/eclipse/che/issues/20108

**Comment by dkwon17** [comment]
Another possible issue if we have time: https://github.com/eclipse/che/issues/20960
