### ISSUE TITLE
Plugins Sprint 212

### ISSUE THREAD

**Issue by svor** [eclipse/che#20955]
### CRW
* [ ] Migrate devfiles v1 to v2 (part 2) [CRW-2539](https://issues.redhat.com/browse/CRW-2539) @svor  
* [ ] Pre-build DevWorkspace templates for devfile v2 of devfile registry [CRW-2500](https://issues.redhat.com/browse/CRW-2500) @vinokurig 
* [x] Update vscode-java extension to 0.82.0 version [CRW-2590](https://issues.redhat.com/browse/CRW-2590) @tsmaeder 

### Bugs
* [ ] Resources Monitor Plugin doesn't work when devWorkspace engine is enable #20800 @svor 
* [ ] [devworkspace] java-spring-petclinic sample cannot connect to mysql database, running in the neighbor container #20787 @vitaliy-guliy 
* [ ] [che-samples] mongo-db sample cannot connect to mongo database #20688 @vitaliy-guliy
* [ ] Go stack sample application shows an empty page #20686 @vitaliy-guliy

### Enhancements
* [ ] Persist Che-Theia preferences when DW is enabled #20622 @vinokurig 
* [ ] Allow to install plugins to Devfile V2 workspaces by using Che-Theia Plugins view #20638 @vitaliy-guliy  
* [ ] [devWorkspace] Adapt ssh-plugin to avoid requesting che-server API #20859 @vinokurig 
* [ ] [devWorkspace] Adapt github-auth plugin to avoid requesting che-server API #20860 @vinokurig 
* [ ] [devWorkspace ] Adapt openshift-authentication plugin to avoid requesting che-server API #20857 @vinokurig

    
### Unplanned
* [x]  Quarkus DW failed with image CrashLoopBack [CRW-2605](https://issues.redhat.com/browse/CRW-2605) @svor

### Open PRs From Last Sprint
* [ ] chore: Store user preferences in a config-map https://github.com/eclipse-che/che-theia/pull/1260 @vinokurig 
* [ ] Install plugins to devworkspaces https://github.com/eclipse-che/che-theia/pull/1267  @vitaliy-guliy 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 11 | 7 |
| @vinokurig  | 8 | 5 |
| @tsmaeder | 3 | 2 |
| @svor | 8 | 5 |

December 27 - Day off for Catholic Christmas Day :ukraine:
January 3 - Day off for New Year's Day :ukraine:
January 7 - Orthodox Christmas Day 
December 27 - January 11 - Thomas PTO
December 28-31 - Valerii PTO
December 31 - H&H

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Update vscode-java extension to 0.82.0 version [CRW-2590](https://issues.redhat.com/browse/CRW-2590) |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Migrate devfiles v1 to v2 (part 2) [CRW-2539](https://issues.redhat.com/browse/CRW-2539) |
| 2 | Resources Monitor Plugin doesn't work when devWorkspace engine is enable #20800 |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 | Pre-build DevWorkspace templates for devfile v2 of devfile registry [CRW-2500](https://issues.redhat.com/browse/CRW-2500) |
| 2 | [devWorkspace] Adapt ssh-plugin to avoid requesting che-server API #20859 |
| 3 | Adapt openshift-authentication plugin to avoid requesting che-server API #20857 |
| 4 | Adapt github-auth plugin to avoid requesting che-server API #20860 |
| 5 | Persist Che-Theia preferences when DW is enabled #20622 |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | Install plugins to devworkspaces [#1267](https://github.com/eclipse-che/che-theia/pull/1267 ) |
| 2 | [devworkspace] java-spring-petclinic sample cannot connect to mysql database, running in the neighbor container #20787 |
| 3 | mongo-db sample cannot connect to mongo database #20688 |
| 4 | Go stack sample application shows an empty page #20686 |

**Comment by svor** [comment]
Superseded by #21000
