### ISSUE TITLE
Editors Sprint 213

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#20999]
January 12 - February 1

---
#### CRW 2.15
- [x] Help Prod. team with "No ripgrep prebuilt 13.0.0-2 available for ppc64" [CRW#2600](https://issues.redhat.com/browse/CRW-2600)
- [x] Provide devfile for IntelliJ IDEA editor in CRW [CRW#2276](https://issues.redhat.com/browse/CRW-2276)

#### Bugs
- #20861

#### Production-ready support of JetBrains IDEs as a Che editor https://github.com/eclipse/che/issues/20591
- #21002
- #21003
- #21011
- #21029

#### Production-ready support of VS Code as a Che editor https://github.com/eclipse/che/issues/20500
- #21030

#### Other issues
- #21034 

---
### Unplanned/Blockers
- [x] Help Prod. team with "Cannot resolve yarn dependencies when building crw-theia 2.15" [CRW#2656](https://issues.redhat.com/browse/CRW-2656)

---
## Team
| Name  | Availability | x0.6
| -- | -- | --
| @vzhukovs    | 14  | 8
| @RomanNikitenko | 11  | 7
| @azatsarynnyy | 14  | 8

---
[Previous Sprint](https://github.com/eclipse/che/issues/20966)
