### ISSUE TITLE
Plugins Sprint 213

### ISSUE THREAD

**Issue by svor** [eclipse/che#21000]
### CRW
* [x] Migrate devfiles v1 to v2 (part 2) [CRW-2539](https://issues.redhat.com/browse/CRW-2539) @svor  
* [ ] Pre-build DevWorkspace templates for devfile v2 of devfile registry [CRW-2500](https://issues.redhat.com/browse/CRW-2500) @vinokurig

### Bugs
* [ ] Resources Monitor Plugin doesn't work when devWorkspace engine is enable #20800 @svor 
* [ ] [devworkspace] java-spring-petclinic sample cannot connect to mysql database, running in the neighbor container #20787 @vitaliy-guliy 
* [ ] [che-samples] mongo-db sample cannot connect to mongo database #20688 @vitaliy-guliy
* [ ] Go stack sample application shows an empty page #20686 @vitaliy-guliy

### Enhancements
* [x] Persist Che-Theia preferences when DW is enabled #20622 @vinokurig 
* [ ] Allow to install plugins to Devfile V2 workspaces by using Che-Theia Plugins view #20638 @vitaliy-guliy  
* [x] [devWorkspace] Adapt ssh-plugin to avoid requesting che-server API #20859 @vinokurig 
* [x] [devWorkspace] Adapt github-auth plugin to avoid requesting che-server API #20860 @vinokurig 
* [x] [devWorkspace ] Adapt openshift-authentication plugin to avoid requesting che-server API #20857 @vinokurig
* [x] Add GitHub authentication manual flow #20995 @vinokurig 

### Unplanned
* [x] Publish CRW plugin registries (multi-arch paths) to gh pages [CRW-2644](https://issues.redhat.com/browse/CRW-2644) @vinokurig 
* [x] Unable to start the devfile v2 workspace with DW disabled - [CRW-2650](https://issues.redhat.com/browse/CRW-2650) @svor
* [x] [plugin-registry-generator] Improve plugin registry generator #21072 @svor 

### Open PRs From Last Sprint
* [x] chore: Store user preferences in a config-map https://github.com/eclipse-che/che-theia/pull/1260 @vinokurig
* [x] chore: [dev-workspace] Rework SSH plugin to store keys in the K8s secret https://github.com/eclipse-che/che-theia/pull/1277 @vinokurig

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 14 | 8 |
| @vinokurig  | 14 | 8 |
| @svor | 14 | 8 |

January 21 - H&H

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Migrate devfiles v1 to v2 (part 2) [CRW-2539](https://issues.redhat.com/browse/CRW-2539) |
| 2 | Resources Monitor Plugin doesn't work when devWorkspace engine is enable #20800 |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 | Adapt openshift-authentication plugin to avoid requesting che-server API #20857 |
| 2 | Adapt github-auth plugin to avoid requesting che-server API #20860 |
| 3 | Add GitHub authentication manual flow #20995 |
| 4 | Pre-build DevWorkspace templates for devfile v2 of devfile registry [CRW-2500](https://issues.redhat.com/browse/CRW-2500) |
| 5 | [devWorkspace] Adapt ssh-plugin to avoid requesting che-server API #20859 |
| 6 | Persist Che-Theia preferences when DW is enabled #20622 |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | Install plugins to devworkspaces [#1267](https://github.com/eclipse-che/che-theia/pull/1267 ) |
| 2 | [devworkspace] java-spring-petclinic sample cannot connect to mysql database, running in the neighbor container #20787 |
| 3 | mongo-db sample cannot connect to mongo database #20688 |
| 4 | Go stack sample application shows an empty page #20686 |

**Comment by svor** [comment]
Superseded by #21093
