### ISSUE TITLE
Editors Sprint 214

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21082]
Timeframe: February 2 - February 22

## Sprint goals
- Add support for Devfile commands running by Che-Code
- Share (in the team) the knowledge of CRW-IDEA editor productization process to prepare for CRW-Code editor productization
- Better Che-IDEA UX: fewer dialog popups on Che-IDEA start

#### CRW
- [x] Migrate `06_idea_rhel` devfile v1 to v2 [CRW#2686](https://issues.redhat.com/browse/CRW-2686)
  - depends on https://github.com/eclipse/che/issues/21031
- [x] theia build fails on s390x: keytar, drivelist [CRW#2706](https://issues.redhat.com/browse/CRW-2706)
- [x] Share the knowledge of how the CRW-IDEA productization process is organized [CRW#2717](https://issues.redhat.com/browse/CRW-2717)

#### Che-Theia
- #21117
- #21034 

#### Production-ready support of JetBrains IDEs as a Che editor https://github.com/eclipse/che/issues/20591
- #21029
- #21108
- #21110
- #21116
- #21100
- #21124

#### Production-ready support of VS Code as a Che editor https://github.com/eclipse/che/issues/20500
- #21030
- #21122

---
### Unplanned/Blockers
- [ ] Browser tab of started workspace has `che-Eclipse Che` name on CRW with Devworkspace engine enabled [CRW#2723](https://issues.redhat.com/browse/CRW-2723)
- [ ] The title of Project tree contains CHE [CRW#2731](https://issues.redhat.com/browse/CRW-2731)
- [ ] Update CRW-IDEA with the latest upstream changes [CRW#2736](https://issues.redhat.com/browse/CRW-2736)

---
## Team
| Name  | Availability | x0.6
| -- | -- | --
| @vzhukovs    | 13  | 8
| @RomanNikitenko | 13  | 8
| @azatsarynnyy | 13  | 8

---
[Previous Sprint](https://github.com/eclipse/che/issues/20999)
