### ISSUE TITLE
Che Controller Sprint #214

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21091]
### Is your task related to a problem? Please describe

This issue collects work items of the Controller Team for Sprint 214 (February 02 - February 22).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (February 02)

The previous sprint https://github.com/eclipse/che/issues/20996

## Sprint goals
- [ ] preparations for WTO 1.5 GA release 
- [ ] CRW addon deprecation after 2.15
- [ ] Release telemetry woopra plugin for DevWorkspaces + provide relevant docs
- [ ] Hardening DevWorksace / UD before the switch to the new workspace engine

### WTO
- [ ] **postponed** (the expected release date ~ mid March) Web Terminal Operator GA Release https://issues.redhat.com/projects/WTO/issues/WTO-61
      - [ ] Web Terminal has wrong size in OpenShift v.4.10 https://issues.redhat.com/projects/WTO/issues/WTO-115
      - [ ] Connecting to the WebTerminal is not finished automatically https://issues.redhat.com/browse/WTO-123  
- [ ] **postponed** https://github.com/redhat-developer/web-terminal-operator/issues/107
- [x] https://github.com/redhat-developer/web-terminal-operator/issues/102
- [x] https://github.com/redhat-developer/web-terminal-operator/issues/108
- [ ] https://github.com/redhat-developer/web-terminal-operator/issues/109

### Developer Sandbox
- [ ] Check that workspaces start successfully with OCP 4.10 Console samples #21063 

### DevWorkspace
- [x] Reuse common PVC 'claim-che-workspace' if exists instead of creating a new 'claim-devworkspace' #21038
     - [x]  https://github.com/devfile/devworkspace-operator/pull/747
- [x] https://github.com/devfile/devworkspace-operator/issues/759
- [x] https://github.com/devfile/devworkspace-operator/issues/744
- [ ] https://github.com/devfile/devworkspace-operator/issues/738

### Dashboard
- [x] https://github.com/eclipse/che/issues/21147
- [x] devfile v2 - Parent is not resolved #21098
- [x] GitHub OAuth flow is going into infinite loop if wrong configuration #21077
- [ ] As an admin, I would like to have a possibility to add information / warning header to the User Dasboard by configuring the CheCluster CR #20724
- [ ] Enable single running workspace restriction for DevWorkspaces started from UD #21032
- [x] devfile v1 -> v2 convertion enchancements #21103
- [ ] There is no CHE_DASHBOARD_URL or PLUGIN_REGISTRY_URL in the dev container #21102
- [x] https://github.com/eclipse/che/issues/21055
- [ ] New workspace isn't displayed in workspace list #20707
- [ ] Dashboard should tell even more when fails to resolve devfile from repo #20491
- [ ] Logout form Dashboard not working (DevWorkspace) #21097

### Telemetry
- Telemetry Plugin support in DevWorkspaces (workspaces started with the DevWorkspace engine) #20090

### CRW
- [x] CodeReady Workspaces is not started and displayed with error logs on OCP 4.10 when DevWorkspace enabled https://issues.redhat.com/browse/CRW-2652
- [ ] How should the new channel be handled on the OSD Addon side https://issues.redhat.com/browse/CRW-2346

### Docs

- [x] Reviewing pull requests https://issues.redhat.com/browse/RHDEVDOCS-3522
- [x] Move https://github.com/devfile/devworkspace-operator-productization-documentation to https://github.com/redhat-developer/devtools-productization 
- [ ] Add WTO productization docs to https://github.com/redhat-developer/devtools-productization 

### QE
- [x] CRW 2.15.0 pre-release testing 
- [ ] https://github.com/devfile/devworkspace-operator/issues/743
- [ ] https://issues.redhat.com/browse/CRW-2540
- [ ] https://issues.redhat.com/browse/CRW-2541
