### ISSUE TITLE
Plugins Sprint 214

### ISSUE THREAD

**Issue by svor** [eclipse/che#21093]
### CRW
* [x] Pre-build DevWorkspace templates for devfile v2 of devfile registry [CRW-2500](https://issues.redhat.com/browse/CRW-2500) @vinokurig 
* [ ] Apply UDIs for all devfiles v2 and plugins [CRW-2688](https://issues.redhat.com/browse/CRW-2688) @svor  
* [x] devfile v2 caching for devworkspace airgap support needs to be arch-aware and swap jdk images for j9 on Power/Z [CRW-2578](https://issues.redhat.com/browse/CRW-2578) @vinokurig 
* [ ] DW failed with image CrashLoopBackOff (plugin reg is not arch-aware / openj9 support missing) [CRW-2638](https://issues.redhat.com/browse/CRW-2638) @vinokurig
* [ ] Cleanup openshift-connector plugin by removing openshift-auth [CRW-2640](https://issues.redhat.com/browse/CRW-2640) @vinokurig
* [ ] The Openshift Connector plugin doesn't display the list of available imagestreams on the disconnected OCP cluster [CRW-2468](https://issues.redhat.com/browse/CRW-2468) @vinokurig 
* [ ] Update 02_java8-maven-fuse devfile to use java 11 [CRW-2591](https://issues.redhat.com/browse/CRW-2591) @vitaliy-guliy 
* [ ] Support for IBM Z and P for Fuse On SpringBoot devfile [CRW-2592](https://issues.redhat.com/browse/CRW-2592) @vitaliy-guliy

### Bugs
* [x] Resources Monitor Plugin doesn't work when devWorkspace engine is enable #20800 @svor 
* [x] [devworkspace] java-spring-petclinic sample cannot connect to mysql database, running in the neighbor container #20787 @vitaliy-guliy  
* [x] [che-samples] mongo-db sample cannot connect to mongo database #20688 @vitaliy-guliy
* [x] Go stack sample application shows an empty page #20686 @svor 

### Enhancements / Tasks
* [x] Allow to install plugins to Devfile V2 workspaces by using Che-Theia Plugins view #20638 @vitaliy-guliy 
* [ ] [Che Code dogfooding](https://github.com/che-incubator/che-code) @svor @vitaliy-guliy @vinokurig  
* [x] Update devfiles to use PROJECT_SOURCE instead of PROJECTS_ROOT #21079 @vitaliy-guliy  

### Unplanned
* [ ] Create or update gitconfig ConfigMap when user change Che Theia git settings #21115 @vinokurig
* [ ] In CRW workspace, On git push command, Title is displaying as "Eclipse che" instead "CodeReady workspaces" [CRW-2718](https://issues.redhat.com/browse/CRW-2718) @svor 

### Open PRs From Last Sprint
* [x] Install plugins to devworkspaces eclipse-che/che-theia#1267 @vitaliy-guliy

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 13 | 8 |
| @vinokurig  | 13 | 8 |
| @svor | 13 | 8 |

February 11 - H&H
February 18 - Q1 Recharge Day

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Go stack sample application shows an empty page #20686 |
| 2 | Apply UDIs for all devfiles v2 and plugins [CRW-2688](https://issues.redhat.com/browse/CRW-2688) |
| 3 | Resources Monitor Plugin doesn't work when devWorkspace engine is enable #20800 |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 | Pre-build DevWorkspace templates for devfile v2 of devfile registry [CRW-2500](https://issues.redhat.com/browse/CRW-2500) |
| 2 | devfile v2 caching for devworkspace airgap support needs to be arch-aware and swap jdk images for j9 on Power/Z [CRW-2578](https://issues.redhat.com/browse/CRW-2578) |
| 3 | DW failed with image CrashLoopBackOff (plugin reg is not arch-aware / openj9 support missing) [CRW-2638](https://issues.redhat.com/browse/CRW-2638) |
| 4 | Cleanup openshift-connector plugin by removing openshift-auth [CRW-2640](https://issues.redhat.com/browse/CRW-2640) |
| 5 | The Openshift Connector plugin doesn't display the list of available imagestreams on the disconnected OCP cluster [CRW-2468](https://issues.redhat.com/browse/CRW-2468) |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | Install plugins to devworkspaces [#1267](https://github.com/eclipse-che/che-theia/pull/1267 ) |
| 2 | [devworkspace] java-spring-petclinic sample cannot connect to mysql database, running in the neighbor container #20787 |
| 3 | mongo-db sample cannot connect to mongo database #20688 |
| 4 | Update devfiles to use PROJECT_SOURCE instead of PROJECTS_ROOT #21079 |
| 5 | Support for IBM Z and P for Fuse On SpringBoot devfile [CRW-2592](https://issues.redhat.com/browse/CRW-2592) |
| 6 | Update 02_java8-maven-fuse devfile to use java 11 [CRW-2591](https://issues.redhat.com/browse/CRW-2591) |
