### ISSUE TITLE
Plugins Sprint 215

### ISSUE THREAD

**Issue by svor** [eclipse/che#21196]
### CRW
* [ ] Apply UDIs for all devfiles v2 and plugins [CRW-2688](https://issues.redhat.com/browse/CRW-2688) @svor 
* [ ] Cleanup openshift-connector plugin by removing openshift-auth [CRW-2640](https://issues.redhat.com/browse/CRW-2640) @vinokurig 
* [ ] The Openshift Connector plugin doesn't display the list of available imagestreams on the disconnected OCP cluster [CRW-2468](https://issues.redhat.com/browse/CRW-2468) @vinokurig
* [ ] Update 02_java8-maven-fuse devfile to use java 11 [CRW-2591](https://issues.redhat.com/browse/CRW-2591) @vitaliy-guliy  
* [ ] Support for IBM Z and P for Fuse On SpringBoot devfile [CRW-2592](https://issues.redhat.com/browse/CRW-2592) @vitaliy-guliy 

### Bugs
* [ ] [resource-monitor] CPU values have wrong presentation #20895 @vitaliy-guliy 

### Enhancements / Tasks
* [ ] [che-code] Add che-github-auth extension into che-code #21206 @vinokurig
* [ ] [che-code] Add che-resource-monitor extension into che-code #21207 @vitaliy-guliy
* [ ] [Che Code dogfooding](https://github.com/che-incubator/che-code) @svor @vitaliy-guliy @vinokurig
* [ ] Cleanup devfile registry #21119 @vinokurig 

### Open PRs From Last Sprint
* [ ] chore: store gitconfig in a configmap eclipse-che/che-theia#1319 @vinokurig 
* [ ] [fix: Fix dialog title to display CodeReady Workspaces instead of Eclipse Che](https://github.com/redhat-developer/codeready-workspaces-theia/pull/41) @vinokurig 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 13 | 8 |
| @vinokurig  | 13 | 8 |
| @svor | 13 | 8 |

March 4 - H&H
February 25 - Day of Lerning

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Apply UDIs for all devfiles v2 and plugins [CRW-2688](https://issues.redhat.com/browse/CRW-2688) |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 |  chore: store gitconfig in a configmap eclipse-che/che-theia#1319 |
| 2 | [fix: Fix dialog title to display CodeReady Workspaces instead of Eclipse Che](https://github.com/redhat-developer/codeready-workspaces-theia/pull/41) |
| 3 | [che-code] Add che-github-auth extension into che-code #21206 |
| 4 | The Openshift Connector plugin doesn't display the list of available imagestreams on the disconnected OCP cluster [CRW-2468](https://issues.redhat.com/browse/CRW-2468) |
| 5 | Cleanup devfile registry #21119 |
| 6 | Cleanup openshift-connector plugin by removing openshift-auth [CRW-2640](https://issues.redhat.com/browse/CRW-2640) |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | Update 02_java8-maven-fuse devfile to use java 11 [CRW-2591](https://issues.redhat.com/browse/CRW-2591) |
| 2 | Support for IBM Z and P for Fuse On SpringBoot devfile [CRW-2592](https://issues.redhat.com/browse/CRW-2592) |
| 3 | [resource-monitor] CPU values have wrong presentation #20895 |
| 4 | [che-code] Add che-resource-monitor extension into che-code #21207 |
