### ISSUE TITLE
Editors Sprint 215

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21193]
Timeframe: February 23 - March 15

## Sprint goals
- Start work on productizing Che-Code for CRW
- Add support for Devfile commands to Che-Code
- Adapt Che-Code for dogfooding

#### CRW
- [ ] Productize Che-Code as optional editor in CRW [CRW#2744](https://issues.redhat.com/browse/CRW-2744)
- [ ] Update CRW-IDEA with the latest upstream changes [CRW#2736](https://issues.redhat.com/browse/CRW-2736)
- [ ] Browser tab of started workspace has `che-Eclipse Che` name on CRW with Devworkspace engine enabled [CRW#2723](https://issues.redhat.com/browse/CRW-2723)
- [ ] The title of Project tree contains CHE [CRW#2731](https://issues.redhat.com/browse/CRW-2731)

#### Che-IDEA
- #21212
- #21209

#### Che-Code
- #21030
- #21215

---
### Unplanned/Blockers

---
## Team
| Name  | Availability | x0.6
| -- | -- | --
| @vzhukovs    | 13  | 8
| @RomanNikitenko | 13  | 8
| @azatsarynnyy | 13  | 8

---
[Previous Sprint](https://github.com/eclipse/che/issues/21082)
