### ISSUE TITLE
Controller Sprint 215

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21200]
This issue collects work items of the Controller Team for Sprint 215 (February 23 - March 16).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (March 16)

The previous sprint https://github.com/eclipse/che/issues/21091

## Sprint goals
- [ ] Backport all important critical features and fixes to 7.44 / CRW 2.16 (DevWorkspace engine enabled by default)
- [x] Release telemetry woopra plugin for DevWorkspaces + provide relevant docs
- [x] Deprecate the CRW addon

### Important features and fixes to 7.44 / CRW 2.16

- [x] As an admin, I would like to have a possibility to add information / warning header to the User Dasboard by configuring the CheCluster CR #20724 **!(Should be also backported in 7.42.x / CRW 2.15.1)!**
- [ ] Workspace is started automatically after the convertion to devfile v2 and still has the warning #21208
- [x] Enable single running workspace restriction for DevWorkspaces started from UD #21032
- [x] Need to make sure that namespace temination will not be blocked by the DevWorkspace finalizers [#738](https://github.com/devfile/devworkspace-operator/issues/738)
- [x] https://github.com/eclipse/che/issues/21120
- [x] Failed banner is not cleared from dashboard when DevWorkspace is restarted #21134

### Web Terminal
- [x] https://github.com/redhat-developer/web-terminal-operator/issues/107
- [x] Connecting to the WebTerminal is not finished automatically https://issues.redhat.com/browse/WTO-123 
- [x] WebTerminal welcome message https://issues.redhat.com/projects/WTO/issues/WTO-98 **POC for discussion / get sprint review feedback**

### DevWorkspace
- [ ] Improve test coverage for the devworkspace-operator https://github.com/devfile/devworkspace-operator/issues/735
- [ ] DevWorkspace start occasionally fails due to FailedMount https://github.com/devfile/devworkspace-operator/issues/778
- [x] https://github.com/devfile/devworkspace-operator/issues/744
- [ ] Support inner loop kubernetes and openshift components https://github.com/eclipse/che/issues/17894

### Developer Sandbox
- [ ] Check that workspaces start successfully with OCP 4.10 Console samples #21063 

### Dashboard
- [x] New workspace isn't displayed in workspace list #20707
- [x] Dashboard should tell even more when fails to resolve devfile from repo #20491

### CRW
- [x] Deprecate CRW addon in prod / stg OSD environment https://issues.redhat.com/browse/CRW-2346

### Telemetry
- [x] Telemetry Plugin support in DevWorkspaces (workspaces started with the DevWorkspace engine) #20090 
- [ ] Provide documentation for enabling DevWorkspace telemetry and update existing docs #20820

### Docs
- [x] https://github.com/eclipse/che/issues/21005

### QA
- [ ] Airgap verification of the latest Eclipse Che with DevWorkspace engine enabled #21205
