### ISSUE TITLE
Sprint 216

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21254]
This issue collects work items of the Eclipse Che Team for Sprint 216 (March 16 - April 5).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (March 16)

The previous sprint https://github.com/eclipse/che/issues/21200

## Sprint goals
- [x] 2.15.3 CRW release
    - Backport https://github.com/eclipse/che/issues/20724 to `7.42.x` 
        - https://github.com/eclipse-che/che-dashboard/pull/478 
        - https://github.com/eclipse-che/che-operator/pull/1339
        - https://github.com/eclipse-che/che-operator/pull/1352
        - https://github.com/eclipse-che/che-operator/pull/1353
- [ ] Web Terminal Operator 1.5 GA 
- [ ] Backport all critical / blocker fixes to 7.44.x  for the next release of CRW with DevWorkspace engine enabled by default
- [x] Identify and deliver the minimal documentation for the next version of the product  
    - https://github.com/eclipse/che/issues/21264
   
### Important features and fixes to 7.44.x / 3.0

- [x] https://github.com/eclipse/che/issues/21120
- [x] #21208

### Web Terminal
- [ ] Web Terminal Operator GA Release [issues.redhat.com/projects/WTO/issues/WTO-61](http://ssues.redhat.com/projects/WTO/issues/WTO-61)

### Gateway
- [x] #20599

### DevWorkspace
- [x] DWO 0.13.0 release (will be used by both WTO 1.5 GA and next DevWorkspace based version of the product)
- [ ] Improve test coverage for the devworkspace-operator https://github.com/devfile/devworkspace-operator/issues/735
- [x] DevWorkspace start occasionally fails due to FailedMount https://github.com/devfile/devworkspace-operator/issues/778
- [ ] Support inner loop kubernetes and openshift components https://github.com/eclipse/che/issues/17894
- [x] #21185

### Developer Sandbox
- [ ] CRW `2.15.3` rollout on production (Once the warning message is defined and the release date is set need to enable it on workspaces.openshift.com clusters)

### Dashboard
- [x] #20463
- [x] https://github.com/eclipse/che/issues/21164 
- [x] https://github.com/eclipse/che/issues/21237

### CRW
- [x] [Nick] manage release of 2.15.2 CVE respins (freshmaker automation + human assistance) [there are at least 2 in flight]
- [x] [Nick] manage release of Che 7.45.0 (mostly automated except when builds fail / Operator PRs don't pass)
- [ ] [Sam] manage release of 2.15.3, once required issues are ready to build (4 images: operator, dashboard, meta, bundle)
  - [x] create Errata, SPMM ticket, RC builds, QE notification email
  - [ ] release still TBD; slipped due to PTO and other reasons
- [ ] [Nick] reskin CRW 2.x as DS 3.0 (https://issues.redhat.com/browse/CRW-2665), with new wordmarks (ASAP) and icons (April 20) (https://issues.redhat.com/browse/CRW-2701) - slipped due to delays by Brand/UX, and PTO
- [x] [Sam] https://issues.redhat.com/browse/CRW-2809 set up RH OS DS 3.x jobs in Jenkins / disable the 2.x and 2.16 jobs
- [x] [Nick] https://issues.redhat.com/browse/CRW-2812 rename crwctl -> new cli & ensure builds work

### Telemetry
- [x] https://github.com/che-incubator/che-workspace-telemetry-client/issues/88
- [x] https://github.com/che-incubator/che-workspace-telemetry-client/issues/89
- [x] https://github.com/che-incubator/devworkspace-telemetry-woopra-plugin/issues/6
- [x] https://github.com/che-incubator/che-workspace-telemetry-client/issues/92

### Docs
- [x] https://github.com/eclipse/che/issues/20614 
    - https://github.com/eclipse-che/che-docs/pull/2159 
- [x] https://github.com/eclipse/che/issues/20820
  - https://github.com/eclipse-che/che-docs/pull/2231
- [x] https://github.com/eclipse/che/issues/21005
- [ ] https://github.com/eclipse/che/issues/21264 (needs to be broken into smaller, more manageable pieces)
- [x] https://github.com/eclipse/che/issues/21272

### QA
- [x] https://github.com/eclipse/che/issues/21205

**Comment by nickboldt** [comment]
Do we have existing issues for "minimal admin guide, install guide, and end user guides for 3.0" ? @ffloreth If not we need those and I can help w/ vetting content, once we have working 3.x/3.0 builds

**Comment by themr0c** [comment]
A initial draft for this issue: https://github.com/eclipse/che/issues/21264

**Comment by nickboldt** [comment]
Another item to include https://issues.redhat.com/browse/CRW-2787 (test conversion to v2)
