### ISSUE TITLE
User guide: update content for devworkspace, in the master branch

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21285]
### Is your task related to a problem? Please describe

User guide to document only instances with devworkspace.

### Describe the solution you'd like

New User Guide outline:

* [x] **[Starting a Che workspace](https://github.com/eclipse/che/issues/21293)** @max-cx
* [x] **[Selecting an IDE](https://github.com/eclipse/che/issues/21295)** @nickboldt  
* [x] **[Adding a VS Code extension](https://github.com/eclipse/che/issues/21296)** @benoitf 
     * [x] https://github.com/eclipse-che/che-docs/pull/2265
* [ ] [MOVED to 3.1]**[Customizing workspaces' containers (and other components)](https://github.com/eclipse/che/issues/21297)** @l0rd 
* [x] **[Git credentials and settings](https://github.com/eclipse/che/issues/21298)** @dkwon17
     * [x] https://github.com/eclipse-che/che-docs/pull/2271
* [x] **[Mounting volumes, secrets, and configmaps](https://github.com/eclipse/che/issues/21299)** @dkwon17 
     * [x] https://github.com/eclipse-che/che-docs/pull/2275
     * [x] https://github.com/eclipse-che/che-docs/pull/2296
* [x] **[Kubernetes Integration](https://github.com/eclipse/che/issues/21300)** @ibuziuk 
   * [x] https://github.com/eclipse-che/che-docs/pull/2250
* [x] **TroubleShooting Che Workspaces** (update done)

**Comment by nickboldt** [comment]
Engineering ownership: blog post authors / Mario + David K + Florent (@ 50%)

**Comment by pmkovar** [comment]
Cloned in Jira: https://issues.redhat.com/browse/RHDEVDOCS-3885

**Comment by max-cx** [comment]
The _url params_ in **Selecting an IDE** are also covered by my PR https://github.com/eclipse-che/che-docs/pull/2227.

**Comment by pmkovar** [comment]
Pairing engineers with writers:

* @benoitf @deerskindoll
* @l0rd x @themr0c 
* @dkwon17 x @max-cx
