### ISSUE TITLE
Sprint 217

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21318]
This issue collects work items of the Eclipse Che Team for Sprint 217 (April 6 - April 26).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (April 6)

The previous sprint https://github.com/eclipse/che/issues/21254

## Sprint goals
- [x] CRW 2.15.3 release / rollout on Developer Sandbox with the Red Hat OpenShift Dev Spaces announcement
- [x] DWO 0.14.1 release (fixes for colisions between automounted and manually set gitconfig)
- [ ] WTO 1.5 GA release
- [ ] Red Hat OpenShift Dev Spaces release
- [ ] Identify and deliver minimal administration guide, installation guide, and user guide to migrate to che-docs main branch #21264
   
### Important bug fixes for 7.46.x / 3.0

- [x] https://github.com/eclipse/che/issues/21120
- [x] #21308
- [x] #20463
- [x] [Apply UDIs for all devfiles v2 and plugins](https://issues.redhat.com/browse/CRW-2688)
- [x] [Can't start DW with UDI](https://issues.redhat.com/browse/CRW-2862)
- [ ] #21244 @azatsarynnyy 
- [x] [_Unplanned_] [Make it possible to switch between Java version in UDI](https://issues.redhat.com/browse/CRW-2878)
- [x] [_Unplanned_] There is image tag "3.0" instead of image digests in workspace deployment(https://issues.redhat.com/browse/CRW-2887)
- [x] [After upgrading from 7.41.x converted workspaces fail to start](https://github.com/eclipse/che/issues/21329)
- [x] https://github.com/eclipse/che/issues/21032

### Docs for 3.0
- [x] Epic: #21264
    - [x] Docs: https://github.com/eclipse/che/issues/21283
    - [ ] Docs: https://github.com/eclipse/che/issues/21284
    - [ ] Docs: https://github.com/eclipse/che/issues/21285
- [x] Docs: https://github.com/eclipse/che/issues/20614 
     - https://github.com/eclipse/che/issues/20602     
     - https://github.com/eclipse-che/che-docs/pull/2269  
     - https://github.com/eclipse-che/che-docs/pull/2159  
- [ ] Docs: https://github.com/eclipse/che/issues/21005

### Important test cases for 3.0 
- [x] Dev: Run devfile conversion tool against a postgres sqldump https://issues.redhat.com/browse/CRW-2787 @benoitf 
- [ ] QA: Verify pre-created namespaces https://issues.redhat.com/browse/CRW-2855 @ibuziuk **[Verified Upstream]**  
    - [x] https://github.com/eclipse/che/issues/21331
- [ ] QA: Verify the setting of the hostname - https://issues.redhat.com/browse/CRW-2854
- [ ] QA: Verify labeling of routes - https://issues.redhat.com/browse/CRW-2854
- [ ] QA: Verify airgap @ScrewTSW **[Verified Upstream as part of #21205]** 
 

### Web Terminal
- [ ] Web Terminal Operator GA Release [issues.redhat.com/projects/WTO/issues/WTO-61](http://ssues.redhat.com/projects/WTO/issues/WTO-61)

### Developer Sandbox
- [x] CRW `2.15.3` rollout on production (Once the warning message is defined and the release date is set need to enable it on workspaces.openshift.com clusters)

### DevWorkspace
- [x] #21185

### Plugins team

- [x] https://github.com/eclipse/che/issues/21206
- [x] https://github.com/eclipse/che/issues/21115

### Editors team
- [x] Compilation errors in DS-Theia https://issues.redhat.com/browse/CRW-2842 @azatsarynnyy 
- [x] Compilation errors in DS-Theia-endpoint https://issues.redhat.com/browse/CRW-2843 @azatsarynnyy 
- [ ] [_Unplanned_] #21244 @azatsarynnyy 
- [x] [_Unplanned_] #21345 @azatsarynnyy 
- [ ] Start work on productizing Che-Code for DevSpaces https://issues.redhat.com/browse/CRW-2744 @RomanNikitenko 
- [ ] Update DevSpaces-IDEA with the latest upstream changes https://issues.redhat.com/browse/CRW-2736 @vzhukovs 
- [ ] #21030 @azatsarynnyy 

###  Productization team

* Mykhailo is back, not sure yet at what capacity
* Sam is out for 1 week PTO Apr 11-15
* Nick has no PTO this sprint other than Easter Fri+Mon long weekend (as does all of RH Canada)

- [x] [Nick] manage release of 2.15.3, including CVE respins https://errata.devel.redhat.com/advisory/90619
- [x] [Nick] reskin CRW 2.x as DS 3.0 (https://issues.redhat.com/browse/CRW-2665), with new wordmarks and icons (https://issues.redhat.com/browse/CRW-2701 + https://issues.redhat.com/browse/DTUX-1193)
- [x] [Nick] ensure 3.0 theia builds are working in brew https://issues.redhat.com/browse/CRW-2842
- [x] [?] fix ansible bug w/ cert install https://issues.redhat.com/browse/CRW-2865
- [x] [?] fix 3.0 theia builds to work on s390x https://issues.redhat.com/browse/CRW-2864 
- [x] [?] Can't start DW with UDI - https://issues.redhat.com/browse/CRW-2862

**Comment by nickboldt** [comment]
To help with next sprint planning and/or to pick up unplanned work if time permits, here's downstream queries for blockers & criticals/P1s: 

Blockers for 3.0 https://issues.redhat.com/browse/CRW-2475?jql=project%20%3D%20CRW%20AND%20fixVersion%20in%20(3.0.0.GA)%20AND%20priority%20in%20(Blocker)%20AND%20issuetype%20!%3D%20%22QE%20Task%22%20AND%20resolution%20is%20null%20ORDER%20BY%20fixversion%2Cpriority%2Ckey%2Ccreated%20DESC
Criticals for 3.0 https://issues.redhat.com/browse/CRW-2357?jql=project%20%3D%20CRW%20AND%20fixVersion%20in%20(3.0.0.GA)%20AND%20priority%20in%20(Critical)%20AND%20issuetype%20!%3D%20%22QE%20Task%22%20AND%20resolution%20is%20null%20ORDER%20BY%20fixversion%2Cpriority%2Ckey%2Ccreated%20DESC
