### ISSUE TITLE
Sprint 218

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21351]
This issue collects work items of the Eclipse Che Team for Sprint 218 (April 27 - May 17).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (April 27)

The previous sprint https://github.com/eclipse/che/issues/21318

## Sprint goals
- [ ] Red Hat OpenShift Dev Spaces 3.0 release
- [x] Identify and deliver minimal administration guide, installation guide, and user guide to migrate to che-docs main branch #21264
- [ ] WTO 1.5 GA release
 
### Important bug fixes for 7.46.x / 3.0

- [x] #21244 @azatsarynnyy 
- [x] My daily authentication dance #21352

[Blockers for 3.0](https://issues.redhat.com/browse/CRW-2475?jql=project%20%3D%20CRW%20AND%20fixVersion%20in%20(3.0.0.GA)%20AND%20priority%20in%20(Blocker)%20AND%20issuetype%20!%3D%20%22QE%20Task%22%20AND%20resolution%20is%20null%20ORDER%20BY%20fixversion%2Cpriority%2Ckey%2Ccreated%20DESC)
- [x] https://issues.redhat.com/browse/CRW-2854 Validate Router sharding with Dev Spaces 3.0
- [x] https://issues.redhat.com/browse/CRW-2855 Validate Namespace uses
- [x] https://issues.redhat.com/browse/CRW-2882 Cloning a project after launching factory doesn't work for GitLab and Bitbucket repos
- [x] https://issues.redhat.com/browse/CRW-2907 Factory link redirects to Dashboard, not to start workspace page
- [x] https://issues.redhat.com/browse/CRW-2908 ZIP project is not cloned into the workspace
- [x] https://issues.redhat.com/browse/CRW-2948 Plugins cannot be installed into the DS workspace
- [ ] https://issues.redhat.com/browse/CRW-2837 Create new marketing & download pages for Dev Spaces [tracking item for productization, work is being done by Marketing with delivery on GA day]
- [x] https://issues.redhat.com/browse/CRW-2964 Missing env vars for plugin registry after loading a v1 devfile (was: Plugin registry became invalid after migration from 2.15 -> 3.0)

[Criticals for 3.0](https://issues.redhat.com/browse/CRW-2357?jql=project%20%3D%20CRW%20AND%20fixVersion%20in%20(3.0.0.GA)%20AND%20priority%20in%20(Critical)%20AND%20issuetype%20!%3D%20%22QE%20Task%22%20AND%20resolution%20is%20null%20ORDER%20BY%20fixversion%2Cpriority%2Ckey%2Ccreated%20DESC)
- [x] https://issues.redhat.com/browse/CRW-2690 DevWorkspace Dashboard doesn't handle 401 server error after user session is expired
- [x] https://issues.redhat.com/browse/CRW-2786 CRW 2.15.101 bundle metadata tech preview operator is not installable if other operators like Jaeger, Kiali are installed on the same cluster [needs to be validated with DS 3 / determine which operator(s) are causing the conflict

### Docs for 3.0
- [x] Epic: #21264
    - [x] Docs: https://github.com/eclipse/che/issues/21284
    - [x] Docs: https://github.com/eclipse/che/issues/21285
- [x] Docs: https://github.com/eclipse/che/issues/21005
- [x] https://issues.redhat.com/browse/CRW-2357 [KI] Upgrading an instance with the {devworkspace} engine enabled requires manual steps
- [x] https://issues.redhat.com/browse/CRW-2748 [RN] Che-Theia Plugins view support for DevWorkspace based workspaces

### Important test cases for 3.0 
- [x] QA: Verify pre-created namespaces https://issues.redhat.com/browse/CRW-2855 @ibuziuk
- [x] QA: Verify the setting of the hostname - https://issues.redhat.com/browse/CRW-2854 @tolusha 
- [x] QA: Verify labeling of routes - https://issues.redhat.com/browse/CRW-2854 @tolusha 
- [ ] QA: Verify airgap - https://github.com/eclipse/che/issues/21393 @ScrewTSW @themr0c 
 
### Web Terminal
- [ ] Web Terminal Operator GA Release [WTO-61](https://issues.redhat.com/projects/WTO/issues/WTO-61)

### DevWorkspace
- [ ] https://github.com/eclipse/che/issues/21340 (added by @l0rd)
- [ ] Make default PVC size configurable [#740](https://github.com/devfile/devworkspace-operator/issues/740)

### Dashboard
- [ ] Add workspaces default editor and component in CheCluster CRD #21353

### Gateway 
- [x] 401 Unauthorized" error page when OCP OAuth session is expired in Dashboard https://issues.redhat.com/browse/CRW-2875
- [x] https://github.com/eclipse/che/issues/20599
- [ ] https://github.com/eclipse/che/issues/21352

### Developer Sandbox
- [ ] Decompose 'Migrating CodeReady Workspaces to Red Hat OpenShift Dev Spaces' epic to sub-tasks - https://issues.redhat.com/browse/CRT-1489

### Plugins team

- [ ] https://github.com/eclipse/che/issues/20583 (added by @l0rd)
- [x] [could not connect to remote localhost:9990 [EAP XP3 Microprofile devfile]](https://issues.redhat.com/browse/CRW-2966)
- [x] [ZIP project is not cloned into the workspace](https://issues.redhat.com/browse/CRW-2908)
- [x] [Plugins cannot be installed into the DS workspace](https://issues.redhat.com/browse/CRW-2948 )
- [x] Cannot install plugins from Che-Theia plugin view on minikube #21381

### Editors team
- [x] Adapt DS-IDEA image to the latest upstream changes in Che-IDEA https://issues.redhat.com/browse/CRW-2736
- [x] #21244
- [ ] Che-Code productization for DevSpaces https://issues.redhat.com/browse/CRW-2744
- [ ] curl/git does not seem to use certs in /public-certs https://issues.redhat.com/browse/CRW-2873
- [x] #21007
- [x] #21030
- [x] Update DS-IDEA to consume the latest Che-IDEA (based on 2022 version) https://issues.redhat.com/browse/CRW-2977
- [ ] (Unplanned) Dev workspace V2 devfiles have empty workspace panel https://issues.redhat.com/browse/CRW-2820

###  Productization team

P1
* [x] [CRW-2902](https://issues.redhat.com/browse/CRW-2902) Python devfile is not working with Devspaces 3.0
* [x] [CRW-2887](https://issues.redhat.com/browse/CRW-2887) There is image tag "3.0" instead of image digests in workspace deployment
* [ ] [CRW-2817](https://issues.redhat.com/browse/CRW-2817) rename/move crw-samples projects to devspaces-samples org; update devfile references

P2
* [x] https://github.com/eclipse/che/issues/21349
* [x] https://github.com/eclipse/che/issues/21348
* [x] [CRW-2904](https://issues.redhat.com/browse/CRW-2904) pylint executables not found in path on udi image
* [x] [CRW-2591](https://issues.redhat.com/browse/CRW-2591) Update 02_java8-maven-fuse devfile to use java 11
* [ ] [CRW-2903](https://issues.redhat.com/browse/CRW-2903) improve CSV related image generation - use built container instead of re-running build scripts
* [ ] [CRW-2619](https://issues.redhat.com/browse/CRW-2619) build python lang server from source / install via cachito

P-Epic (to start this sprint (?) and continue into the next)
* [ ] [CRW-2459](https://issues.redhat.com/browse/CRW-2459) Improve codeready-workspaces-images local build story for better ease of use (and to allow GHA builds)
* [ ] [CRW-2444](https://issues.redhat.com/browse/CRW-2444) Use Cachito for container sources (where possible)
* [ ] [CRW-1102](https://issues.redhat.com/browse/CRW-1102) Provide Dev Spaces scratch builds for PR checks

**Comment by nickboldt** [comment]
Additional blockers/criticals:

[Blockers for 3.0](https://issues.redhat.com/browse/CRW-2475?jql=project%20%3D%20CRW%20AND%20fixVersion%20in%20(3.0.0.GA)%20AND%20priority%20in%20(Blocker)%20AND%20issuetype%20!%3D%20%22QE%20Task%22%20AND%20resolution%20is%20null%20ORDER%20BY%20fixversion%2Cpriority%2Ckey%2Ccreated%20DESC)
- [ ] https://issues.redhat.com/browse/CRW-2740 `DevWorkspace install load tests on real-world infra (OCP 4.9 RHPDS)` fails on CRW deployment step
- [ ] https://issues.redhat.com/browse/CRW-2837 Create new marketing & download pages for Dev Spaces
- [ ] https://issues.redhat.com/browse/CRW-2854 Validate Router sharding with Dev Spaces 3.0
- [ ] https://issues.redhat.com/browse/CRW-2855 Validate Namespace uses
- [ ] https://issues.redhat.com/browse/CRW-2882 Cloning a project after launching factory doesn't work for GitLab and Bitbucket repos
- [ ] https://issues.redhat.com/browse/CRW-2907 Factory link redirects to Dashboard, not to start workspace page
- [ ] https://issues.redhat.com/browse/CRW-2908 ZIP project is not cloned into the workspace

[Criticals for 3.0](https://issues.redhat.com/browse/CRW-2357?jql=project%20%3D%20CRW%20AND%20fixVersion%20in%20(3.0.0.GA)%20AND%20priority%20in%20(Critical)%20AND%20issuetype%20!%3D%20%22QE%20Task%22%20AND%20resolution%20is%20null%20ORDER%20BY%20fixversion%2Cpriority%2Ckey%2Ccreated%20DESC)
- [ ] https://issues.redhat.com/browse/CRW-2357 DOC ONLY - [KI] Upgrading an instance with the {devworkspace} engine enabled requires manual steps
- [ ] https://issues.redhat.com/browse/CRW-2638 DW failed with image CrashLoopBackOff (plugin reg is not arch-aware / openj9 support missing)
- [ ] https://issues.redhat.com/browse/CRW-2690 DevWorkspace Dashboard doesn't handle 401 server error after user session is expired
- [ ] https://issues.redhat.com/browse/CRW-2748 Che-Theia Plugins view support for DevWorkspace based workspaces
- [ ] https://issues.redhat.com/browse/CRW-2786 CRW 2.15.101 bundle metadata tech preview operator is not installable if other operators like Jaeger, Kiali are installed on the same cluster [needs to be validated with DS 3 / determine which operator(s) are causing the conflict
- [ ] https://issues.redhat.com/browse/CRW-2820 Dev workspace V2 devfiles have empty workspace panel
