### ISSUE TITLE
Sprint 219

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21395]
This issue collects work items of the Eclipse Che Team for Sprint 219 (May 18 - June 7).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (May 18)

The previous sprint https://github.com/eclipse/che/issues/21351

## Sprint goals
- [x] Red Hat OpenShift Dev Spaces 3.0 release
- [x] WTO 1.5 GA release
 
### Blockers / Criticals for 3.0
- [x]  [proxy] Dev workspace V2 devfiles have empty workspace panel https://issues.redhat.com/browse/CRW-2820

### Web Terminal
- [x] Web Terminal Operator GA Release [WTO-61](https://issues.redhat.com/projects/WTO/issues/WTO-61)

### DWO
- [ ] Extend the DevWorkspaceTemplate spec with containers contributions https://github.com/devfile/devworkspace-operator/issues/656
- [ ] As an Admin I want to configure default pvc storage properties from the Eclipse Che CR #21405
- [x] Check PVC cleanup pods for failure (events and status) https://github.com/devfile/devworkspace-operator/issues/551

### Dashboard
- [x] [Cannot create a factory from repository (without devfile) that has uppercase characters in name ](https://github.com/eclipse/che/issues/21338)
- [x] https://github.com/eclipse/che/issues/21353

### Gateway 
- [x] https://github.com/eclipse/che/issues/20599

### Docs
- [x] https://github.com/eclipse/che/issues/21393
- [ ] https://github.com/eclipse/che/issues/21401

### Operator
- [x] https://github.com/eclipse/che/issues/20758
- [x] https://github.com/eclipse/che/issues/21387
- [x] https://github.com/eclipse/che/issues/21268
- [x] https://github.com/eclipse/che/issues/20804
- [x] https://github.com/eclipse/che/issues/21399

### chectl
- [x] https://github.com/eclipse/che/issues/21311

### Technical debt
- [ ] Decommissioning PostgreSQL database #21374
- [ ] https://github.com/eclipse/che/issues/21411

### Developer Sandbox
- [ ] Move WTO and DWO to the dedicated namespace https://issues.redhat.com/browse/CRT-1405
- [x] Update user removal / deprovisioning flow for Red Hat OpenShift Dev Spaces https://issues.redhat.com/browse/CRT-1504

### Telemetry
- [x] https://github.com/che-incubator/che-workspace-telemetry-client/issues/88
- [x] https://github.com/che-incubator/devworkspace-telemetry-woopra-plugin/issues/6
- [x] https://github.com/che-incubator/che-workspace-telemetry-client/issues/92

### Editors
- [x] Dev workspace V2 devfiles have empty workspace panel https://issues.redhat.com/browse/CRW-2820
- [ ] Che-Code productization for DevSpaces https://issues.redhat.com/browse/CRW-2744
- [x] #21030
- [x] #21137
- [x] #21439

### Plugins

- [x] https://github.com/eclipse/che/issues/20583
- [x] https://github.com/eclipse/che/issues/21145
- [ ] [CRW-2478](https://issues.redhat.com/browse/CRW-2478) - Airgapped: Go LS tools unable to install by default **[TODO: document as a known issue]**
- [x] [CRW-2592](https://issues.redhat.com/browse/CRW-2592) - Support for IBM Z and P for Fuse On SpringBoot devfile
- [x] [CRW-3003](https://issues.redhat.com/browse/CRW-3003) - Java EAP Maven Microprofile debugging fails to start - connection refused

### Productization items:

P1: 3.0
- [x] Prepare 3.0 RC build for QE & [track in spreadsheet](https://docs.google.com/spreadsheets/d/1TllnofYIlA7yTn7hIa8-LojGpHR1ACk1hVP-7fg_wsY/edit#gid=964445818)
- [ ] [89695](https://errata.devel.redhat.com/advisory/89695) - Load images into errata & push to stage
- [ ] [SPMM-9036](https://issues.redhat.com/browse/SPMM-9036) create dsc/sources/manifests for cobrien to push to prod
  - [x] [CRW-2869](https://issues.redhat.com/browse/CRW-2869) fix the stage-mw-release step in publishing dsc and sources
- [ ] [CRW-2837](https://issues.redhat.com/browse/CRW-2837) verify new developers.redhat.com page is live after push to prod 

P1: 3.1
- [ ] [CRW-2665](https://issues.redhat.com/browse/CRW-2665) Rename CodeReady Workspaces to Red Hat OpenShift Dev Spaces (RHOSDS)
  - [ ] [CRW-2817](https://issues.redhat.com/browse/CRW-2817) rename/move crw-samples projects to devspaces-samples org; update devfile references
  - [ ] [CRW-2822](https://issues.redhat.com/browse/CRW-2822) refactor CRW_ prefix in openshift templates and operator code to use DS_ prefix
  - [ ] [CRW-2839](https://issues.redhat.com/browse/CRW-2839) Create CI folder for new devspaces jobs, separate from CRW_CI folder
  - [ ] [CRW-2810](https://issues.redhat.com/browse/CRW-2810) Link to new (or renamed existing) product page content in Comet
  - [ ] [CRW-2804](https://issues.redhat.com/browse/CRW-2804) Request removal of tech preview operator-bundle `codeready-workspaces2` from OCP 4.9-4.10 indexes, once CRW 3.0 is live
  - [ ] [CRW-2837](https://issues.redhat.com/browse/CRW-2837) Create new marketing & download pages for Dev Spaces

P2
- [ ] [CRW-2619](https://issues.redhat.com/browse/CRW-2619) build python lang server from source / install via cachito
- [x] [CRW-2903](https://issues.redhat.com/browse/CRW-2903) improve CSV related image generation - use built container instead of re-running build scripts

Epics
 - [CRW-2459](https://issues.redhat.com/browse/CRW-2459) Improve codeready-workspaces-images local build story for better ease of use (and to allow GHA builds)
 - [CRW-2444](https://issues.redhat.com/browse/CRW-2444) Use Cachito for container sources (where possible)
 - [CRW-1102](https://issues.redhat.com/browse/CRW-1102) Provide Dev Spaces scratch builds for PR checks

**Comment by nickboldt** [comment]
Productization items:

P1
- [ ] [CRW-2665](https://issues.redhat.com/browse/CRW-2665) Rename CodeReady Workspaces to Red Hat OpenShift Dev Spaces (RHOSDS)
  - [ ] [CRW-2817](https://issues.redhat.com/browse/CRW-2817) rename/move crw-samples projects to devspaces-samples org; update devfile references
  - [ ] [CRW-2822](https://issues.redhat.com/browse/CRW-2822) refactor CRW_ prefix in openshift templates and operator code to use DS_ prefix
  - [ ] [CRW-2839](https://issues.redhat.com/browse/CRW-2839) Create CI folder for new devspaces jobs, separate from CRW_CI folder
  - [ ] [CRW-2810](https://issues.redhat.com/browse/CRW-2810) Link to new (or renamed existing) product page content in Comet
  - [ ] [CRW-2837](https://issues.redhat.com/browse/CRW-2837) Create new marketing & download pages for Dev Spaces

P2
- [ ] [CRW-2619](https://issues.redhat.com/browse/CRW-2619) build python lang server from source / install via cachito
- [ ] [CRW-2903](https://issues.redhat.com/browse/CRW-2903) improve CSV related image generation - use built container instead of re-running build scripts

Epics
 - [CRW-2459](https://issues.redhat.com/browse/CRW-2459) Improve codeready-workspaces-images local build story for better ease of use (and to allow GHA builds)
 - [CRW-2444](https://issues.redhat.com/browse/CRW-2444) Use Cachito for container sources (where possible)
 - [CRW-1102](https://issues.redhat.com/browse/CRW-1102) Provide Dev Spaces scratch builds for PR checks

**Comment by l0rd** [comment]
I would like to add https://github.com/eclipse/che/issues/21411

**Comment by azatsarynnyy** [comment]
> For editors:
> 
> * vscode productization
> * offline openvsx (@benoitf)
> * [vscode commands](https://github.com/eclipse/che/issues/21030)
> * JetBrains Gateway support

Thanks, Mario. We already have all these items in the current sprint.
Our highest priority now is  https://issues.redhat.com/browse/CRW-2820
