### ISSUE TITLE
Sprint 220

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21438]
This issue collects work items of the Eclipse Che Team for Sprint 220 (June 8 - June 28).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (June 8th)

The previous sprint https://github.com/eclipse/che/issues/21395

## Sprint goals
- [x] Red Hat OpenShift Dev Spaces 3.0 release
- [x] Migrate CodeReady Workspace 2.15.4 to Red Hat OpenShift DevSpaces of the Developer Sandbox staging cluster
- [ ] Make che-code production ready (long-running goal for a couple of sprints)
- [x] Eclipse Che CR v2 (implementation + docs updates)
 
### Blockers / Criticals for 3.0
- [x] https://issues.redhat.com/browse/CRW-3050 (moved to  3.1)

### Web Terminal
- [x] Update internal productization docs 

### DWO
- [x] https://github.com/devfile/devworkspace-operator/issues/656
- [x] https://github.com/eclipse/che/issues/21405
- [x] https://github.com/devfile/devworkspace-operator/issues/852
- [x] Check PVC cleanup pods for failure (events and status) https://github.com/devfile/devworkspace-operator/issues/551
- [x] https://github.com/devfile/devworkspace-operator/issues/853

### Dashboard
- [x] https://github.com/eclipse/che/issues/21454
- [x] https://github.com/eclipse/che/issues/21353
- [x] https://github.com/eclipse/che/issues/21429
- [x] https://github.com/eclipse/che/issues/21428
- [x] https://github.com/eclipse/che/issues/21449

### Gateway 
- [x] https://github.com/eclipse/che/issues/20599

### Git 0 Config
- [ ] Resolve Devfiles from private GH/BB/Gitlab repos even if Che OAuth App is not configured #21189
- [x] https://github.com/eclipse/che/issues/21421

### Automation
- [x] https://github.com/eclipse/che/issues/21446
- [x] https://github.com/eclipse/che/issues/21445

### Machine exec
- [x] https://github.com/eclipse/che/issues/21431 

### Docs
- [x] https://github.com/eclipse/che/issues/21393
- [x] https://github.com/eclipse/che/issues/21444
- [ ] https://github.com/eclipse/che/issues/21401

### Operator
- [x] https://github.com/eclipse/che/issues/20758
- [x] https://github.com/eclipse/che/issues/20804
- [x] https://github.com/eclipse/che/issues/21399

### Technical debt
- [ ] https://github.com/eclipse/che/issues/21411

### Developer Sandbox
- [x] Move WTO and DWO to the dedicated namespace https://issues.redhat.com/browse/CRT-1405
- [x] Migrate CodeReady Workspace 2.15.4 to Red Hat OpenShift DevSpaces of the Developer Sandbox staging cluster

## Image Puller
- [x] https://github.com/eclipse/che/issues/21448

### Editors
- [ ] Che-Code productization for DevSpaces https://issues.redhat.com/browse/CRW-2744
- [x] #21473
- [x] [Unplanned] #21455
- [x] [Unplanned] #21471
- [x] #21212
- [x] [Unplanned] #21139
- [x] [Unplanned] #21141
- [x] [Unplanned] #21140
- [x] [Unplanned] #21494
- [x] [Unplanned] #21493
- [x] [Unplanned] #21511

### Plugins
- [x] Support OAuth flow for Gitlab SaaS #21435
- [ ] [Cannot start IDEA tech preview devfile](https://issues.redhat.com/browse/CRW-3014)
- [x] [JDK 11 workspace shows default JDK is 1.8](https://issues.redhat.com/browse/CRW-3013)
- [x] [Jboss EAP XP Microprofile and JBoss EAP 7.4 use two separate users and containers](https://issues.redhat.com/browse/CRW-3039) 
- [x] Cannot install any plugin if sample repo doesn't have extensions.json file #21422
- [ ] After Inlining of the extensions.json and che-theia-plugins.yaml an extetntion is not installed #21423
- [ ] Validate full air gap scenario with che-code #21443

### Productization items:

P1: 3.0 (postponed from previous sprint due to blockers)
- [x] Prepare 3.0 GA build for QE & [track in spreadsheet](https://docs.google.com/spreadsheets/d/1TllnofYIlA7yTn7hIa8-LojGpHR1ACk1hVP-7fg_wsY/edit#gid=964445818)
- [x] [89695](https://errata.devel.redhat.com/advisory/89695) - Load images into errata & push to stage
- [x] [SPMM-9036](https://issues.redhat.com/browse/SPMM-9036) create dsc/sources/manifests for cobrien to push to prod
- [x] [CRW-2837](https://issues.redhat.com/browse/CRW-2837) verify new developers.redhat.com page is live after push to prod 

P1: 3.1 (postponed from previous sprint due to delay of 3.0)
- [x] [CRW-2725](https://issues.redhat.com/browse/CRW-2725) Re-enable replaces directive in operator-bundle sync*.sh and csv files
- [ ] [CRW-2665](https://issues.redhat.com/browse/CRW-2665) Rename CodeReady Workspaces to Red Hat OpenShift Dev Spaces (RHOSDS)
  - [x] [CRW-2817](https://issues.redhat.com/browse/CRW-2817) rename/move crw-samples projects to devspaces-samples org; update devfile references
  - [ ] [CRW-2822](https://issues.redhat.com/browse/CRW-2822) refactor CRW_ prefix in openshift templates and operator code to use DS_ prefix
  - [ ] [CRW-2839](https://issues.redhat.com/browse/CRW-2839) Create CI folder for new devspaces jobs, separate from CRW_CI folder
  - [x] [CRW-2810](https://issues.redhat.com/browse/CRW-2810) Link to new (or renamed existing) product page content in Comet
  - [x] [CRW-2804](https://issues.redhat.com/browse/CRW-2804) Request removal of tech preview operator-bundle `codeready-workspaces2` from OCP 4.9-4.10 indexes, once CRW 3.0 is live
  - [x] [CRW-2837](https://issues.redhat.com/browse/CRW-2837) Create new marketing & download pages for Dev Spaces

P2
- [ ] [CRW-2619](https://issues.redhat.com/browse/CRW-2619) build python lang server from source / install via cachito - in progress from prev sprint - Mykhailo
- [x] [CRW-2958](https://issues.redhat.com/browse/CRW-2958) sync problems between ds-theia (upstream) and ds-images/ds-theia (midstream) - in progress from prev sprint - Mykhailo

Epics
 - [CRW-2459](https://issues.redhat.com/browse/CRW-2459) Improve codeready-workspaces-images local build story for better ease of use (and to allow GHA builds)
 - [CRW-2444](https://issues.redhat.com/browse/CRW-2444) Use Cachito for container sources (where possible)
 - [CRW-1102](https://issues.redhat.com/browse/CRW-1102) Provide Dev Spaces scratch builds for PR checks

**Comment by l0rd** [comment]
I would like to discuss 
- https://github.com/eclipse/che/issues/21140 vs https://github.com/eclipse/che/issues/21354
- https://github.com/eclipse/che/issues/21411
- https://github.com/eclipse/che/issues/21431
- https://github.com/eclipse/che/issues/21430
