### ISSUE TITLE
Sprint 222

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21551]
This issue collects work items of the Eclipse Che Team for Sprint 222 (July 20 - August 09).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (July 19th)

The previous sprint https://github.com/eclipse/che/issues/21503

## Sprint goals
- [ ] Dev Spaces 3.1 with DWO 0.15.2 release 
- [ ] WTO 1.6 release for OpenShift 4.11
- [ ] Migrate CodeReady Workspace 2.15.4 to Red Hat OpenShift DevSpaces on the Developer Sandbox [CRT-1489](https://issues.redhat.com/browse/CRT-1489)
- [x] Make che-code production ready (long-running goal for a couple of sprints; target no later than Che 7.52)
- [ ] Improve dogfooding experience:
     - [x] Grant all users permissions for building images from workspaces 
     - [ ] Add monitoring stack 
     - [ ] Add logs access (loki)
 
### WTO
- [ ] 1.6 release for 4.11
- [x] Custom idling timeout does not affect on the terminal with DWO 0.15.2 https://issues.redhat.com/browse/WTO-132

### DWO
- [x] https://github.com/devfile/devworkspace-operator/issues/892
- [x] https://github.com/devfile/devworkspace-operator/issues/656
- [x] https://github.com/eclipse/che/issues/21405
- [x] https://github.com/devfile/devworkspace-operator/issues/852

### Dashboard
- https://github.com/eclipse/che/issues/21561
- https://github.com/eclipse/che/issues/21560
- https://github.com/eclipse/che/issues/21554
- https://github.com/eclipse/che/issues/20738
- Refactor the Factory loading flow https://github.com/eclipse/che/issues/21449
- Error message when trying to delete multiple workspaces from the Dashboard https://github.com/eclipse/che/issues/21532
- Dashboard does not redirect to IDE automatically during startup (refresh is required) https://github.com/eclipse/che/issues/21308
- https://github.com/eclipse/che/issues/21512

### Git 0 Config
- [ ] Git zero config with OAuth flow #20583
- [x] Resolve Devfiles from private GH/BB/Gitlab repos even if Che OAuth App is not configured #21189
- [ ] Support OAuth flow for Bitbucket SaaS #21517
- [x] When the git repository is on gitlab.com .che/che-editor.yaml is ignored #21562

### Automation
- [x] https://github.com/eclipse/che/issues/21445

### Machine exec
- [x] https://github.com/eclipse/che/issues/21549 
- [x] https://github.com/eclipse/che/issues/21431

### Docs / Blogs
- [ ] https://github.com/eclipse-che/blog/pull/29
- [ ] https://github.com/eclipse/che/issues/21401

### Operator
- [x] Deprecate (remove if not possible to deprecate) https://operatorhub.io/operator/eclipse-che with a reference to https://artifacthub.io/packages/helm/eclipse-che/eclipse-che
- [ ] https://github.com/eclipse/che/issues/21559
- [x] https://github.com/eclipse/che/issues/21579

### chectl
- [x] On minikube, not able to start a workspace with che installed with chectl next #21557

### Technical debt
- [ ] https://github.com/eclipse/che/issues/21411

### Developer Sandbox
- [ ]  Migrate CodeReady Workspace 2.15.4 to Red Hat OpenShift DevSpaces on the Developer Sandbox [CRT-1489](https://issues.redhat.com/browse/CRT-1489)

### Editors
- [ ] Productize vscode as an OpenShift Dev Spaces editor https://issues.redhat.com/browse/CRW-2744
- [x] Unsupported platform: linux s390x BE (support code-rhel8 on s390x) https://issues.redhat.com/browse/CRW-3171
- [x] #21548
- [x] #21537
- [x] Increase --idle-timeout to 30 minutes for all editors (upstream / downstream 3.1) https://issues.redhat.com/browse/CRW-3154
- [x] [Unplanned] #21324 (https://issues.redhat.com/browse/CRW-3169)
- [x] [Unplanned] #21573

### Plugins
- [x] Include VSCode in OpenShift Dev Spaces (plugin-registry and samples) [CRW-2288](https://issues.redhat.com/browse/CRW-2288)
- [x] https://github.com/eclipse/che/issues/21555
- [x] https://github.com/eclipse/che/issues/21443
- [x] https://github.com/eclipse/che/issues/21423
- [ ] Use mvn commands to run and debug for java-maven-based devfiles #20791
- [x] [Unplanned] #21574
- [x] #21587
- [x] #21581
- [x] Add devworkspaces with VSCode editor into the devfile registry [CRW-3191](https://issues.redhat.com/browse/CRW-3191)
- [ ] [Unplanned] #21436

### Productiztion

* [ ] Release DS 3.1.0 [first week Aug]
* [ ] Release Che 7.51 [Jul 20]
* [ ] [CRW-3080](https://issues.redhat.com/browse/CRW-3080) **EPIC** Make Container Images Eligible for Source Containers (move away from pkgs.devel lookaside caching / enable source containers)
* [ ] [CRW-3078](https://issues.redhat.com/browse/CRW-3078) review polling rules for all containers
* [ ] [CRW-3079](https://issues.redhat.com/browse/CRW-3079) general refactoring/cleanup of DS 3.x jobs
