### ISSUE TITLE
Sprint 223

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21615]
This issue collects work items of the Eclipse Che Team for Sprint 222 (August 10 - August 30).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (August 10th)

The previous sprint https://github.com/eclipse/che/issues/21551

## Sprint goals
- [x] Dev Spaces 3.0.1 and 3.1.0 release
- [x] WTO 1.5.1 release
- [ ] WTO 1.6 release for OpenShift 4.11
- [x] Migrate CodeReady Workspace 2.15.4 to Red Hat OpenShift DevSpaces on the Developer Sandbox [CRT-1489](https://issues.redhat.com/browse/CRT-1489)
- [ ] Che-Code Productization (3.1 tech-preview, focus on airgap and whitelabel/branding)
 
### WTO
- [x] 1.5.1 release
- [ ] 1.6 release for 4.11
- [x] Add virtctl tool for interacting with VMs https://issues.redhat.com/browse/WTO-129 
- [x] [WTO-142](https://issues.redhat.com/projects/WTO/issues/WTO-142?filter=allopenissues) Configure network policies for WTO onboarding to che-dev cluster

### DWO
- [x] https://github.com/devfile/devworkspace-operator/issues/656
- [x] https://github.com/eclipse/che/issues/21405
- [x] https://github.com/devfile/devworkspace-operator/issues/852
- [x] https://github.com/devfile/devworkspace-operator/issues/892

### Dashboard
- [x] Remove all CheCluster API v1 dependencies from the User Dashboard component https://github.com/eclipse/che/issues/21594
- [x] Provides OpenVSX CheCluster URL to user containers https://github.com/eclipse/che/issues/21600
- [x] As a user I want to have a possibility to start from scratch / create an empty workspace #21554
- [ ] Handle gracefully when an invalid devfile is found in a git repository #20738
- [x] Improve UX on the dashboard page when a workspace is stopped / idled https://github.com/eclipse/che/issues/21540
- [ ] [UX] Instead of error message "you are not allowed to start more workspaces", ask user if they want to switch to open workspace or close all workspaces in order to open this new one #21359
- [x] Workspace fails to start when VS Code is the editor and the git repository has no devfile #21560
- [x] Unexpected error null https://github.com/eclipse/che/issues/21618
- [ ] Error message when trying to delete multiple workspaces from the Dashboard #21532
- [ ] Getting Started workspace fails to start if there is exsiting workspace #21561
- [ ] Reuse already stored data in the new tab where factory flow runs #21512

### Git 0 Config
- [x] https://github.com/eclipse/che/issues/21517
- [x] https://github.com/eclipse/che/issues/21627

### Automation
- [x] https://github.com/eclipse/che/issues/21445

### Machine exec
- [x] https://github.com/eclipse/che/issues/21431

### chectl
- [x] https://github.com/eclipse/che/issues/21363

### Operator
 - [x] https://github.com/eclipse/che/issues/21622 
 - [x] https://github.com/eclipse/che/issues/21619
 - [ ] https://github.com/eclipse/che/issues/21584 
 - [x] https://github.com/eclipse/che/issues/21577
 - [x] https://github.com/eclipse/che/issues/21617
 - [x] https://github.com/eclipse/che/issues/21582
 - [x] Specifying a node selector for every workspace pod in the CheCluster CR doesn't work  https://issues.redhat.com/browse/CRW-3224
 - [x] https://github.com/eclipse/che/issues/21628
 - [x] https://github.com/eclipse/che/issues/21620
 - [x] https://github.com/eclipse/che/issues/21637

### Technical debt
- [ ] https://github.com/eclipse/che/issues/21411

### Developer Sandbox
- [x]  Migrate CodeReady Workspace 2.15.4 to Red Hat OpenShift DevSpaces on the Developer Sandbox [CRT-1489](https://issues.redhat.com/browse/CRT-1489)

### Editors
- [ ] Support whitelabel/branding of VSCode editor in Dev Spaces https://issues.redhat.com/browse/CRW-3199
- [x] #21626
- [x] [Unplanned] Task vscode-reh-web-linux-s390x-min not defined https://issues.redhat.com/browse/CRW-3281

### Plugins
- [x] #20791 @vitaliy-guliy 
- [x] #21436 @vinokurig 
- [x] #21621
- [x] #21372
- [x] Upgrade Dependency Analytics plugin to latest version [CRW-2208](https://issues.redhat.com/browse/CRW-2208)
- [x] Factory creation from pull request on GitHub fails with 'Internal Server Error occurred' error [CRW-3202](https://issues.redhat.com/browse/CRW-3202)
- [x] [airgap] "Application is not available" error when run JBoss EAP XP 3.0 Bootable Jar sample application [CRW-3246](https://issues.redhat.com/browse/CRW-3246)
- [x] Devfile samples contain outdated OC login command [CRW-3214](https://issues.redhat.com/browse/CRW-3214)
- [ ] Add missing recommended extensions to .vscode/extensions.json in all che-samples #21644
- [ ] #20809
- [ ] #21443 @svor 

### Productiztion
Prod team tasks, current sprint
* [x] Release Che 7.52 [Aug 10] - Sam taking over for Mykhailo
* [x] Release DS 3.0.1 [week of Aug 15?] - Blocker https://issues.redhat.com/browse/CRW-3243
* [x] Release DS 3.1.0 [week of Aug 15?] - Blocker https://issues.redhat.com/browse/CRW-3215
  * [x] [CRW-3250](https://issues.redhat.com/browse/CRW-3250) Remove RPMs and base image references from the manifest-all.txt file
  * [x] [CRW-3079](https://issues.redhat.com/browse/CRW-3079) general refactoring/cleanup of DS 3.x jobs - refactoring is done, but need to do some final deletes once 3.1 is live & close the issue
* [x] [CRW-2208](https://issues.redhat.com/browse/CRW-2208) Upgrade Dependency Analytics plugin to latest version (working with Plugins team)
* [x] [CRW-3219](https://issues.redhat.com/browse/CRW-3219) Publish filtered IIBs to Quay for all 3.x CIs and on request 3.yy ERs and RCs (almost done, just some content to add to jenkins job statuses and QE email generation job)

Ongoing Epics

* [ ] [CRW-3080](https://issues.redhat.com/browse/CRW-3080) Make Container Images Eligible for Source Containers (move away from pkgs.devel lookaside caching / enable source containers)

Future Epics (listed for visibility)

* [ ] [CRW-2459](https://issues.redhat.com/browse/CRW-2459) Improve codeready-workspaces-images local build story for better ease of use (and to allow GHA builds)
* [ ] [SSML-9185](https://issues.redhat.com/browse/SSML-9185) SSML.PS.2.1.1 Software Integrity Verification Information (4 sub tasks)
* [ ] other P1 SSML requirements https://issues.redhat.com/secure/Dashboard.jspa?selectPageId=12343615 (P1 need to be completed by EOY 2022)

### Docs / Blogs
- [ ] https://github.com/eclipse/che/issues/21401

**Comment by nickboldt** [comment]
Prod team tasks, current sprint
* [ ] Release Che 7.52 [Aug 10] - Sam taking over for Mykhailo
* [ ] Release DS 3.0.1 [week of Aug 15?] - Blocker https://issues.redhat.com/browse/CRW-3243
* [ ] Release DS 3.1.0 [week of Aug 15?] - Blocker https://issues.redhat.com/browse/CRW-3215
  * [ ] [CRW-3250](https://issues.redhat.com/browse/CRW-3250) Remove RPMs and base image references from the manifest-all.txt file
  * [ ] [CRW-3079](https://issues.redhat.com/browse/CRW-3079) general refactoring/cleanup of DS 3.x jobs - refactoring is done, but need to do some final deletes once 3.1 is live & close the issue

* [ ] [CRW-3080](https://issues.redhat.com/browse/CRW-3080) **EPIC** Make Container Images Eligible for Source Containers (move away from pkgs.devel lookaside caching / enable source containers)

Future sprint Epics

* [ ] [CRW-2459](https://issues.redhat.com/browse/CRW-2459) Improve codeready-workspaces-images local build story for better ease of use (and to allow GHA builds)
* [ ] [SSML-9185](https://issues.redhat.com/browse/SSML-9185) SSML.PS.2.1.1 Software Integrity Verification Information (4 sub tasks)
* [ ] other P1 SSML requirements https://issues.redhat.com/secure/Dashboard.jspa?selectPageId=12343615 (P1 need to be completed by EOY 2022)
