### ISSUE TITLE
Sprint 224

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21653]
This issue collects work items of the Eclipse Che Team for Sprint 224 (August 31 - September 20).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (August 30th)

The previous sprint https://github.com/eclipse/che/issues/21615

## Sprint goals
- [ ] Preparations for Dev Spaces 3.2 release with DWO 0.16.0 (the release is planned between Sep 26th and October 4th)
- [ ] Airgap support for Che-Code editor (both upstream and downstream)
    - [ ] Use embedded openvsx registry on dogfooding
    - [ ] Downstream embedded openvsx registry @nickboldt 
 
### Blockers for 3.2 that need to be backported in 7.52.x
- [x] As an Admin I want to configure default pvc storage properties from the Eclipse Che CR https://github.com/eclipse/che/issues/21405 
- [ ] Can not start a workspace with &storageType=ephemeral attribute https://github.com/eclipse/che/issues/21569
- [x] Getting Started samples on the website are not processed correctly - 'session' and 'code' attributes are not dropped during startup https://github.com/eclipse/che/issues/21655 (? should be backported to 7.52.x)
- [ ] ~~Workspace fails to start if there is an existing workspace with such a name #21561~~ 
 **Sleeps till 3.3 / Bulk change on the UD level** - https://github.com/eclipse-che/che-dashboard/pull/622
- [x] fix: Fix url resolving in the bitbucket api client https://github.com/eclipse-che/che-server/pull/346
- [x] https://github.com/eclipse/che/issues/21695

### WTO
- [ ] Improve and simplify the Web Terminal Operator release process https://issues.redhat.com/browse/WTO-150
- [ ] Simplify implementation for exec component https://issues.redhat.com/browse/WTO-149
 

### DWO
- [x] Automounted gitconfig overwrites existing git config for project clone https://github.com/devfile/devworkspace-operator/issues/911
- [x] https://github.com/devfile/devworkspace-operator/issues/656
- [x] https://github.com/devfile/devworkspace-operator/issues/852

### Dashboard
- [x] Adding a container registry from Dashboard User preferences doesn't work https://github.com/eclipse/che/issues/21589 (**potentially backport to 7.52.x**)
- [x] Dashboard does not respect CheCluster CR changes https://github.com/eclipse/che/issues/21654
- [x] Dashboard tiles not listed in filename order; instead alpha-ordered by tile name https://issues.redhat.com/browse/CRW-2782 (**potentially backport to 7.52.x**)
- [x] Dashboard should not patch DevWorkspace during startup (replica set is scaling up and down resulting in slow workspace startup) #21664 (**potentially backport to 7.52.x**)
- [x] https://github.com/eclipse/che/issues/20738
- [ ] Error message when trying to delete multiple workspaces from the Dashboard #21532
- [ ] Reuse already stored data in the new tab where factory flow runs #21512
- [ ] Explain how to develop che-dashboard with Eclipse Che https://github.com/eclipse/che/issues/21667
- [x] https://github.com/eclipse/che/issues/21669
- [x] https://github.com/eclipse/che/issues/21671
- [x] .che/che-editor.yaml content is not taken into account when running a workspace #21639

### Git 0 Config
- [x] Support OAuth flow for GitHub Enterprise Server https://github.com/eclipse/che/issues/21485

### Automation
- [x] https://github.com/eclipse/che/issues/21445

### chectl
- [x] https://github.com/eclipse/che/issues/21363

### Operator
 - [x] https://github.com/eclipse/che/issues/21522
 - [x] https://github.com/eclipse/che/issues/21649
 - [x] https://github.com/eclipse/che/issues/21577
 - [x] Update the `:identity-provider:` and `:identity-provider-id:` attributes both upstream and downstream https://issues.redhat.com/browse/RHDEVDOCS-4296
 - [x] https://github.com/eclipse/che/issues/21582
 - [x] https://github.com/eclipse/che/issues/21642
 - [x] Include newer ose proxy images in operator deployment? (4.10 or 4.11?) https://issues.redhat.com/browse/CRW-3263
 - [x] clean up unneeded refs to DWO assets in DS operator sync scripts https://issues.redhat.com/browse/CRW-3262
 - [x] https://github.com/eclipse/che/issues/21681
 - [x] 'dsc 3.2.0 server:deploy' command deployed Eclipse Che 7.53.0 https://issues.redhat.com/browse/CRW-3335
 - [x] rollback.sh script has failed being run just after 1-prepare.sh, and CRW application remained not available https://issues.redhat.com/browse/CRW-3289
 - [x] OpenShift Dev Spaces Operator 3.1.0 is breaking due to issue with conversion webhook https://issues.redhat.com/browse/CRW-3315
 
### Telemetry

- [ ] Telemetry Plugin support for Che-Code editor #21661

### Editors
- [x] Support whitelabeling/branding of VSCode editor in Dev Spaces https://issues.redhat.com/browse/CRW-3199
- [x] #21673 [CRW-3320](https://issues.redhat.com/browse/CRW-3320)
- [x] #21629 [CRW-3261](https://issues.redhat.com/browse/CRW-3261)
- [x] [Unplanned] #21686
- [x] [Unplanned] #21708
- [x] [Unplanned] #21712
- [x] [Unplanned] #21711

### Plugins
 - [ ] Check OAuth tokens validity when workspace restarts #21640 @vinokurig 
 - [x] A few plug-ins do not load when using a sample .NET workspace [CRW-3288](https://issues.redhat.com/browse/CRW-3288) @svor
- [x] #21644 @vitaliy-guliy 
- [x] Add missing recommended extensions to .vscode/extensions.json [CRW-3302](https://issues.redhat.com/browse/CRW-3302) @vitaliy-guliy
- [x] Use redhat.fabric8-analytics instead of redhat.dependency-analytics in devfiles [CRW-3216](https://issues.redhat.com/browse/CRW-3216) @vitaliy-guliy 
- [ ] #20809 @vinokurig 
- [ ] #21443 @svor 
- [x] #21662
- [ ] Create offline VS Code Marketplace (airgap support for vscode as default editor) [CRW-3295](https://issues.redhat.com/browse/CRW-3295)
- [x] Plugins are not installed after creating a workspace by the factory #21635

### Productization
Sam:
- [x] https://github.com/eclipse/che/issues/21617
- [x] https://github.com/eclipse/che/issues/21363
- [x] [CRW-3136](https://issues.redhat.com/browse/CRW-3136) traefik :: migrate to cachito
- [ ] [CRW-3137](https://issues.redhat.com/browse/CRW-3137) imagepuller :: migrate to cachito
- [x] [Eclipse Simrel 2022-09](https://wiki.eclipse.org/Category:SimRel-2022-09) - GA Sept 14

Mykailo:
- [ ] [CRW-2619](https://issues.redhat.com/browse/CRW-2619) udi: python :: migrate to cachito
  - [ ] [CRW-1927](https://issues.redhat.com/browse/CRW-1927) [python] Option to run a single test through Test Explorer does not work [must switch to VSCode Editor to get latest ms-python extension]
  - [ ] [CRW-2630](https://issues.redhat.com/browse/CRW-2630) Upgrade pip version in the image used in Python devfile
- [ ] [CRW-3194](https://issues.redhat.com/browse/CRW-3194) udi: lombok :: use fetch-artifacts for lombok jar

Nick:
- [x] [CRW-1759](https://issues.redhat.com/browse/CRW-1759) subscribe to weekly DS 3.x builds
- [x] [Deploying Dev Spaces pre-release builds](https://issues.redhat.com/browse/CRW-3219): users should be able to do that using `dsc server:deploy` @tolusha @nickboldt 
- [ ] [CRW-3178](https://issues.redhat.com/browse/CRW-3178) prevent inclusion of quay.io/devspaces images in stable branch builds of registries and operator-bundle
- [x] [CRW-3276](https://issues.redhat.com/browse/CRW-3276) getLatestImageTags returns the wrong IIB values

Other tasks we can help with / contribute PRs for:

- [ ] https://github.com/eclipse/che/issues/21586 Deduplicate samples between che-samples and devspaces-samples 
- [ ] [RHDEVDOCS-4227](https://issues.redhat.com/browse/RHDEVDOCS-4227) Building a custom devfile registry (also [CRW-2275](https://issues.redhat.com/browse/CRW-2275) )

Ongoing & Future Epics

- [ ]  [CRW-3080](https://issues.redhat.com/browse/CRW-3080) Make Container Images Eligible for Source Containers (move away from pkgs.devel lookaside caching / enable source containers)
  - [ ] [CRW-3193](https://issues.redhat.com/browse/CRW-3193) udi: kamel :: migrate to cachito (golang)
- [ ]  [CRW-2459](https://issues.redhat.com/browse/CRW-2459) Improve codeready-workspaces-images local build story for better ease of use (and to allow GHA builds)
- [ ]  [SSML-9185](https://issues.redhat.com/browse/SSML-9185) SSML.PS.2.1.1 Software Integrity Verification Information (4 sub tasks)
- [ ]  other P1 SSML requirements https://issues.redhat.com/secure/Dashboard.jspa?selectPageId=12343615 (P1 need to be completed by EOY 2022)

### Docs / Blogs
- [x] Adding "Networking requirements" section to the Preparing the installation documentation - https://github.com/eclipse/che/issues/21648 
- [x] https://github.com/eclipse/che/issues/21670
- [x] https://github.com/eclipse-che/che-docs/pull/2408

**Comment by nickboldt** [comment]
Prod team tasks for next sprint (I'm on PTO, won't be around for the planning)

Sam:
- [ ] https://github.com/eclipse/che/issues/21617
- [ ] https://github.com/eclipse/che/issues/21363
- [ ] https://issues.redhat.com/browse/CRW-3136 traefik :: migrate to cachito
- [ ] https://issues.redhat.com/browse/CRW-3137 imagepuller :: migrate to cachito
- [ ] Eclipse Simrel 2022-09 - https://wiki.eclipse.org/Category:SimRel-2022-09 [GA Sept 14]

Mykailo:
- [ ] https://issues.redhat.com/browse/CRW-2619 udi: python :: migrate to cachito
  - [ ] [CRW-1927](https://issues.redhat.com/browse/CRW-1927) [python] Option to run a single test through Test Explorer does not work [must switch to VSCode Editor to get latest ms-python extension]
  - [ ] [CRW-2630](https://issues.redhat.com/browse/CRW-2630) Upgrade pip version in the image used in Python devfile
- [ ] https://issues.redhat.com/browse/CRW-3194 udi: lombok :: use fetch-artifacts for lombok jar
- [ ] https://issues.redhat.com/browse/CRW-3193 udi: kamel :: migrate to cachito (golang)

Nick:
- [ ] [CRW-1759](https://issues.redhat.com/browse/CRW-1759) subscribe to weekly DS 3.x builds
- [ ] [CRW-3178](https://issues.redhat.com/browse/CRW-3178) prevent inclusion of quay.io/devspaces images in stable branch builds of registries and operator-bundle
- [ ] [CRW-3276](https://issues.redhat.com/browse/CRW-3276) getLatestImageTags returns the wrong IIB values

Other tasks we can help with / contribute PRs for:

- [ ] https://github.com/eclipse/che/issues/21586 Deduplicate samples between che-samples and devspaces-samples 
- [ ] https://issues.redhat.com/browse/RHDEVDOCS-4227 Building a custom devfile registry

Ongoing & Future Epics

- [ ]  [CRW-3080](https://issues.redhat.com/browse/CRW-3080) Make Container Images Eligible for Source Containers (move away from pkgs.devel lookaside caching / enable source containers)
- [ ]  [CRW-2459](https://issues.redhat.com/browse/CRW-2459) Improve codeready-workspaces-images local build story for better ease of use (and to allow GHA builds)
- [ ]  [SSML-9185](https://issues.redhat.com/browse/SSML-9185) SSML.PS.2.1.1 Software Integrity Verification Information (4 sub tasks)
- [ ]  other P1 SSML requirements https://issues.redhat.com/secure/Dashboard.jspa?selectPageId=12343615 (P1 need to be completed by EOY 2022)

**Comment by l0rd** [comment]
- https://github.com/eclipse/che/issues/21629
- https://github.com/eclipse/che/issues/21606
- [Deploying Dev Spaces pre-release builds](https://issues.redhat.com/browse/CRW-3219): users should be able to do that using `dsc server:deploy`
