### ISSUE TITLE
Sprint 225

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21705]
This issue collects work items of the Eclipse Che Team for Sprint 225 (September 21 - October 11).
The previous sprint https://github.com/eclipse/che/issues/21653

## Sprint goals

TBD

### DWO
- [ ] [Tens of outdated configuration options in documentation are confusing users](https://issues.redhat.com/browse/CRW-3355) ⭐ 
- [ ] [Support specifying the schedulerName of workspace pods](https://issues.redhat.com/browse/CRW-3323) ⭐ 
- [ ] [Workspace startup fails when the Devfile specifies cpuRequest or cpuLimit and the editor is VS Code](https://issues.redhat.com/browse/CRW-3356) ⭐
- [ ] [Support Devfile v2 components of type Kubernetes](https://issues.redhat.com/browse/CRW-3364) ⭐
- [ ] [Support "podman run" from within a workspace](https://issues.redhat.com/browse/CRW-3367) ⭐
- [x] devfile/devworkspace-operator/issues/920
- [x] devfile/devworkspace-operator/issues/930
- [x] devfile/devworkspace-operator/issues/929

### Dashboard
- [x] https://github.com/eclipse/che/issues/20738
- [x] https://github.com/eclipse/che/issues/21532
- [ ] [Improving the support for building container images](https://issues.redhat.com/browse/CRW-3366) ⭐
- [x] #21703

### chectl
- [x] [CheCluster Custom Resource Definition is not removed after uninstalling](https://issues.redhat.com/browse/CRW-3318) ⭐
- [x] #21363

### Operator
 - [x] #21710
 - [x] #21649
 - [x] #21599
 - [x] #21695
 - [x] #21676
 - [x] #21751
 - [ ] #21584
 - [x] #21445
 - [ ] [Allow to deploy Dev Spaces from fast channel using dsc](https://issues.redhat.com/browse/CRW-3353)
 - [x] [Provide Dev Spaces equivalents for dropped CheCustomProperties](https://issues.redhat.com/browse/CRW-3342)
 - [x] [Remove mention of Dev Spaces from the Che Operator CRD (and re-add it downstream when running sync*.sh)](https://issues.redhat.com/browse/CRW-2949)

### Telemetry

- [x] #21661

### Editors
- [x] [Blocker] [Che-Code automatic rebase against upstream VS Code is failed](https://github.com/eclipse/che/issues/21712)
- [x] [Blocker] [Che-Code automatic rebase against upstream VS Code is failed](https://github.com/eclipse/che/issues/21727)
- [x] [Blocker] [Che-Code automatic rebase against upstream VS Code is failed](https://github.com/eclipse/che/issues/21730)
- [x] [Make it possible to run Che-Code on UBI 9](https://issues.redhat.com/browse/CRW-3261) ⭐
- [x] #21673
  - [x] [PowerShell VS Code extension failed to start](https://issues.redhat.com/browse/CRW-3320) ⭐
  - [x] #21616
- [x] [It's not possible to run a Task in Che-Code if it's not che type](https://issues.redhat.com/browse/CRW-3365) ⭐
- [ ] [Unplanned] [Document how to apply a custom branding to Che-Code editor](https://github.com/eclipse/che/issues/21682)

### Plugins
- [ ] [Create offline VS Code Marketplace (airgap support for vscode as default editor)](https://issues.redhat.com/browse/CRW-3295) ⭐
- [ ] [Update VSCode OpenShift Connector plugin to latest 0.6.0](https://issues.redhat.com/browse/CRW-3344) ⭐ 
- [x] #21696
- [x] #21640
- [x] [Unplanned] BitBucket Factory Link does not work like GitHub [CRW-3359](https://issues.redhat.com/browse/CRW-3359)
- [x] [Unplanned] 'Unable to create injector' error when create 'bitbucket-oauth-config' secret [CRW-3341](https://issues.redhat.com/browse/CRW-3341)

#### Sam
- [x] [Deprecate CRW images on RHEC as they are now EOL](https://issues.redhat.com/browse/CRW-3337)
- [x] #21363
- [x] [imagepuller :: migrate to cachito](https://issues.redhat.com/browse/CRW-3137)
- [ ] DS 3.2 RC and GA coordination (starting this sprint, continues into the next one)
  - [ ] [update spreadsheet](https://docs.google.com/spreadsheets/d/1TllnofYIlA7yTn7hIa8-LojGpHR1ACk1hVP-7fg_wsY/edit#gid=187232987) with latest RC image lists
  - [ ] [update Errata](https://github.com/redhat-developer/devspaces/blob/devspaces-3-rhel-8/product/getLatestImageTags.sh#L113) w/ NVRs
  - [ ] ensure [NVRs in the errata](https://errata.devel.redhat.com/advisory/98977) are pushed to stage
  - [ ] ensure containers in the errata are (mostly) [A grade](https://errata.devel.redhat.com/errata/container/98977)
  - [ ] use [Jenkins job](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/send-email-qe-build-list_3.2/) to send QE an email announcing each RC (and optionally disabling the jobs to avoid respins)
  - [ ] [coordinating with QE and Releng](https://issues.redhat.com/browse/SPMM-10736) to push the dsc and sources to rcm-guest on QE signoff day / before GA push day
- [ ] [operator :: migrate to fetch-artifacts (or commit files directly?) for sources](https://issues.redhat.com/browse/CRW-3138)

#### Mykailo
- [x] #21552 (including integration in plugin reg and operator, and any downstreaming)
- [ ] [CRW-3370](https://issues.redhat.com/browse/CRW-3370) pylint executable not found in path on udi image / CVP test failing (python 3.9 update)
- [ ] [udi: kamel :: migrate to cachito (golang)](https://issues.redhat.com/browse/CRW-3193)

#### Nick
- [ ] [Improving the support for building container images -- suport rootless podman/buildah](https://issues.redhat.com/browse/CRW-3366) ⭐ 
- [ ] [Prevent inclusion of quay.io/devspaces images in stable branch builds of registries and operator-bundle (continued from prev sprint)](https://issues.redhat.com/browse/CRW-3178)
- [ ] [Make it possible to run Che-Code on UBI 9](https://issues.redhat.com/browse/CRW-3261) [support downstreaming efforts here, explore what's needed to start releasing RHEL 9 based containers]
- [ ] See also other [long-running epics from previous sprint](https://github.com/eclipse/che/issues/21653#issuecomment-1227627808)

**Comment by nickboldt** [comment]
Prod tasks:

Sam:
- [ ] https://github.com/eclipse/che/issues/21363
- [ ] [CRW-3137](https://issues.redhat.com/browse/CRW-3137) imagepuller :: migrate to cachito [almost done]
- [ ] DS 3.2 RC and GA coordination (starting this sprint, continues into the next one)
  - [ ] [update spreadsheet](https://docs.google.com/spreadsheets/d/1TllnofYIlA7yTn7hIa8-LojGpHR1ACk1hVP-7fg_wsY/edit#gid=187232987) with latest RC image lists
  - [ ] [update Errata](https://github.com/redhat-developer/devspaces/blob/devspaces-3-rhel-8/product/getLatestImageTags.sh#L113) w/ NVRs
  - [ ] ensure [NVRs in the errata](https://errata.devel.redhat.com/advisory/98977) are pushed to stage
  - [ ] ensure containers in the errata are (mostly) [A grade](https://errata.devel.redhat.com/errata/container/98977)
  - [ ] use [Jenkins job](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/send-email-qe-build-list_3.2/) to send QE an email announcing each RC (and optionally disabling the jobs to avoid respins)
  - [ ] [coordinating with QE and Releng](https://issues.redhat.com/browse/SPMM-10736) to push the dsc and sources to rcm-guest on QE signoff day / before GA push day
- [ ] [CRW-3080](https://issues.redhat.com/browse/CRW-3080) Make Container Images Eligible for Source Containers (move away from pkgs.devel lookaside caching / enable source containers) - picking away at the subtasks here

Mykailo:
- [ ] https://github.com/eclipse/che/issues/21552
- [ ] [CRW-3193](https://issues.redhat.com/browse/CRW-3193) udi: kamel :: migrate to cachito (golang)

Nick:
- [ ] [CRW-3178](https://issues.redhat.com/browse/CRW-3178) prevent inclusion of quay.io/devspaces images in stable branch builds of registries and operator-bundle (continued from prev sprint)
- [ ] [Make it possible to run Che-Code on UBI 9](https://issues.redhat.com/browse/CRW-3321) [support downstreaming efforts here, explore what's needed to start releasing RHEL 9 based containers]

See also other long-running epics in https://github.com/eclipse/che/issues/21653#issuecomment-1227627808

**Comment by AObuchow** [comment]
DWO:
Annotate DWO created PVC's https://github.com/devfile/devworkspace-operator/issues/920
Add testing framework for DWO reconcile loop https://github.com/devfile/devworkspace-operator/issues/930
Add code coverage check for DWO repository https://github.com/devfile/devworkspace-operator/issues/929
