### ISSUE TITLE
Sprint 226

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21745]
This issue collects work items of the Eclipse Che Team for Sprint 226 (October 12 - November 1st).
The previous sprint https://github.com/eclipse/che/issues/21705

## Sprint goals

- [x] Dev Spaces 3.2 upgrade on Developer Sandbox
- [ ] Offline VS Code Marketplace (airgap support for vscode as default editor) for 3.3
- [ ] Improving the support for building container images (first iteration disabled by default)

### DWO

- [ ] [Improving the support for building container images](https://issues.redhat.com/browse/CRW-3366) ⭐
     #21770
     devfile/devworkspace-operator#884
- [ ] [Support specifying the schedulerName of workspace pods](https://issues.redhat.com/browse/CRW-3323) ⭐ 
- [ ] [Workspace startup fails when the Devfile specifies cpuRequest or cpuLimit and the editor is VS Code](https://issues.redhat.com/browse/CRW-3356) ⭐
- [ ] [Support Devfile v2 components of type Kubernetes](https://issues.redhat.com/browse/CRW-3364) ⭐
- [ ] [Support "podman run" from within a workspace](https://issues.redhat.com/browse/CRW-3367) ⭐
- [x] devfile/devworkspace-operator/issues/920
- [x] devfile/devworkspace-operator/issues/930
- [x] devfile/devworkspace-operator/issues/929

### Dashboard

- [x] https://github.com/eclipse/che/issues/21737
- [x] https://github.com/eclipse/che/issues/20738
- [x]  [Improving the support for building container images](https://issues.redhat.com/browse/CRW-3366) ⭐ 
       https://github.com/eclipse/che/issues/21756
- [x] https://github.com/eclipse/che/issues/21595
- [x] https://github.com/eclipse/che/issues/21750
- [x] https://github.com/eclipse/che/issues/21532
- [x] https://github.com/eclipse/che/issues/21744

### Operator
 - [ ] [Allow to deploy Dev Spaces from fast channel using dsc](https://issues.redhat.com/browse/CRW-3353)
 - [x] [Image Puller doesn't work outside of openshift-operators namespace](https://issues.redhat.com/browse/CRW-3467)
 - [x] https://github.com/eclipse/che/issues/21752
 - [x] https://github.com/eclipse/che/issues/21754
 - [x] #21784
 - [x] #21445
 - [x]  [Improving the support for building container images](https://issues.redhat.com/browse/CRW-3366) ⭐ 
       #21768
       #21769
 
### chectl
- [x] #21363

### Che Server
- [ ] https://github.com/eclipse/che/issues/21184 @vitaliy-guliy

### Developer Sandbox
- [x] Update Grafana dashboard for Dev Spaces https://issues.redhat.com/browse/CRT-1600

### Technical Debt
-  [ ] [Tens of outdated configuration options in documentation are confusing users](https://issues.redhat.com/browse/CRW-3355) ⭐ 
    - [ ] https://github.com/eclipse/che/issues/21411   
- [x] https://github.com/eclipse/che/issues/21374

### Image Puller
- [x] Image puller operator kube-rbac-proxy should not be pulled from gcr.io https://issues.redhat.com/browse/CRW-3379 ⭐ 

### Editors
- [x] https://github.com/eclipse/che/issues/21738
- [x] #21400
- [x] #21392 [CRW-3412](https://issues.redhat.com/browse/CRW-3412)
- [x] #21625
- [x] #21651
- [x] #21215
- [x] #21723
- [x] [Unplanned] #21775

### Plugins
- [ ] [Create offline VS Code Marketplace (airgap support for vscode as default editor)](https://issues.redhat.com/browse/CRW-3295) ⭐
- [x] Following Doc does not seem to lead to /home/user/.m2/settings.xml [CRW-3418](https://issues.redhat.com/browse/CRW-3418) ⭐
- [x] Factory creation from Bitbucket repo with OAuth fails on DS 3.2.0.RC-09-30 [CRW-3409](https://issues.redhat.com/browse/CRW-3409)
- [x] #21640
- [x] Factory creation from gitlab server repo with personal access token fails on DS 3.2.0.RC-10-05 [CRW-3431](https://issues.redhat.com/browse/CRW-3431)
- [x] Cannot clone github project from private repo(without devfile.yaml) [CRW-3371](https://issues.redhat.com/browse/CRW-3371)
- [ ] Testing Git zero flow #21753
- [x] .NET related plugins unavailable in OpenVSX [CRW-3245](https://issues.redhat.com/browse/CRW-3245)
- [ ] Che ignores my devfile.yaml and che-editor.yaml updates (because che-server URLFetcher sometimes caches its results) #21184 @vitaliy-guliy
- [ ] Update VSCode OpenShift Connector plugin to latest 0.7 (or newer) to support odo 3.0 [CRW-3344](https://issues.redhat.com/browse/CRW-3344)
- [x] [Unplanned] VS Code is run in {{che-code-runtime-description}} container [CRW-3444](https://issues.redhat.com/browse/CRW-3444)
- [x] [Unplanned] [AirGap] Plugin registry doesn't start with local openvsx registry in the restricted environment [CRW-3481](https://issues.redhat.com/browse/CRW-3481)

### Productization
Sam:
- [x] https://github.com/eclipse/che/issues/21363
- [x] DS 3.2 RC and GA coordination (starting this sprint, continues into the next one)
  - [x] [update spreadsheet](https://docs.google.com/spreadsheets/d/1TllnofYIlA7yTn7hIa8-LojGpHR1ACk1hVP-7fg_wsY/edit#gid=187232987) with latest RC image lists
  - [x] [update Errata](https://github.com/redhat-developer/devspaces/blob/devspaces-3-rhel-8/product/getLatestImageTags.sh#L113) w/ NVRs
  - [x] ensure [NVRs in the errata](https://errata.devel.redhat.com/advisory/98977) are pushed to stage
  - [x] ensure containers in the errata are (mostly) [A grade](https://errata.devel.redhat.com/errata/container/98977)
  - [x] use [Jenkins job](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/send-email-qe-build-list_3.2/) to send QE an email announcing each RC (and optionally disabling the jobs to avoid respins)
  - [x] [coordinating with QE and Releng](https://issues.redhat.com/browse/SPMM-10736) to push the dsc and sources to rcm-guest on QE signoff day / before GA push day
- [ ] [CRW-3138](https://issues.redhat.com/browse/CRW-3138) operator :: migrate to fetch-artifacts (or commit files directly?) for sources

Mykailo:
- [ ] https://github.com/eclipse/che/issues/21552 (including downstreaming)
- [x] [CRW-3193](https://issues.redhat.com/browse/CRW-3193) udi: kamel :: migrate to cachito (golang)

Nick:
- [x] [CRW-3178](https://issues.redhat.com/browse/CRW-3178) prevent inclusion of quay.io/devspaces images in stable branch builds of registries and operator-bundle (continued from prev sprint)
  - [ ] [CRW-3429](https://issues.redhat.com/browse/CRW-3429) plugin registry external_images.txt refer to quay.io
- [x] [CRW-3428](https://issues.redhat.com/browse/CRW-3428) Transform tag to SHA in CRD
- [ ] [CRW-3080](https://issues.redhat.com/browse/CRW-3080) Make Container Images Eligible for Source Containers
See also other long-running epics in https://github.com/eclipse/che/issues/21653#issuecomment-1227627808

**Comment by nickboldt** [comment]
Prod tasks:

Sam:
- [ ] https://github.com/eclipse/che/issues/21363
- [ ] DS 3.2 RC and GA coordination (starting this sprint, continues into the next one)
  - [ ] [update spreadsheet](https://docs.google.com/spreadsheets/d/1TllnofYIlA7yTn7hIa8-LojGpHR1ACk1hVP-7fg_wsY/edit#gid=187232987) with latest RC image lists
  - [ ] [update Errata](https://github.com/redhat-developer/devspaces/blob/devspaces-3-rhel-8/product/getLatestImageTags.sh#L113) w/ NVRs
  - [ ] ensure [NVRs in the errata](https://errata.devel.redhat.com/advisory/98977) are pushed to stage
  - [ ] ensure containers in the errata are (mostly) [A grade](https://errata.devel.redhat.com/errata/container/98977)
  - [ ] use [Jenkins job](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/send-email-qe-build-list_3.2/) to send QE an email announcing each RC (and optionally disabling the jobs to avoid respins)
  - [ ] [coordinating with QE and Releng](https://issues.redhat.com/browse/SPMM-10736) to push the dsc and sources to rcm-guest on QE signoff day / before GA push day
- [ ] [CRW-3138](https://issues.redhat.com/browse/CRW-3138) operator :: migrate to fetch-artifacts (or commit files directly?) for sources

Mykailo:
- [ ] https://github.com/eclipse/che/issues/21552 (including downstreaming)
- [ ] [CRW-3193](https://issues.redhat.com/browse/CRW-3193) udi: kamel :: migrate to cachito (golang)

Nick:
- [ ] [CRW-3178](https://issues.redhat.com/browse/CRW-3178) prevent inclusion of quay.io/devspaces images in stable branch builds of registries and operator-bundle (continued from prev sprint)
  - [ ] [CRW-3429](https://issues.redhat.com/browse/CRW-3429) plugin registry external_images.txt refer to quay.io
- [ ] [CRW-3428](https://issues.redhat.com/browse/CRW-3428) Transform tag to SHA in CRD
- [ ] [CRW-3080](https://issues.redhat.com/browse/CRW-3080) Make Container Images Eligible for Source Containers
See also other long-running epics in https://github.com/eclipse/che/issues/21653#issuecomment-1227627808
