### ISSUE TITLE
Sprint 227

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21785]
This issue collects work items of the Eclipse Che Team for Sprint 227 (November 2nd - November 22).
The previous sprint https://github.com/eclipse/che/issues/21745

## Sprint goals

- [x] DWO 0.17.0 upstream release (identify minimal feature set for DWO 0.17.x for Dev Spaces 3.3)
- [x] Offline VS Code Marketplace (airgap support for vscode as default editor) for 3.3
- [ ] Improving the support for building container images (first iteration disabled by default)

### WTO
- [ ] [Web Terminal Operator leaking user token into Audit logs](https://issues.redhat.com/browse/WTO-151)
- [ ] [Publish source images for the web-terminal-tooling container](https://issues.redhat.com/browse/WTO-154)
- [ ] [Update tooling image to install binaries from internal sources](https://issues.redhat.com/browse/WTO-147)
- [ ] [Improve and simplify the Web Terminal Operator release process](https://issues.redhat.com/browse/WTO-150)
- [ ] [Simplify implementation for exec component](https://issues.redhat.com/browse/WTO-149)

### DWO
- [x] [airgap] "operator does not have permissions to get the 'container-build' SecurityContextConstraints" error when start Quarkus workspace using VS Code Editor https://issues.redhat.com/browse/CRW-3491
- [ ] [Improving the support for building container images](https://issues.redhat.com/browse/CRW-3366) ⭐
     #21770
     devfile/devworkspace-operator#884
- [x] [Insufficient CPU and insufficent memory errors are not caught at workspaces startup](https://issues.redhat.com/browse/CRW-3474) ⭐
- [ ] [Support "podman run" from within a workspace](https://issues.redhat.com/browse/CRW-3367) ⭐
- [ ] [Support Devfile v2 components of type Kubernetes](https://issues.redhat.com/browse/CRW-3364) ⭐
- [x] devfile/devworkspace-operator/issues/920
- [x] devfile/devworkspace-operator/issues/930

### Dashboard
- [x] Issues when a devfile is invalid and Che fails gracefully #21793
- [x] https://github.com/eclipse/che/issues/21799
   - [x] https://github.com/eclipse/che/issues/21532
   - [ ] Multiple error messages in Dashboard when auth session expired, before automatic redirection to OpenShift auth page https://issues.redhat.com/browse/CRW-3436
- [ ] [Begin using DevWorkspace Operator container contributions functionality](https://issues.redhat.com/browse/CRW-3356) ⭐
     - [x] https://github.com/eclipse/che/issues/21736  
     - [ ] Dashboard should put plugins in DevWorkspace .spec.contributions instead of as plugin components in .spec.templates #21737
- [ ] Rework (potentially remove) "Account" page on the User Dashboard. Add login / logout buttons for GitHub / GitLab / BitBucket #21595
- [ ] [Support specifying the schedulerName of workspace pods](https://issues.redhat.com/browse/CRW-3323) ⭐
  - [x] https://github.com/eclipse/che/issues/21803
  - [x] ~~Specify workspace pod schedulerName as an URL parameter~~ #21420
- [ ] [Automatic setup of git remotes when starting a workspace from GitHub](https://issues.redhat.com/browse/CRW-3482) ⭐
 

### Operator
  - [ ] [Switching OpenShift IdP causes user to lose access to their workspaces](https://issues.redhat.com/browse/CRW-3478) ⭐
  - [x] #21445
  - [x] #21774
  - [ ] [Allow to deploy DevSpaces from fast channel using dsc](https://issues.redhat.com/browse/CRW-3353)
  - [ ] [Workspace is not running' page appeared even when the workspace should be running](https://github.com/eclipse/che/issues/21796)

    
### chectl
 - [x] #21759
 - [x] #21802

### Che Server
- [x] https://github.com/eclipse/che/issues/21184 @vitaliy-guliy
- [x] https://github.com/eclipse/che/issues/21801

### Git zero config
- [ ]  [Git zero config (always use OAuth flow to auth with Git providers, git push should work out of the box )](https://github.com/eclipse/che/issues/20583):
  -  [Testing Git services](https://github.com/eclipse/che/issues/21753)

### Technical Debt
-  [x] [Tens of outdated configuration options in the documentation are confusing users](https://issues.redhat.com/browse/CRW-3355) ⭐
- [ ] [Decommissioning PostgreSQL database](https://github.com/eclipse/che/issues/21374)

### Editors
- [x] [Unplanned] #21826
- [x] [Unplanned] [theia build failing with "429 Too Many Requests" when downloading vscode-builtin plugins](https://issues.redhat.com/browse/CRW-3493)
- [x]  [Unplanned] #21813 [([CRW-3421](https://issues.redhat.com//browse/CRW-3421))](https://issues.redhat.com/browse/CRW-3421)
- [x] [Unplanned] #21787 [CRW-3475](https://issues.redhat.com/browse/CRW-3475), [CRW-3506](https://issues.redhat.com/browse/CRW-3506)
- [x] [Unplanned] [IntelliJ IDEA Welcome screen should not be displayed](https://issues.redhat.com/browse/CRW-3471)
- [x] [machine-exec component isn't running in IDEA-based DevWorkspace](https://issues.redhat.com/browse/CRW-3480)
- [x] #21701 [CRW-3483](https://issues.redhat.com/browse/CRW-3483)
- [ ] Add the Happy Path PR check for Che-Code repository https://github.com/eclipse/che/issues/21789
- [ ] [Handle idling in VS Code correctly instead of attempting to reconnect in x seconds](https://github.com/eclipse/che/issues/21610) 

### Plugins
- [x] [Create offline VS Code Marketplace (airgap support for vscode as default editor)](https://issues.redhat.com/browse/CRW-3295) ⭐
- [ ] Testing Git zero flow #21753
- [x] Che ignores my devfile.yaml and che-editor.yaml updates (because che-server URLFetcher sometimes caches its results) #21184
- [x] [Add vsix extensions that aren't published on openvsx.org into the local plugin registry](https://issues.redhat.com/browse/CRW-3477)
- [ ] [Document how to add/remove extensions from the open-vsx registry (including those not in open-vsx.org)](https://issues.redhat.com/browse/CRW-3472) ⭐
- [x] [airgap] [Can't install Python vsix extension in VS Code Editor](https://issues.redhat.com/browse/CRW-3490)
- [ ] [Support .NET LS and netcoredbg with VS Code and re-introduce the .NET sample](https://issues.redhat.com/browse/CRW-2456)
- [x] Factory creation from pull request clones wrong branch [CRW-3449](https://issues.redhat.com/browse/CRW-3449)
- [x] Update VSCode OpenShift Connector plugin to latest 0.7 (or newer) to support odo 3.0 [CRW-3344](https://issues.redhat.com/browse/CRW-3344)
- [x] [Unplanned] Add vsix extensions that aren't published on openvsx.org into the local plugin registry #21818

### Productization

Registry build/customize/doc:
- [ ] [CRW-2275](https://issues.redhat.com/browse/CRW-2275) Simplify registry customization process
- [ ] [CRW-3472](https://issues.redhat.com/browse/CRW-3472) Document how to add/remove extensions from the open-vsx registry (including those not in open-vsx.org)
- [ ] [CRW-2459](https://issues.redhat.com/browse/CRW-2459) Improve codeready-workspaces-images local build story

Build flow:
- [x] [CRW-3493](https://issues.redhat.com/browse/CRW-3493) theia build failing with "429 Too Many Requests" when downloading vscode-builtin plugins
- [x] [CRW-3451](https://issues.redhat.com/browse/CRW-3451) Fine-tune VSCode air-gap Marketplace (add more extensions)
- [x] [CRW-3344](https://issues.redhat.com/browse/CRW-3344) Update VSCode OpenShift Connector plugin to latest OpenShift Toolkit 1.0 to support odo 3.0
- [ ] [CRW-3429](https://issues.redhat.com/browse/CRW-3429) add traefik and project-clone to plugin registry's external_images.txt (for use with imagepuller)
- [x] [CRW-3330](https://issues.redhat.com/browse/CRW-3330) publish DWO 0.17 downstream images to quay, then include them in quay.io/devspaces/iib images

Che issues:
- [x] https://github.com/eclipse/che/issues/21795
- [x] https://github.com/eclipse/che/issues/21790
- [x] https://github.com/eclipse/che/issues/21575
- [x] https://github.com/eclipse/che/issues/21763

Prod sec / RH internal process issues:
- [ ] [CRW-3450](https://issues.redhat.com/browse/CRW-3450) Migrate release engineering tasks using obsolete rcm-guest.app.eng.bos.redhat.com to new host [due Nov 15?]
- [ ] [CRW-3080](https://issues.redhat.com/browse/CRW-3080) Make Container Images Eligible for Source Containers
  - [ ] [CRW-3138](https://issues.redhat.com/browse/CRW-3138) operator :: migrate to fetch-artifacts (or commit files directly?) for sources

**Comment by l0rd** [comment]
Here is the issue list

Already in progress issues (finishing those should the top priority):
- [Create offline VS Code Marketplace (airgap support for vscode as default editor)](https://issues.redhat.com/browse/CRW-3295) ⭐
- [Support specifyng the schedulerName of workspace pods](https://issues.redhat.com/browse/CRW-3323) ⭐
- [Tens of outdated configuration options in documentation are confusing users](https://issues.redhat.com/browse/CRW-3355) ⭐
- [Begin using DevWorkspace Operator container contributions functionality](https://issues.redhat.com/browse/CRW-3356) ⭐
- [Improving the support for building container images](https://issues.redhat.com/browse/CRW-3366) ⭐
- [Decommissioning PostgreSQL database](https://github.com/eclipse/che/issues/21374)
- [Support "podman run" from within a workspace](https://issues.redhat.com/browse/CRW-3367) ⭐
- [Support Devfile v2 components of type Kubernetes](https://issues.redhat.com/browse/CRW-3364) ⭐
- [Git zero config (always use OAuth flow to auth with Git providers, git push should work out of the box )](https://github.com/eclipse/che/issues/20583):
  -  [Testing Git services](https://github.com/eclipse/che/issues/21753)
- [Improve Devfile editing UX](https://github.com/eclipse/che/issues/21606)

New issues in priority order (we don't have take all of them but we should start with the ones in higher position):
- [Document how to add/remove extensions from the open-vsx registry (including those not in open-vsx.org)](https://issues.redhat.com/browse/CRW-3472) ⭐
- [Insufficient CPU and insufficent memory errors are not caught at workspaces startup](https://issues.redhat.com/browse/CRW-3474) ⭐
- [Dashboard IDE selection and devworkspace creation should not use the same displayName variable](https://github.com/eclipse/che/issues/21704)
- [Automatically install extensions at VS Code startup](https://issues.redhat.com/browse/CRW-3483) ⭐
- [Automatic setup of git remotes when starting a workspace from GitHub](https://issues.redhat.com/browse/CRW-3482) ⭐
- [Handle idling in VS Code correctly instead of attempting to reconnect in x seconds](https://github.com/eclipse/che/issues/21610) 
- [Support .NET LS and netcoredbg with VS Code and re-introduce the .NET sample ](https://issues.redhat.com/browse/CRW-2456)
- [Support for JetBrains Gateway - Remote Development environment](https://issues.redhat.com/browse/CRW-3086) ⭐
- [Idling support for JetBrains IDEs]
- [VS Code built-in extensions are outdated](https://issues.redhat.com/browse/CRW-3475) ⭐
- [Use a pre-created ServiceAccount for workspace Pods](https://issues.redhat.com/browse/CRW-3470) ⭐
- [Switching OpenShift IdP causes user to lose access to their workspaces](https://issues.redhat.com/browse/CRW-3478) ⭐

**Comment by nickboldt** [comment]
For prod team:

Build flow:
- [ ] [CRW-3429](https://issues.redhat.com/browse/CRW-3429) add traefik and project-clone to plugin registry's external_images.txt 
- [ ] [CRW-3492](https://issues.redhat.com/browse/CRW-3492) Jenkins webhook smee service not set up for che-incubator repos
- [ ] [CRW-3493](https://issues.redhat.com/browse/CRW-3493) theia build failing with "429 Too Many Requests" when downloading vscode-builtin plugins
- [ ] [CRW-3330](https://issues.redhat.com/browse/CRW-3330) publish latest DWO images to quay, then include them in quay.io/devspaces/iib images

Prod sec issues:
- [ ] [CRW-3080](https://issues.redhat.com/browse/CRW-3080) Make Container Images Eligible for Source Containers
  - [ ] [CRW-3138](https://issues.redhat.com/browse/CRW-3138) operator :: migrate to fetch-artifacts (or commit files directly?) for sources

Che issues:
- [ ] https://github.com/eclipse/che/issues/21795
- [ ] https://github.com/eclipse/che/issues/21763
- [ ] https://github.com/eclipse/che/issues/21790
- [ ] https://github.com/eclipse/che/issues/21575
