### ISSUE TITLE
Sprint 228

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21823]
This issue collects work items of the Eclipse Che Team for Sprint 228 (November 23 - December 13th).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (November 22nd)

The previous sprint https://github.com/eclipse/che/issues/21785

### Sprint goals
- [ ] Dev Spaces 3.3 release and rollout to Developer Sandbox
- [ ] Migrate WTO / DWO CPaaS to GitLab and update the downstream release docs

### Aditional Notes

- **Hack 'n' Hustle - December 2nd** 
    - JKube - https://github.com/marcnuri-demo/202210-eclipsecon @ibuziuk 
    - Kubedock (for 'podman run') - https://github.com/joyrex2001/kubedock @l0rd 
    - Kail (for getting container logs) - https://github.com/boz/kail
    - Customer Demos Recording (short ~5 mins videos):
       - STEP 3 and 4 from [devspaces-demo](https://github.com/redhat-developer/devspaces-demo) @dkwon17 

    - macos [homebrew](https://brew.sh/) package for dsc/chectl PoC
    -  Dev Spaces chrome extension PoC ([issue](https://github.com/eclipse/che/issues/11584))  @ibuziuk 
      -  https://chrome.google.com/webstore/detail/eclipse-che-cloud-ide-hos/fkkgabogjbijdhfbbmdllhoobpeenbjo/related?authuser=1
   -  kubectl extension for devworkspace operator PoC ([issue](https://github.com/devfile/devworkspace-operator/issues/603))
   - Test a tooling container for Che using [devenv](https://devenv.sh/) with [starship](https://starship.rs/) 
   - update the [Che Dogfooding Scoreboard](https://docs.google.com/spreadsheets/d/1kGvWuq8bJU5sQSfXX025K8ZCDeLXudfm6Mi-YXVJ6T4/edit#gid=1734494029)
   - [OpenShift console dynamic plugin](https://docs.openshift.com/container-platform/4.11/web_console/dynamic-plug-ins.html) to manage DWs PoC
   - VS Code extension to start remote dev environments in Che / Dev Spaces
- **Day of Learning - December 9th** 
    -  Psychological Safety 
    -  Compliance and Ethics Training

### WTO
- [ ] CPaaS WTO Midstream repositories migration to GitLab - https://issues.redhat.com/browse/WTO-155
- [ ] Update WTO Productization docs - https://github.com/redhat-developer/devtools-productization/tree/main/web-terminal-operator
- [ ] [Web Terminal Operator leaking user token into Audit logs](https://issues.redhat.com/browse/WTO-151)
- [x] [Publish source images for the web-terminal-tooling container](https://issues.redhat.com/browse/WTO-154)
- [x] [Update tooling image to install binaries from internal sources](https://issues.redhat.com/browse/WTO-147)
- [ ] [Improve and simplify the Web Terminal Operator release process](https://issues.redhat.com/browse/WTO-150)
- [ ] [Simplify implementation for exec component](https://issues.redhat.com/browse/WTO-149)

### DWO
- [ ] [CPaaS DWO Midstream repositories migration to GitLab](https://github.com/devfile/devworkspace-operator/issues/982)
- [ ] [Improving the support for building container images](https://issues.redhat.com/browse/CRW-3366) ⭐
     #21770
- [ ] [Support "podman run" from within a workspace](https://issues.redhat.com/browse/CRW-3367) ⭐
- [ ] [Support Devfile v2 components of type Kubernetes](https://issues.redhat.com/browse/CRW-3364) ⭐
- [x] https://github.com/eclipse/che/issues/21829
- [ ] [Support specifying the schedulerName of workspace pods](https://issues.redhat.com/browse/CRW-3323) ⭐
  - [x] https://github.com/eclipse/che/issues/21803
- [x] https://github.com/eclipse/che/issues/21807
- [x] devfile/devworkspace-operator/issues/920
- [x] devfile/devworkspace-operator/issues/930

### Dashboard
- [ ] [Workspace is not running' page appeared even when the workspace should be running](https://github.com/eclipse/che/issues/21796)
- [x] https://github.com/eclipse/che/issues/21799
- [x] https://github.com/eclipse/che/issues/21809
- [x] https://github.com/eclipse/che/issues/21664
- [ ]  #21595
- [ ] [Automatic setup of git remotes when starting a workspace from GitHub](https://issues.redhat.com/browse/CRW-3482) ⭐
- [x] https://github.com/eclipse/che/issues/21825
- [x] https://github.com/eclipse/che/issues/21736
   - [ ]  (dashboard) Add `controller.devfile.io/merge-contribution: true` attribute to devfile container to enable injecting editor automatically; use the new editors defintions; ~~remove library usage to inject this editor~~: https://github.com/eclipse/che/issues/21738
- [x] Added implementation of devfileSchema API (moved from Che-Server) - https://github.com/eclipse-che/che-dashboard/pull/671
 
### Operator
  - [x] Use a pre-created ServiceAccount for workspace Pods https://issues.redhat.com/browse/CRW-3470 ⭐
  - [x] #21445
  - [x] [Allow to deploy DevSpaces from fast channel using dsc](https://issues.redhat.com/browse/CRW-3353)
  - [ ] Allow configuring workspace start timeout via CheCluster spec https://github.com/eclipse/che/issues/21820
    
### chectl
 - [x] #21759
 - [x] https://github.com/eclipse/che/issues/21858

### Technical Debt
- [ ] [Decommissioning PostgreSQL database](https://github.com/eclipse/che/issues/21374)

### Editors
- [x] [Unplanned] #21854
- [x] [Unplanned] #21880
- [x] [Unplanned] Ensure Git LFS works with VSCode with Dev Spaces 3.3 release [CRW-3585](https://issues.redhat.com/browse/CRW-3585)
- [x] Fix CVE in `devspaces-idea-rhel8` container [CRW-3546](https://issues.redhat.com/browse/CRW-3546)
- [x] #21701 [CRW-3483](https://issues.redhat.com/browse/CRW-3483)
- [x] #21610
- [x] #21412 [CRW-3086](https://issues.redhat.com/browse/CRW-3086)

### Plugins
- [x] [Unplanned] Factory creation from private/public Bitbucket.org repository with OAuth setup fails on DS 3.3.0.RC-11-24 [CRW-3584](https://issues.redhat.com/browse/CRW-3584)
- [x] https://github.com/eclipse/che/issues/21736
   - [x] Add new editors definitions that use `controller.devfile.io/container-contribution: true` to injectable component in editor devfile definition: https://github.com/eclipse/che/issues/21739
   - [ ] (devfile-registry) Rework the devworkspace generation process https://github.com/eclipse/che/issues/21832
- [ ] Testing Git zero flow #21753
- [x] [Support .NET LS and netcoredbg with VS Code and re-introduce the .NET sample](https://issues.redhat.com/browse/CRW-2456)
- [ ] [Document how to add/remove extensions from the open-vsx registry (including those not in open-vsx.org)](https://issues.redhat.com/browse/CRW-3472)
- [ ] Rebase che-openvsx against the upstream [CRW-3544](https://issues.redhat.com/browse/CRW-3544)
- [ ] [plugin-registry] Use upstream openvsx image to get openvsx-server sources #21721
- [ ] VS Code Editor shows installing built-in extensions in the list of installed ones at first start of workspace page [CRW-3506](https://issues.redhat.com/browse/CRW-3506)

### Productization

UX / Customization / Doc:
- [ ] [CRW-3553](https://issues.redhat.com/browse/CRW-3553) improve imagepuller customization process
- [ ] [CRW-2275](https://issues.redhat.com/browse/CRW-2275) Simplify registry customization process
  - [ ] [CRW-3472](https://issues.redhat.com/browse/CRW-3472) Document how to add/remove extensions from the open-vsx registry (including those not in open-vsx.org)
  - [ ] [CRW-2459](https://issues.redhat.com/browse/CRW-2459) Improve codeready-workspaces-images local build story

Tech Debt:
- [x]  [CRW-3531](https://issues.redhat.com/browse/CRW-3531) Update to golang 1.18 / clean out obsolete & unused dockerfiles
- [ ] [CRW-3080](https://issues.redhat.com/browse/CRW-3080) Make Container Images Eligible for Source Containers (ongoing Epic)
  - [x] [CRW-3099](https://issues.redhat.com/browse/CRW-3099) Migrate che server build to PNC
  - [x] [CRW-3195](https://issues.redhat.com/browse/CRW-3195) udi: maven, gradle, e2fsprogs :: use fetch-artifacts

Che issues:
- [x] https://github.com/eclipse/che/issues/21795 (almost done, continued from prev sprint)
- [x] https://github.com/eclipse/che/issues/21575
- [x] https://github.com/eclipse/che/issues/21763

### Docs 
- [x] https://github.com/eclipse/che/issues/21808 
- [x] Add procedure explaining how to view Visual Studio logs in Viewing Che workspaces logs - https://issues.redhat.com/browse/RHDEVDOCS-4574
- [x] Visual Studio Code: Process monitoring plugin - https://issues.redhat.com/browse/RHDEVDOCS-4596
- [x] Use Visual Studio Code rather than Che-Theia in Importing untrusted TLS certificates to Che - https://issues.redhat.com/browse/RHDEVDOCS-4573

**Comment by AObuchow** [comment]
Potential Che-Operator issue: https://github.com/eclipse/che/issues/21820

**Comment by nickboldt** [comment]
Prod

UX / customization:
- [ ] [CRW-553](https://issues.redhat.com/browse/CRW-3553) improve imagepuller customization process
- [ ] [CRW-2275](https://issues.redhat.com/browse/CRW-2275) Simplify registry customization process
- [ ] [CRW-3472](https://issues.redhat.com/browse/CRW-3472) Document how to add/remove extensions from the open-vsx registry (including those not in open-vsx.org)
- [ ] [CRW-2459](https://issues.redhat.com/browse/CRW-2459) Improve codeready-workspaces-images local build story

Tech Debt
- [ ] [CRW-3080](https://issues.redhat.com/browse/CRW-3080) Make Container Images Eligible for Source Containers
  - [ ] [CRW-3099](Migrate che server build to PNC (or internal RH npmjs mirror?) for 3rd party maven dependencies)
  - [ ] [CRW-3196](devfile registry :: migrate to fetch-artifacts (or commit files directly?) for sources)

Che issues:
- [ ] https://github.com/eclipse/che/issues/21795 (almost done)
- [ ] https://github.com/eclipse/che/issues/21575
- [ ] https://github.com/eclipse/che/issues/21763

**Comment by AObuchow** [comment]
Hack 'n' Hustle idea: Devfile builder app

**Comment by l0rd** [comment]
HnH proposals:

1. macos [homebrew](https://brew.sh/) package for dsc/chectl PoC
2. Dev Spaces chrome extension PoC ([issue](https://github.com/eclipse/che/issues/11584))
3. kubectl extension for devworkspace operator PoC ([issue](https://github.com/devfile/devworkspace-operator/issues/603))
4. Test a tooling container for Che using [devenv](https://devenv.sh/) with [starship](https://starship.rs/) 
5. update the [Che Dogfooding Scoreboard](https://docs.google.com/spreadsheets/d/1kGvWuq8bJU5sQSfXX025K8ZCDeLXudfm6Mi-YXVJ6T4/edit#gid=1734494029)
6. [OpenShift console dynamic plugin](https://docs.openshift.com/container-platform/4.11/web_console/dynamic-plug-ins.html) to manage DWs PoC
7. VS Code extension to start remote dev environments in Che / Dev Spaces
