### ISSUE TITLE
Sprint 229

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21864]
This issue collects work items of the Eclipse Che Team for Sprint 229 (December 14th - January 10th).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (December 13th)

The previous sprint https://github.com/eclipse/che/issues/21823

### Sprint goals
- [x] DevSpaces 3.3 release
- [x] Developer Sandbox
    - [x] Upgrade to DevSpaces 3.3
    - [x] Onboard Dev Spaces on m3 cluster 
- [x] DWO 0.18.0 upstream release for DevSpaces 3.4. Blocked PRs
    - [x] https://github.com/eclipse-che/che-operator/pull/1576
    - [x] https://github.com/eclipse-che/che-operator/pull/1587
- [ ] Migrate WTO / DWO CPaaS to GitLab and update the downstream release docs

### WTO
- [x] CPaaS WTO Midstream repositories migration to GitLab - https://issues.redhat.com/browse/WTO-155
- [ ] Update WTO Productization docs - https://github.com/redhat-developer/devtools-productization/tree/main/web-terminal-operator
- [x] [Web Terminal Operator leaking user token into Audit logs](https://issues.redhat.com/browse/WTO-151)
- [x] [Publish source images for the web-terminal-tooling container](https://issues.redhat.com/browse/WTO-154)
- [x] [Update tooling image to install binaries from internal sources](https://issues.redhat.com/browse/WTO-147)
- [ ] [Improve and simplify the Web Terminal Operator release process](https://issues.redhat.com/browse/WTO-150)
- [x] [Simplify implementation for exec component](https://issues.redhat.com/browse/WTO-149)

### DWO
- [x] https://github.com/devfile/devworkspace-operator/issues/913
- [x] [CPaaS DWO Midstream repositories migration to GitLab](https://github.com/devfile/devworkspace-operator/issues/982)
- [x] https://github.com/devfile/devworkspace-operator/issues/993 
- [x]  [Improving the support for building container images](https://issues.redhat.com/browse/CRW-3366) ⭐
     #21770
- [ ] [Support "podman run" from within a workspace](https://issues.redhat.com/browse/CRW-3367) ⭐
- [ ] Projected Volumes support: related to [downstream GCP WIF support issue](https://issues.redhat.com/browse/CRW-3535)⭐
- [x] [Support Devfile v2 components of type Kubernetes](https://issues.redhat.com/browse/CRW-3364) ⭐
- [x] [Support specifying the schedulerName of workspace pods](https://issues.redhat.com/browse/CRW-3323) ⭐
  - [x] https://github.com/eclipse/che/issues/21803
- [x] devfile/devworkspace-operator/issues/920
- [x] devfile/devworkspace-operator/issues/930

### Dashboard
- [x] https://github.com/eclipse/che/issues/21866
- [ ] [Automatic setup of git remotes when starting a workspace from GitHub](https://issues.redhat.com/browse/CRW-3482) ⭐
- [x] https://github.com/eclipse/che/issues/21595
- [x] https://github.com/eclipse/che/issues/21825
- [x] https://github.com/eclipse/che/issues/21846
- [x] https://github.com/eclipse/che/issues/21845
- [x] https://github.com/eclipse/che/issues/21738
- [x] https://github.com/eclipse/che/issues/21873
- [x] https://github.com/eclipse/che/issues/21848

### Operator
- [ ]  [Make default value for endpoint security configurable in CheCluster CR](https://issues.redhat.com/browse/CRW-3579) 
- [x] Support `ephemeral` as CheCluster pvcStrategy https://github.com/eclipse/che/issues/21885
- [x] Allow configuring workspace start timeout via CheCluster spec https://github.com/eclipse/che/issues/21820
- [x] dsc tool leaves a few items behind after uninstalling https://issues.redhat.com/browse/CRW-3521
- [x] https://github.com/eclipse/che/issues/21445
- [x] https://github.com/eclipse/che/issues/21860
- [x] https://github.com/eclipse/che/issues/21876
- [x] https://github.com/eclipse/che/issues/21877
- [x] https://github.com/eclipse/che/issues/21869 https://issues.redhat.com/browse/CRW-3606
- [x] https://github.com/eclipse/che/issues/21882
- [x] https://github.com/eclipse/che/issues/21897
- [x] https://github.com/eclipse/che/issues/21836

### Che Server 
- [ ] [OAuth token isn't suitable for use with the github CLI from a terminal](https://issues.redhat.com/browse/CRW-3525) (Che server) ⭐
    
### chectl
- [x] https://github.com/eclipse/che/issues/21884
- [x] https://github.com/eclipse/che/issues/21923
- [x] https://github.com/eclipse/che/issues/21759

### Technical Debt
- [ ] [Decommissioning PostgreSQL database](https://github.com/eclipse/che/issues/21374)

### Developer Sandbox
- [x]  Dev Spaces onboarding on m3 - https://issues.redhat.com/browse/CRT-1628

### Editors
- [x] [Unplanned] #21888
- [x] [Unplanned] #21915
- [x] #21878
- [x] #21879
- [x] #21610
- [x] #21412 [CRW-3086](https://issues.redhat.com/browse/CRW-3086)
- [x] #21853 [CRW-3605](https://issues.redhat.com/browse/CRW-3605)
- [x] #21840 [CRW-3333](https://issues.redhat.com/browse/CRW-3333)

### Plugins
- [x] Set urlRewriteSupported to false in editors redirect endpoints [CRW-3600](https://issues.redhat.com/browse/CRW-3600)
- [x] Factory creation from Bitbucket/Gitlab cloud/server repository when OAuth setup and user refused fails on DS 3.3.0.RC-12-03 [CRW-3594](https://issues.redhat.com/browse/CRW-3594)
- [ ] [Document how to add/remove extensions from the open-vsx registry (including those not in open-vsx.org)](https://issues.redhat.com/browse/CRW-3472)
- [x] [plugin-registry] Use upstream openvsx image to get openvsx-server sources #21721
- [ ] Testing Git zero flow #21753
- [x] (devfile-registry) Rework the devworkspace generation process https://github.com/eclipse/che/issues/21832
- [ ] Editor devfiles should use controller.devfile.io/container-contribution: true attribute on injectable components [CRW-3612](https://issues.redhat.com/browse/CRW-3612)
- [ ] DevWorkspaces generated in che-devfile-registry build should use container contributions [CRW-3613](https://issues.redhat.com/browse/CRW-3613)
- [x] [Unplanned] DeleteOAuthToken API method doesn't work properly #21890

### Productization
Tech Debt:
- [ ] [CRW-3080](https://issues.redhat.com/browse/CRW-3080) Make Container Images Eligible for Source Containers (ongoing Epic)
  - [ ] [CRW-3160](https://issues.redhat.com/browse/CRW-3160) vscode :: migrate from pkgs.devel lookaside asset files to cachito w/ yarn [Nick]
  - [ ] [CRW-3196](https://issues.redhat.com/browse/CRW-3196)	devfile registry :: migrate to fetch-artifacts (or commit files directly?) for sources [Sam]
  - [ ] [CRW-3336](https://issues.redhat.com/browse/CRW-3336)	pluginregistry :: Use fetch-artifacts for plugin registry build assets 

Che issues:
- [x] Release Che 7.58
  - [x] https://github.com/eclipse/che/issues/21836
- [x] https://github.com/eclipse/che/issues/21575 [Sam]
- [x] https://github.com/eclipse/che/issues/21763 [Sam]

Other ideas:
- [x] [CRW-3578](https://issues.redhat.com/browse/CRW-3578) "NodeJS MongoDB" workspace recommendations have issues in VS Code Editor: vscode.typescript-language-features (not found in marketplace)
- [ ] [CRW-3581](https://issues.redhat.com/browse/CRW-3581) enable github to jira integration (openshift-ci)
- [ ] [CRW-3601](https://issues.redhat.com/browse/CRW-3601) in PR comments, switch from comments API to review-comments so we can update 'job started' to 'job done' messages

### Docs 
- [x] https://github.com/eclipse/che/issues/21808

**Comment by nickboldt** [comment]
Prod

Tech Debt:
- [ ] [CRW-3080](https://issues.redhat.com/browse/CRW-3080) Make Container Images Eligible for Source Containers (ongoing Epic)
  - [ ] https://issues.redhat.com/browse/CRW-2619 add new python pip deps (remove tarball)
  - [ ] https://issues.redhat.com/browse/CRW-3487 build php xdebug from sources (remove tarball)

Che issues:
- [ ] Release Che 7.58
- [ ] https://github.com/eclipse/che/issues/21575
- [ ] https://github.com/eclipse/che/issues/21763

**Comment by l0rd** [comment]
- [Implicitly set `merge-contribution:true` on first template component](https://github.com/devfile/devworkspace-operator/issues/993)
- [Inject Theia/JetBrains in the devfile tooling container (as for VS Code)](https://github.com/eclipse/che/issues/21878)
- [To start VS Code, use `post-start` rather than overriding the entrypoint](https://github.com/eclipse/che/issues/21879)
- [Make default value for endpoint security configurable in CheCluster CR](https://issues.redhat.com/browse/CRW-3579)
- Projected Volumes support: related to [downstream GCP WIF support issue](https://issues.redhat.com/browse/CRW-3535)
- Support ephemeral as CheCluster pvcStrategy
- remotes URL parameter

**Comment by nickboldt** [comment]
For next sprint, we should look at untriaged/unplanned/unowned issues in [https://issues.redhat.com/browse/CRW-3623?jql=project%20%3D%20CRW%20AND%20type%20not%[…]s%20EMPTY%20ORDER%20BY%20created%20DESC%2C%20priority%20DESC](https://issues.redhat.com/browse/CRW-3623?jql=project%20%3D%20CRW%20AND%20type%20not%20in%20(Task%2C%20%22QE%20Task%22%2C%20Epic)%20AND%20resolution%20is%20null%20AND%20fixVersion%20is%20EMPTY%20ORDER%20BY%20created%20DESC%2C%20priority%20DESC) and decide if any should be done for 3.4/3.5.
