### ISSUE TITLE
Sprint 230

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21925]
This issue collects work items of the Eclipse Che Team for Sprint 330 (January 11th - January 24th).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (January 10th)

The previous sprint https://github.com/eclipse/che/issues/21864

### Sprint goals
- [ ] Daily periodic tests for Developer Sandbox stg, m1, m2, m3 clusters

### Aditional Notes
-  **Hack 'n' Hustle - January 13th** 
   - Compliance and Ethics Training   
   - Chrome extension - https://github.com/eclipse/che/issues/11584 @ibuziuk
   - JKube - https://github.com/marcnuri-demo/202210-eclipsecon @ibuziuk
   - Short OpenShift Dev Spaces demo about creating PVC shared across multiple DWs @dkwon17 
      - [Related docs](https://www.eclipse.org/che/docs/stable/end-user-guide/requesting-persistent-storage-for-workspaces/#requesting-persistent-storage-in-a-pvc)
      - Demo: Share m2 repository across multiple workspaces

### WTO
- [Improve and simplify the Web Terminal Operator release process](https://issues.redhat.com/browse/WTO-150) / Update WTO Productization docs 
- Update tooling versions once new versions of oc, kubectl are available for 4.12
- [Support for persistent storage per user](https://issues.redhat.com/projects/WTO/issues/WTO-156)

### DWO
- [Support "podman run" from within a workspace](https://issues.redhat.com/browse/CRW-3367) ⭐
- [ ] Projected Volumes support: related to [downstream GCP WIF support issue](https://issues.redhat.com/browse/CRW-3535)⭐ TODO: setup a follow up call @l0rd 
- https://github.com/devfile/devworkspace-operator/issues/995
- https://github.com/devfile/devworkspace-operator/issues/947
- https://github.com/devfile/devworkspace-operator/issues/922
- https://github.com/devfile/devworkspace-operator/issues/914

### Dashboard
- [x] https://github.com/eclipse/che/issues/21846 
- [x] https://github.com/eclipse/che/issues/21866 ⭐ **(should be backported in 7.58.x / 3.4)**
- [x] [Automatic setup of git remotes when starting a workspace from GitHub](https://issues.redhat.com/browse/CRW-3482) ⭐
   - [x] https://github.com/eclipse/che/issues/21922
   - [x] https://github.com/eclipse/che/issues/21921
   - [x] https://github.com/redhat-actions/try-in-web-ide/issues/14
- [x] https://github.com/eclipse/che/issues/21595
- [x] https://github.com/eclipse/che/issues/21825
- [x] https://github.com/eclipse/che/issues/21738
- [x] https://github.com/eclipse/che/issues/21873
- [x] https://github.com/eclipse/che/issues/21848
- [x] https://github.com/eclipse/che/issues/21655
- [x] https://github.com/eclipse/che/issues/21894

### Che Operator
- [x] https://github.com/eclipse/che/issues/21927
- [ ] [Make default value for endpoint security configurable in CheCluster CR](https://issues.redhat.com/browse/CRW-3579)
- [x] [Issue installing Red Hat OpenShift Dev Spaces Operator (3.1.0) FIPS mode](https://issues.redhat.com/browse/CRW-3301)
- [x] https://github.com/eclipse/che/issues/21860
- [x] https://github.com/eclipse/che/issues/21877
- [x] https://github.com/eclipse/che/issues/21900

### chectl
-  [x] https://github.com/eclipse/che/issues/21759

### Che Server 
- [x] [OAuth token isn't suitable for use with the github CLI from a terminal](https://issues.redhat.com/browse/CRW-3525) (Che server) ⭐

### Technical Debt
- [ ] [Decommissioning PostgreSQL database](https://github.com/eclipse/che/issues/21374)
    - [x] https://github.com/eclipse-che/che-server/pull/398

### Developer Sandbox
- Daily periodic tests for Developer Sandbox stg, m1, m2, m3 clusters @ScrewTSW

### Image Puller
- [x] https://github.com/eclipse/che/issues/21899

### Editors
- [ ] Help the Prod. Team with the Cachito-based build of VS Code [CRW-3160](https://issues.redhat.com/browse/CRW-3160)
- [x] #21610
- [x] #21412 [CRW-3086](https://issues.redhat.com/browse/CRW-3086)
- [x] #21878
- [x] #21879
- [x] #21853 [CRW-3605](https://issues.redhat.com/browse/CRW-3605)
- [x] #21840 [CRW-3333](https://issues.redhat.com/browse/CRW-3333)

### Plugins
- [x] Unsupported OAuth provider github error when starting a workspace without OAuth setup #21896
- [x] [Factory creation from public gitlab server repo without OAuth fails on DS 3.2.0.RC-09-30](https://issues.redhat.com/browse/CRW-3408)
- [ ] Add scripts to prepare test GitHub Enterprise Server on AWS #21875
- [x] [Rebase che-openvsx against the upstream](https://issues.redhat.com/browse/CRW-3544)
- [x] [VS Code Editor shows installing built-in extensions in the list of installed ones at first start of workspace page](https://issues.redhat.com/browse/CRW-3506)
- [x] Editor devfiles should use controller.devfile.io/container-contribution: true attribute on injectable components [CRW-3612](https://issues.redhat.com/browse/CRW-3612) 
- [x] DevWorkspaces generated in che-devfile-registry build should use container contributions [CRW-3613](https://issues.redhat.com/browse/CRW-3613)
- [ ] [Remove lombok.jar from UDI](https://issues.redhat.com/browse/CRW-3602)
- [x] [Unplanned] Fix Plugin Registry - PR check - Publish Registry Content GH action [CRW-3395](https://issues.redhat.com/browse/CRW-3395)

### Productization
- Security:
- [ ] assist with CVE fixes (where possible) and decide which can be done in 3.5, 3.6, future, or nothing to do (rpm issues we don't control). See also https://github.com/redhat-developer/devspaces/blob/devspaces-3-rhel-8/product/manifest/3.3.0/manifest-all.txt
  - [ ] 10 for [dashboard](https://issues.redhat.com/browse/CRW-3798?filter=12405213&jql=project%20%3D%20CRW%20AND%20component%20%3D%20%22productization%3A%20security%20%26%20legal%22%20AND%20labels%20%3D%20SecurityTracking%20AND%20resolution%20is%20EMPTY%20and%20fixversion%20is%20null%20and%20summary%20~%20%20devspaces-dashboard-rhel8-container) 
  - [ ] 3 for [code](https://issues.redhat.com/browse/CRW-3774?filter=12405213&jql=project%20%3D%20CRW%20AND%20component%20%3D%20%22productization%3A%20security%20%26%20legal%22%20AND%20labels%20%3D%20SecurityTracking%20AND%20resolution%20is%20EMPTY%20and%20fixversion%20is%20null%20and%20summary%20~%20%20devspaces-code-rhel8-container)
  - [ ] 2 for [operator](https://issues.redhat.com/browse/CRW-3801?filter=12405213&jql=project%20%3D%20CRW%20AND%20component%20%3D%20%22productization%3A%20security%20%26%20legal%22%20AND%20labels%20%3D%20SecurityTracking%20AND%20resolution%20is%20EMPTY%20and%20fixversion%20is%20null%20and%20summary%20~%20%20devspaces-rhel8-operator-container)
  - [ ] 1 for [machine-exec](https://issues.redhat.com/browse/CRW-3765?filter=12405213&jql=project%20%3D%20CRW%20AND%20component%20%3D%20%22productization%3A%20security%20%26%20legal%22%20AND%20labels%20%3D%20SecurityTracking%20AND%20resolution%20is%20EMPTY%20and%20fixversion%20is%20null%20and%20summary%20~%20%20devspaces-machineexec-rhel8-container)
  - [ ] 1 for [traefik](https://issues.redhat.com/browse/CRW-3784?filter=12405213&jql=project%20%3D%20CRW%20AND%20component%20%3D%20%22productization%3A%20security%20%26%20legal%22%20AND%20labels%20%3D%20SecurityTracking%20AND%20resolution%20is%20EMPTY%20and%20fixversion%20is%20null%20and%20summary%20!~%20%20devspaces-dashboard-rhel8-container) 

Tech Debt:
- [ ] [CRW-3080](https://issues.redhat.com/browse/CRW-3080) Make Container Images Eligible for Source Containers (ongoing Epic)
  - [ ] [CRW-3160](https://issues.redhat.com/browse/CRW-3160) vscode :: migrate from pkgs.devel lookaside asset files to cachito w/ yarn [Nick] ... in progress
  - [ ] [CRW-3336](https://issues.redhat.com/browse/CRW-3336)	plugin registry :: Use fetch-artifacts for plugin registry build assets  [Sam] ... in progress
  - [ ] [CRW-3196](https://issues.redhat.com/browse/CRW-3196)	devfile registry :: migrate to fetch-artifacts (or commit files directly?) for sources

Che issues:
- [ ] [CRW-3606](https://issues.redhat.com/browse/CRW-3606) Update to Traefik 2.9.6
- [ ] https://github.com/eclipse/che/issues/21763 [Sam] ... in progress (waiting for PR reviews & merges by code owners)
- [ ] Release Che 7.60
  - [x] get Sam elected committer so she can do the release

### Docs 
- [x] https://github.com/eclipse/che/issues/21808
    - [ ] https://github.com/eclipse-che/che-docs/pull/2510 (pending @max-cx review) 
- [x] https://github.com/eclipse/che/issues/21805
- [x] [Document how to add/remove extensions from the open-vsx registry (including those not in open-vsx.org)](https://issues.redhat.com/browse/CRW-3472)

**Comment by nickboldt** [comment]
Prod

Tech Debt:
- [ ] [CRW-3080](https://issues.redhat.com/browse/CRW-3080) Make Container Images Eligible for Source Containers (ongoing Epic)
  - [ ] [CRW-3160](https://issues.redhat.com/browse/CRW-3160) vscode :: migrate from pkgs.devel lookaside asset files to cachito w/ yarn [Nick] ... in progress
  - [ ] [CRW-3336](https://issues.redhat.com/browse/CRW-3336)	plugin registry :: Use fetch-artifacts for plugin registry build assets  [Sam] ... in progress
  - [ ] [CRW-3196](https://issues.redhat.com/browse/CRW-3196)	devfile registry :: migrate to fetch-artifacts (or commit files directly?) for sources

Che issues:
- [ ] Release Che 7.60
  - [ ] get Sam elected committer so she can do the release
- [ ] https://github.com/eclipse/che/issues/21763 [Sam] ... in progress (waiting for PR reviews & merges by code owners)
- [ ] https://github.com/eclipse/che/issues/21924 

Other ideas:
- [ ] [CRW-3581](https://issues.redhat.com/browse/CRW-3581) enable github to jira integration (openshift-ci)
- [ ] [CRW-3601](https://issues.redhat.com/browse/CRW-3601) in PR comments, switch from comments API to review-comments so we can update 'job started' to 'job done' messages
- [ ] re-enable [jiralint](https://github.com/redhat-developer/devspaces-jiralint) and [improve workflow](https://docs.google.com/document/d/12Z4ukeFzdfAjmzGtD7_2d0pjtby4zp-9q_b-6mnwTW0/edit) for ghira

**Comment by nickboldt** [comment]
Continued in:
* https://github.com/eclipse/che/issues/21942
* https://github.com/eclipse/che/issues/21941
