### ISSUE TITLE
Sprint 231 (Team A)

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21941]
This issue collects work items of the Eclipse Che Team for Sprint 231 (January 25th - February 14th) (three weeks).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (January 25th)

### Sprint goals

- [x] Release Che 7.60 **(January 25th)**
- [x] Release Dev Spaces 3.4, and promote it to Developer Sandbox workspaces.openshift.com **(February 6th - February 9th)**
- [ ] Daily periodic tests for Developer Sandbox stg, m1, m2, m3 clusters 
    - [ ] https://issues.redhat.com/browse/CRW-3886 
- [ ] Improve git services OAuth flow
- [x] Pre-release testing of Dev Spaces 3.4.0.GA
- [ ] Dev Spaces factory E2E acceptance tests automation
- [ ] Happy path E2E GUI acceptance tests automation

### Aditional Notes
-  **Compliance and Ethics Training**  until January 31
-  **Hack 'n' Hustle** - February 3rd 
   - [x] [CRW-3877](https://issues.redhat.com/browse/CRW-3877) Allow to deploy DevSpaces from the `latest` IIB, `fast` channel using dsc -- possible H&H to learn a bit about typescript?
   - [ ] JKube - https://github.com/marcnuri-demo/202210-eclipsecon @ibuziuk
   - [ ] Library upgrade follow up for che-dashboard
   - [ ] Short OpenShift Dev Spaces demo about creating PVC shared across multiple DWs @dkwon17 
      - [Related docs](https://www.eclipse.org/che/docs/stable/end-user-guide/requesting-persistent-storage-for-workspaces/#requesting-persistent-storage-in-a-pvc)
      - Demo: Share m2 repository across multiple workspaces
   
### https://github.com/eclipse/che/labels/area%2Fgit%2Foauth-services
- [x] https://github.com/eclipse/che/issues/21951
- [x] [Workspace creation failed from bitbucket-server public repo factory without PAT and OAuth on DS 3.4.0.RC-01-11
](https://issues.redhat.com/browse/CRW-3867)
- [x] https://github.com/eclipse/che/issues/21949
- [x] Factory creation from private gitlab server repo with OAuth fails on DS 3.3.0 [CRW-3884](https://issues.redhat.com/browse/CRW-3884)
- [ ] Bitbucket.org private repo factory test scenario with refused OAuth fails to create workspace [CRW-3878](https://issues.redhat.com/browse/CRW-3878)
- [ ] [BitBucket] che-editor.yaml overrides don't work [CRW-3369](https://issues.redhat.com/browse/CRW-3369)
- [ ] 404 page not found" error when open workspace from BitBucket server public repo factory URL [CRW-3864](https://issues.redhat.com/browse/CRW-3864)

### https://github.com/eclipse/che/labels/area%2Fdashboard
- [x] https://github.com/eclipse/che/issues/21738
- [x] https://github.com/eclipse/che/issues/21825
- [x] https://github.com/eclipse/che/issues/21563
- [x] There is incorrect link to devfile documentation at "Dashboard > Workspace" page [CRW-3881](https://issues.redhat.com/browse/CRW-3881) 
- [x] https://github.com/eclipse/che/issues/21873
- [x] https://github.com/eclipse/che/issues/21950
- [x] https://github.com/eclipse/che/issues/21848
- [x] https://github.com/eclipse/che/issues/21655
- [x] https://github.com/eclipse/che/issues/21894
- [x] https://github.com/eclipse/che/issues/21939
- [x] https://github.com/eclipse/che/issues/21943 
- [x] Certificate Error message uses 'here' as link text [CRW-3024](https://issues.redhat.com/browse/CRW-3024)

###  https://github.com/eclipse/che/labels/area%2Fche-operator
- [ ] Make default value for endpoint security configurable in CheCluster CR [CRW-3579](https://issues.redhat.com/browse/CRW-3579)
- [x] https://github.com/eclipse/che/issues/21819
- [ ] https://github.com/eclipse/che/issues/21883
- [x] https://github.com/eclipse/che/issues/21986

### https://github.com/eclipse/che/labels/area%2Fchectl
- [x] https://github.com/eclipse/che/issues/21759
- [x] [Allow to deploy DevSpaces from the `latest` channel using dsc](https://issues.redhat.com/browse/CRW-3877)
- [x] https://github.com/eclipse/che/issues/21945
- [x] https://github.com/eclipse/che/issues/21980

### https://github.com/eclipse/che/labels/kind%2Ftechnical-debt
- [x] [Decommissioning PostgreSQL database](https://github.com/eclipse/che/issues/21374)

### https://github.com/eclipse/che/labels/area%2Fche-server
- [x] https://github.com/eclipse/che/issues/7662

 ### https://github.com/eclipse/che/labels/area%2Fplugin-registry
- [x] #21719
- [x] Change version of che-code editor from insiders to latest in che-editors.yaml [CRW-3568](https://issues.redhat.com/browse/CRW-3568)

### https://github.com/eclipse/che/labels/area%2Fdevfile-registry
- [x] #21926
- [x] Project isn't cloned into the workspace started form the samples [CRW-3941](https://issues.redhat.com/browse/CRW-3941)

### https://github.com/eclipse/che/labels/area%2Fsamples 
- [x] Using breakpoint for Node.js stacks with Vs Code editor is unclear [CRW-3435](https://issues.redhat.com/browse/CRW-3435)

### https://github.com/eclipse/che/labels/area%2Fimage-puller
- N / A

### https://github.com/eclipse/che/labels/area%2Fwebsite
- [x] Eclipse Che website CI is broken and website is not updated - https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2521
- [x] Eclipse Che website pipline is broken due to missing ECA for che-bot - account https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2614

### https://github.com/eclipse/che/labels/area%2Fhosted-che
- [x] Developer Sandbox workspaces.openshift.com Dev Spaces 3.4 update
- [x] [CRW-3886: Configure m2, m3, stg cluster access tokens, update periodic reports logic](https://issues.redhat.com/browse/CRW-3886)

### Browser Extension
- [x] https://github.com/eclipse/che/issues/11584

### Try in Web IDE GitHub action
- [x] https://github.com/redhat-actions/try-in-web-ide/issues/13

### https://github.com/eclipse/che/labels/area%2Fqe + https://github.com/eclipse/che/labels/e2e-test%2Ffailure + [![image](https://user-images.githubusercontent.com/227597/214135832-6150cbf2-7b33-4cfe-96a7-6cc3c940a1c6.png)](https://issues.redhat.com/issues/?filter=12405916)

- [x] [CRW-3641: Pre-release testing of Dev Spaces 3.4.0.GA](https://issues.redhat.com/browse/CRW-3641)
- [x] [CRW-3670: Run test case 'VS Code Editor Happy path E2E GUI test' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3670)
- [x] [CRW-3682: Run test case 'Test cascaded user removal' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3682)
- [x] [CRW-3684: Run test case 'Import from a Git repository to create workspace using 'Create Workspace' dashboard page' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3684)
- [x] [CRW-3685: Run test case 'Git operations in workspace Terminal' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3685)
- [x] [CRW-3758: Run test case 'Install DS on OSD 4.10'](https://issues.redhat.com/browse/CRW-3758)
- [x] [CRW-3672: Run test case 'Java Lombok devfile API test' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3672)
- [x] [CRW-3693: Run test case 'BitBucket server: private repo factory with accepted OAuth' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3693)
- [x] [CRW-3694: Run test case 'BitBucket server: private repo factory with PAT' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3694)
- [x] [CRW-3710: Run test case 'GitLab server: private repo factory with PAT' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3710)
- [x] [CRW-3753: Run test case 'Update 3.3 to 3.4 on x86_64 OCP 4.12 including all samples'](https://issues.redhat.com/browse/CRW-3753)
- [x] [CRW-3756: Run test case 'Install DS on x86_64 OCP 4.12 and run workspace using stage images'](https://issues.redhat.com/browse/CRW-3756)
- [CRW-3761: Run test case 'Custom Che Plugin registry'](https://issues.redhat.com/browse/CRW-3761) - moved to **Team B**
- [x] [CRW-3680: Run test case 'Test VS Code Editor recommended extensions in GUI' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3680)
- [x] [CRW-3695: Run test case 'BitBucket server: private repo factory with refused OAuth' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3695)
- [x] [CRW-3782: Run test case 'GitLab.com: public repo factory with PAT' on x86_64 OCP 4.10, OCP 4.12](https://issues.redhat.com/browse/CRW-3722)
- [x] [CRW-3724: Run test case 'GitLab.com: public repo factory with no OAuth or PAT' on x86_64 OCP 4.10, OCP 4.12](https://issues.redhat.com/browse/CRW-3724)
- [x] [CRW-3764: Run test case 'Image puller verification'](https://issues.redhat.com/browse/CRW-3764)
- [x] [CRW-3674: Run test case 'Python devfile API test' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3674)
- [x] [CRW-3668: Run test case '.NET sample E2E GUI test' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3668)
- [x] [CRW-3676: Run test case 'C/C++ devfile API test' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3676)
- [x] [CRW-3697: Run test case 'BitBucket server: public repo factory with accepted OAuth' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3697)
- [x] [CRW-3698: Run test case 'BitBucket server: public repo factory with PAT' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3698)
- [x] [CRW-3699: Run test case 'BitBucket server: public repo factory with refused OAuth' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3699)
- [x] [CRW-3702: Run test case 'BitBucket.org: private repo factory with PAT' on x86_64 OCP 4.10, OCP 4.12](https://issues.redhat.com/browse/CRW-3702)
- [x] [CRW-3706: Run test case 'BitBucket.org: public repo factory with PAT' on x86_64 OCP 4.10, OCP 4.12](https://issues.redhat.com/browse/CRW-3706)
- [x] [CRW-3714: Run test case 'GitLab server: public repo factory with PAT' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3714)
- [x] [CRW-3718: Run test case 'GitLab.com: private repo factory with PAT' on x86_64 OCP 4.10, OCP 4.12](https://issues.redhat.com/browse/CRW-3718)
- [x] [CRW-3720: Run test case 'GitLab.com: private repo factory with no OAuth or PAT' on x86_64 OCP 4.10, OCP 4.12](https://issues.redhat.com/browse/CRW-3720)
- [x] [CRW-3677: Run test case 'Go devfile API test' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3677)
- [x] [CRW-3836: Handle AWS Vulnerability Report regarding version of bitbucket server](https://issues.redhat.com/browse/CRW-3836)
- [ ] [CRW-3654: Fix nexus maven configuration for airgap Quarkus and Lombok samples opened using Che Code editor](https://issues.redhat.com/browse/CRW-3654)
- [x] https://github.com/eclipse/che/issues/21940
- [x] [CRW-3664: Create complex factory URL test pipeline which verifies OAuth, PAT, refused oAuth and no config setup test cases using certain Git Provider](https://issues.redhat.com/browse/CRW-3664)
- [ ] [CRW-3140: Update CRW interop tests to be run using DevSpaces 3.x](https://issues.redhat.com/browse/CRW-3140)
- [ ] [CRW-3500: Automate Che Code Editor Happy path E2E GUI test](https://issues.redhat.com/browse/CRW-3500)
- [ ] [CRW-3304: Stabilize test workspace removal in e2e typescript tests](https://issues.redhat.com/browse/CRW-3304)
- [ ] [CRW-3112: Print error message in output of test workspace deletion in case of failure](https://issues.redhat.com/browse/CRW-3112)
- [x] https://github.com/eclipse/che/issues/21965
- [x] [CRW-3905: Use Kerberos SSO Authentication on CRW Jenkins](https://issues.redhat.com/browse/CRW-3905)
- [x] [CRW-3929: Switch testing pipelines to DS 3.5.0](https://issues.redhat.com/browse/CRW-3929)
- [x] [CRW-3945: devfile API test failed on workspace creation step because of new path to devworkspace-che-code yaml](https://issues.redhat.com/browse/CRW-3945)

### https://github.com/eclipse/che/labels/kind%2Frelease + https://github.com/eclipse/che/labels/area%2Fci + [![image](https://user-images.githubusercontent.com/227597/214135832-6150cbf2-7b33-4cfe-96a7-6cc3c940a1c6.png)](https://issues.redhat.com/browse/CRW-3868?filter=-1&jql=project%20in%20(CRW)%20and%20component%20in%20(%22productization%3A%20build%20%26%20internals%22%2C%20%22productization%3A%20security%20%26%20legal%22)%20and%20resolution%20%3D%20Unresolved)

- [x] Release Che 7.60
- [x] Release Dev Spaces 3.4.0.GA
- [x] [CRW-3765](https://issues.redhat.com/browse/CRW-3765) update machine-exec dependencies for https://github.com/advisories/GHSA-6vm3-jj99-7229
- [x] [CRW-3882](https://issues.redhat.com/browse/CRW-3882) enable jiralint for CRW JIRA
- [ ] [CRW-3868](https://issues.redhat.com/browse/CRW-3868) support building OSBS scratch builds from midstream PRs
- [ ] [CRW-3160](https://issues.redhat.com/browse/CRW-3160) migrate code-rhel8 build to use cachito w/ yarn
- [x] [CRW-3877](https://issues.redhat.com/browse/CRW-3877) Allow to deploy DevSpaces from the `latest` IIB, `fast` channel using dsc -- possible H&H to learn a bit about typescript?

Prod Backlog A:
- [ ] [CRW-3601](https://issues.redhat.com/browse/CRW-3601) in PR comments, switch from comments API to review-comments so we can update 'job started' to 'job done' messages
- [ ] Triage / resolve [CVE issues](https://issues.redhat.com/browse/CRW-3869?jql=project%20%3D%20CRW%20AND%20type%20not%20in%20(Epic%2C%20%22QE%20Task%22)%20AND%20labels%20%3D%20SecurityTracking%20AND%20priority%20%3E%3D%20Minor%20AND%20resolution%20is%20EMPTY%20and%20fixversion%20is%20empty%20ORDER%20BY%20updated%20DESC)

### https://github.com/eclipse/che/labels/area%2Fdoc
- [x] https://github.com/eclipse-che/che-docs/pull/2531 (pending @max-cx review) 
- [x] https://github.com/eclipse/che/issues/21808
    - [x] https://github.com/eclipse-che/che-docs/pull/2510 (pending @max-cx review) 
- [x] https://github.com/eclipse/che/issues/21805

**Comment by nickboldt** [comment]
Future prod issues (3.5 or 3.6 - depends on approval from Kasturi or Rick):

 [CRW-3489](https://issues.redhat.com/browse/CRW-3489) Drop theia from list of available editors in dashboard
 [CRW-3662](https://issues.redhat.com/browse/CRW-3662) Enable theia IDE removal warning in dashboard
 [CRW-3514](https://issues.redhat.com/browse/CRW-3514) Remove CRW 2.15 jobs from Jenkins

**Comment by nickboldt** [comment]
Possible issues for this/next sprint:
* [CRW-3865](https://issues.redhat.com/browse/CRW-3865) include sdkman in downstream UDI container?
* [CRW-3072](https://issues.redhat.com/browse/CRW-3072) Include jbang binary in Universal Developer image

**Comment by l0rd** [comment]
I have opened [this issue](https://github.com/eclipse/che/issues/21951) on the git services support related to one of customers top requests ([spreadsheet](https://docs.google.com/spreadsheets/d/1nctM2r56rvXezVLUZ75HSz24IazHNxnQZtVh3FvU6n8/edit#gid=1012016449)).

**Comment by ibuziuk** [comment]
thanks, @l0rd I added the dedicated label for oauth services in the planning + one of the goals for the current sprint is the improvement of the git services OAuth flow since we already have quite a few bugs for this area

**Comment by pmkovar** [comment]
For docs, refer to this scrum board: https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=3516&projectKey=RHDEVDOCS&quickFilter=25878

**Comment by ibuziuk** [comment]
@pmkovar could you please, provide the scrum board for the next sprint to https://github.com/eclipse/che/issues/21991?
