### ISSUE TITLE
Sprint 233 (Team A)

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22027]
This issue collects work items of the Eclipse Che Team for Sprint 233 (March 8th - March 22nd) (two weeks).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (March 8th)

Previous Sprint - https://github.com/eclipse/che/issues/21991

### Sprint goals
- [x] Dev Spaces 3.5.0 release
- [ ] Publish the first version of the "Try in Dev Spaces" Browser extension to marketplaces 

| Team Availability Ratio  |     0.5      |
|----------|:-------------:|
| Story Points Planned | 131 |
| Velocity | 53 |
  
### Aditional Notes
-  **[Dev Tools Week](https://source.redhat.com/groups/public/day-of-learning/learning_suggestions)** - March 13 - 17th 
    - [Jenkins-to-slack build notifications](https://issues.redhat.com/browse/CRW-841) (like we have in MM for Che builds) @dmytro-ndp
    - Devfile Registry Operator https://github.com/devfile/registry-operator as a replaccement of https://github.com/eclipse-che/che-devfile-registry 
    - Try out the existing Developer Sanbox Activities - https://developers.redhat.com/developer-sandbox/activities @dkwon17 @ibuziuk  
    - Contribute Dev Spaces-related activity to https://developers.redhat.com/developer-sandbox/activities @ibuziuk @dkwon17 

    - Enable CI builds for che-incubator/configbump, including updated secrets #21988 @dmytro-ndp 
    - Blogs
        -  Decommissioning PostgreSQL database (Che blog) @ibuziuk 
        - Try in Dev Spaces Browser Extension (Red Hat Developer) @dkwon17 
    - Learning Courses: @tolusha @vinokurig @olexii4 @akurinnoy @nickboldt 
        - Kubernetes Documentary - https://www.linkedin.com/learning/kubernetes-the-documentary 
        - https://role.rhu.redhat.com
        - https://www.linkedin.com/learning/onboarding/start/content-recommendations?careerIntentTrackingId=oUHDGZTHRJS8%2FPcWmMzyRQ%3D%3D&u=2056732
        - https://source.redhat.com/groups/public/day-of-learning/learning_suggestions
        - https://docs.google.com/document/d/1RvpXULVz67yhsDaBhp-t2-xf33ZzraPx7X4Kf5LdPx4/edit#heading=h.sjfsy7ljote4
    - Experiment with developing Knative project in Che @dkwon17 
    - Publish embedded VSCode extensions at build time [CRW-4054](https://issues.redhat.com/browse/CRW-4054) @svor 
    - Investigate Backstage and Janus-IDP @nickboldt 
    - StoneSoup Hackathon @nickboldt (Mar 9, not technically during DTW)

### https://github.com/eclipse/che/labels/area%2Fgit%2Foauth-services
- [ ] Support reading devfiles from private repos other than GitHub/GitLab/Bitbucket #21951
   - [ ] https://github.com/eclipse/che/issues/22025 **5 sp**
   - [x] The workspace should start even if che-server fails to resolve the devfile https://github.com/eclipse/che/issues/21997 **5 sp**
- [ ] BitBucket
   - [x] [che-editor.yaml overrides don't work](https://issues.redhat.com/browse/CRW-3369)⭐ **5 sp**
   - [ ] 404 page not found" error when open workspace from BitBucket server public repo factory URL [CRW-3864](https://issues.redhat.com/browse/CRW-3864)  **5 sp**
   - [x]  [The start workspace failed on DS 3.5.0 when launch factory from Bitbucket.org repository](https://issues.redhat.com/browse/CRW-4095) **1 sp**
- [ ] Improving git configuration with PAT documentation https://github.com/eclipse/che/issues/21989 **5 sp**
- [x] [Workspace restart does not refresh expired GitLab OAuth token](https://issues.redhat.com/browse/CRW-3928) ⭐ **1 sp**
- [x] [Incorrect user name/email in commit message after user went through Git server OAuth flow in DS 3.4.0.RC-01-11](https://issues.redhat.com/browse/CRW-3859) **1 sp**

### https://github.com/eclipse/che/labels/area%2Fdashboard
- [ ] https://github.com/eclipse/che/issues/21827 **13 sp**
- [ ] https://github.com/eclipse/che/issues/21990 **3 sp**
- [ ] https://github.com/eclipse/che/issues/22039 **2 sp** 
- [x] https://github.com/eclipse/che/issues/22041 **1 sp** 

###  https://github.com/eclipse/che/labels/area%2Fche-operator
- [x]  #22032 **1 sp**
- [x] https://github.com/eclipse/che/issues/21970 **1 sp**
- [x]  #22026 **2 sp**
- [x] https://github.com/eclipse/che/issues/22051 **3 sp**
- [x] https://github.com/eclipse/che/issues/22022 **3 sp**

### https://github.com/eclipse/che/labels/area%2Fchectl
- [x] https://github.com/eclipse/che/issues/22058 **3 sp**

### https://github.com/eclipse/che/labels/kind%2Ftechnical-debt
- N / A

### https://github.com/eclipse/che/labels/area%2Fche-server
- N / A

### https://github.com/eclipse/che/labels/area%2Fplugin-registry
- N / A

### https://github.com/eclipse/che/labels/area%2Fdevfile-registry
- [x] #21979 **5 sp**
 
### https://github.com/eclipse/che/labels/area%2Fsamples 
- N / A

### https://github.com/eclipse/che/labels/area%2Fimage-puller
- N / A

### https://github.com/eclipse/che/labels/area%2Fwebsite
- N / A

### https://github.com/eclipse/che/labels/area%2Fhosted-che 
- [x] [[Developer Sandbox] Increase the number of routes per-user to 30](https://issues.redhat.com/browse/CRW-4124) **2 sp**

### Browser Extension
- [ ] https://github.com/eclipse/che/issues/11584 **5 sp**
- [x] https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/issues/27 **3 sp**
- [x] https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/issues/39 **1 sp**
- [ ] https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/issues/38 **2 sp**

### Try in Web IDE GitHub action
- N / A

### https://github.com/eclipse/che/labels/area%2Fqe + https://github.com/eclipse/che/labels/e2e-test%2Ffailure + [![image](https://user-images.githubusercontent.com/227597/214135832-6150cbf2-7b33-4cfe-96a7-6cc3c940a1c6.png)](https://issues.redhat.com/issues/?filter=12405916)
- [x] [CRW-3930: Pre-release testing of Dev Spaces 3.5.0.GA](https://issues.redhat.com/browse/CRW-3930) **2sp** (remaining part)
- [ ] https://github.com/eclipse/che/issues/22031 **5sp**
- [x] [CRW-4035: Run test case 'Update DS 3.4 to DS 3.5 on x86_64 OCP 4.12 airgap'](https://issues.redhat.com/browse/CRW-4035) **2sp**
- [x] [CRW-4034: Run test case 'Install DS on x86_64 OCP 4.12 and run workspace using stage images'](https://issues.redhat.com/browse/CRW-4034) **1sp**
- [x] [CRW-3949: Run test case 'Check links to documentation page in Dashboard' on x86_64 OCP 4.10, OCP 4.12, airgap OCP 4.12](https://issues.redhat.com/browse/CRW-3949) **1sp**
- [x] [CRW-4042: Run test case 'Image puller verification'](https://issues.redhat.com/browse/CRW-4042) **1sp**
- [x] [CRW-2835: Implement a groovy lint checker for crw_jenkins merge requests](https://issues.redhat.com/browse/CRW-2835) **3sp**
- [x] [CRW-4045: DS 3.5.0 DevSandbox pre-rollout (staging) verification](https://issues.redhat.com/browse/CRW-4045) **5sp**

### https://github.com/eclipse/che/labels/kind%2Frelease + https://github.com/eclipse/che/labels/area%2Fci + [![image](https://user-images.githubusercontent.com/227597/214135832-6150cbf2-7b33-4cfe-96a7-6cc3c940a1c6.png)](https://issues.redhat.com/browse/CRW-3868?filter=-1&jql=project%20in%20(CRW)%20and%20component%20in%20(%22productization%3A%20build%20%26%20internals%22%2C%20%22productization%3A%20security%20%26%20legal%22)%20and%20resolution%20%3D%20Unresolved)
- [ ] CRW-3196 migrate devfileregistry to cachito - Nick - WIP from previous sprint **13sp**
- [ ] https://issues.redhat.com/browse/CRW-4077 Ensure smooth transition from old default editor (theia or che-code/insiders) to new default che-code/latest -- will need help from Dashboard, Server, Operator, Devfile Reg experts here; not sure who should own this blocker for 3.6 **13sp**

Issues we can now address since theia can be safely removed in 3.6 (7.63-7.64):
- [x]  https://issues.redhat.com/browse/CRW-3489 Drop theia from list of available editors in dashboard **1sp** 
- [x]  https://issues.redhat.com/browse/CRW-3662 Enable theia IDE removal warning in dashboard **1sp** 
- [x]  remove lombok jar https://github.com/redhat-developer/devspaces-images/pull/392 **1sp**
- [x] https://issues.redhat.com/browse/CRW-3514 Remove CRW 2.15 jobs from Jenkins **3sp**
- [ ] Documentation **5 sp**

### https://github.com/eclipse/che/labels/area%2Fdoc
- [ ] https://github.com/eclipse/che/issues/22033 ⭐ **5 sp**
- [ ] Update CheCluster Custom Resource fields reference in the doc by adding missed sections #21970 **1 sp**

**Comment by nickboldt** [comment]
Prod / CI issues:
- [ ] CRW-3196 migrate devfileregistry to cachito - Nick - WIP from previous sprint
- [ ] https://issues.redhat.com/browse/CRW-4077 Ensure smooth transition from old default editor (theia or che-code/insiders) to new default che-code/latest -- will need help from Dashboard, Server, Operator, Devfile Reg experts here; not sure who should own this blocker for 3.6 

Issues we can now address since theia can be safely removed in 3.6 (7.63-7.64):
- [ ]  https://issues.redhat.com/browse/CRW-3489 Drop theia from list of available editors in dashboard
- [ ]  https://issues.redhat.com/browse/CRW-3662 Enable theia IDE removal warning in dashboard
- [ ]  remove lombok jar https://github.com/redhat-developer/devspaces-images/pull/392
- [ ] https://issues.redhat.com/browse/CRW-3514 Remove CRW 2.15 jobs from Jenkins

Ideas for Dev Tools Week:
- [ ] Enable CI builds for che-incubator/configbump, including updated secrets #21988 - Dmytro started this during last H&H
- [ ] investigate https://github.com/devfile/registry-operator to maybe replace the devfile registry (would need to be productized as a separate product or part of DS / DWO?)
- [ ] https://issues.redhat.com/browse/CRW-2835 implement groovy linter for Jenkins MR checks (so the check actually catches errors/typos!)

Issues for Team A backlog
- [ ]  CRW-3868 support building OSBS scratch builds from midstream PRs
- [ ] https://issues.redhat.com/browse/CRW-4075 convert installDevSpaces script into a wrapper for "install dsc and then run that" as we have in https://github.com/redhat-developer/devspaces-demo/pull/16/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R19

**Comment by nickboldt** [comment]
Courseware links:
* https://role.rhu.redhat.com
* https://www.linkedin.com/learning/onboarding/start/content-recommendations?careerIntentTrackingId=oUHDGZTHRJS8%2FPcWmMzyRQ%3D%3D&u=2056732
* https://source.redhat.com/groups/public/day-of-learning/learning_suggestions
* https://docs.google.com/document/d/1RvpXULVz67yhsDaBhp-t2-xf33ZzraPx7X4Kf5LdPx4/edit#heading=h.sjfsy7ljote4
