### ISSUE TITLE
Sprint 233 (Team B)

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22035]
This issue collects work items of the Eclipse Che https://github.com/eclipse/che/labels/team%2FB for Sprint 233 (Mar 9th - Mar 22th) (two weeks).

Continued from previous sprint https://github.com/eclipse/che/issues/22001

:notebook: Please note that this is a tentative plan until sprint planning has been conducted (February 8th)

### Red Hat DevTools Week Activities

@amisevsk:
  - Debugging tools for Dev Spaces installs (https://github.com/amisevsk/che-must-gather)
  - Learn about ACM as there are WTO questions there

@azatsarynnyy:
- [Solve the customer's problem when installing VS Code extension in their air-gapped DevSpaces](https://issues.redhat.com/browse/CRW-3942)
- [Get a successfull build of VS Code in the Cachito-based environment](https://issues.redhat.com/browse/CRW-3160)

@AObuchow: 
- Learning about DWO/WTO release and productization process

@RomanNikitenko:
- https://github.com/eclipse/che/issues/21859#issuecomment-1335064545
- https://github.com/eclipse/che/issues/21822

@vitaliy-guliy:
- Explore possible ways to speed up Che-Code development:
  - Build the che-code by hands
  - How to run unit tests
  - Build the che-code docker image without running tests

@SDawley

@mkuznyetsov:
- Eclipse Che Operator
- Devworkspace Operator

@musienko-maxim:
Pick up/study tasks according to decisions in the issue: https://issues.redhat.com/browse/CRW-4093 

@SkorikSergey
[Security Journey](https://redhat.securityjourney.com/) course

@nallikaea: Devfiles

@l0rd:
- recording 3 minute videos of devspaces-demo
- devworkspace operator blog post

### Sprint backlog

![## AREA/DEVFILE-SPEC](https://img.shields.io/github/issues/eclipse/che/area%2Fdevfile-spec?style=plastic) 

- devfile/api/issues/1032
- devfile/api/issues/1033

![## AREA/DEVWORKSPACE-OPERATOR](https://img.shields.io/github/issues/eclipse/che/area%2Fdevworkspace-operator?style=plastic)

- devfile/devworkspace-operator/issues/1036
- devfile/devworkspace-operator/issues/1045
- #22012
- Flickering DevWorkspace metrics in Grafana dashboard
- #22036
- devfile/devworkspace-operator/issues/1056

![## AREA/WEB-TERMINAL](https://img.shields.io/badge/area%2Fweb--terminal_issues-n%2fa-brightgreen?style=plastic)

- ⚪ **[Improve and simplify the Web Terminal Operator release process](https://issues.redhat.com/browse/WTO-150)**
- ⚪ **[Support for persistent storage per user](https://issues.redhat.com/projects/WTO/issues/WTO-156)**
- ⚪ **Set up automatic rebuilds of web-terminal-exec component for WTO 1.5**

![## AREA/EDITOR/VSCODE](https://img.shields.io/github/issues/eclipse/che/area%2Feditor%2Fvscode?style=plastic)

- ⚪ **[[CRW-3942] Installing VS Code extensions behind a proxy fails with HTTP error 403](https://issues.redhat.com/browse/CRW-3942)** 
- ⚪ **[[CRW-3160] migrate from pkgs.devel lookaside asset files to cachito w/ yarn](https://issues.redhat.com/browse/CRW-3160)**
- ⚪ **[VS Code's WebView functionality doesn't work when the browser is behind the proxy](https://issues.redhat.com/browse/CRW-3885)** 
- #21879
- #22008
- #21837
- #21853
- #21987
- #22003
- #22004

![## AREA/EDITOR/JETBRAIN](https://img.shields.io/github/issues/eclipse/che/area%2Feditor%2Fjetbrains%2Fintellij?style=plastic)

- #22034

![## AREA/UDI](https://img.shields.io/github/issues/eclipse/che/area%2Fudi?style=plastic)

- ⚪ **[[CRW-3367] Allow running podman from within a workspace](https://issues.redhat.com/browse/CRW-3367)**
- #20799
- ⚪ **[[CRW-3865] include sdkman in downstream UDI container?](https://issues.redhat.com/browse/CRW-3865)**
- ⚪ **[[CRW-3072] Include jbang binary in Universal Developer image](https://issues.redhat.com/browse/CRW-3072)**

![## AREA/QE](https://img.shields.io/github/issues/eclipse/che/area%2Fqe?style=plastic)

- ⚪ **[[CRW-3893] Automate test for checking the predefined DevSpace testflow](https://issues.redhat.com/browse/CRW-3893)**
- ⚪ **[[CRW-4093] Clarify some QE aspects for WTO/DWO projects](https://issues.redhat.com/browse/CRW-4093)**
- ⚪ **[[CRW-4044] Estimate time of java project build and run inside Che Code Editor in performance tests](https://issues.redhat.com/browse/CRW-4044)**
- ⚪ **[[CRW-4096] Automate `Github and Github Cloud factories with OAuth` test-cases](https://issues.redhat.com/browse/CRW-4096)**
- ⚪ **[[CRW-3936] Create Jenkins job for running Predefined namespace test](https://issues.redhat.com/browse/CRW-3936)**
- ⚪ **[Pre-release testing issues](https://issues.redhat.com/issues/?jql=project%20%3D%20CRW%20AND%20status%20%3D%20Open%20AND%20component%20%3D%20%22Team%20B%3A%20DevWorkspace%20%2B%20Operator%2C%20Web%20Terminal%20%2B%20Operator%2C%20editors%2FIDEs%20%2B%20built-in%20vscode%20extensions%2C%20Universal%20Developer%20Image%2C%20machine-exec%2C%20dev%20environment%20config%22%20AND%20%22Epic%20Link%22%20%3D%20CRW-3930%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC)**
- #21514
- #21789
- #21789

![## E2E-TEST/FAILURE](https://img.shields.io/github/issues/eclipse/che/e2e-test%2Ffailure?style=plastic)

- ⚪  

![## AREA/CI](https://img.shields.io/github/issues/eclipse/che/area%2Fci?style=plastic)

- [ ] [[CRW-3336] pluginregistry :: Use fetch-artifacts for plugin registry build assets](https://issues.redhat.com/browse/CRW-3336) - Sam, WIP
- [ ] [[CRW-3581] enable github to jira integration (openshift-ci)](https://issues.redhat.com/browse/CRW-3581) - Mykhailo, Partially completed
- [ ] [[CRW-4043] Improve process for building midstream and syncing to downstream](https://issues.redhat.com/browse/CRW-4043) 🆕  - Sam, WIP
- [x] #21931
- [x] #21586
- [x] #21988
- [x] #21993

![## KIND/RELEASE](https://img.shields.io/github/issues/eclipse/che/kind%2Frelease?style=plastic)

- ⚪

![## KIND/TASK](https://img.shields.io/github/issues/eclipse/che/kind%2Ftask?style=plastic)

- #21944

**Comment by nickboldt** [comment]
Issues for Team B prod team: 

- [ ] https://issues.redhat.com/browse/CRW-3336 pluginregistry :: Use fetch-artifacts for plugin registry build assets - Sam - WIP from previous sprint
- [ ] https://issues.redhat.com/browse/CRW-4043 Improve process for building midstream and syncing to downstream - Sam - WIP continued from prev sprint

- [ ] https://issues.redhat.com/browse/CRW-3581 enable github to jira integration (openshift-ci) - Mykhailo - WIP 1/3rd completed in prev sprint
- [ ] https://github.com/eclipse/che/issues/21931 39 restricted dependencies used in code-rhel8 container build - Mykhailo started in prev sprint

Backlog:
- [ ] https://github.com/eclipse/che/issues/21954 Set set provenance:false in workflows that use docker/setup-buildx-action 
- [ ] https://github.com/eclipse/che/issues/21586 Deduplicate samples between che-samples and devspaces-samples
- [ ]  https://issues.redhat.com/browse/CRW-4087 remove crwctl executable from dsc tarballs
- [ ] https://github.com/eclipse/che/issues/21969 Remove s390x/ppc64le; add arm64 arches in che container builds
- [ ] https://github.com/eclipse/che/issues/21993 The set-output command is deprecated and will be disabled by May 2023

**Comment by nickboldt** [comment]
Course / education links for DTW:
* https://role.rhu.redhat.com
* https://www.linkedin.com/learning/onboarding/start/content-recommendations?careerIntentTrackingId=oUHDGZTHRJS8%2FPcWmMzyRQ%3D%3D&u=2056732
* https://source.redhat.com/groups/public/day-of-learning/learning_suggestions
* https://docs.google.com/document/d/1RvpXULVz67yhsDaBhp-t2-xf33ZzraPx7X4Kf5LdPx4/edit#heading=h.sjfsy7ljote4

**Comment by dmytro-ndp** [comment]
@l0rd , @musienko-maxim : would you consider next issues for Maryna to work on during this sprint?
- Automate "Empty workspace" sample test: https://issues.redhat.com/browse/CRW-3566
- Clean up Che Theia specific tests and page objects from Eclipse Che typescript functional tests: https://github.com/eclipse/che/issues/22043
?

**Comment by l0rd** [comment]
@amisevsk please consider that there is [the new logs tab that is being working on by Team A](https://github.com/eclipse/che/issues/21827)

**Comment by nickboldt** [comment]
WIP for the current and next sprint: [CRW-4049](https://issues.redhat.com/browse/CRW-4049) Create jenkins build for vsix plugins, publishing to download.devel (subtask of [[CRW-3336] pluginregistry :: Use fetch-artifacts for plugin registry build assets](https://issues.redhat.com/browse/CRW-3336))
