### ISSUE TITLE
Sprint 234 (Team A)

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22066]
The issue collects work items of the Eclipse Che Team for Sprint 234 (March 22nd - April 4th) (two weeks).
:notebook: Please note that this is a tentative plan until sprint planning has been conducted (March 22nd)

Previous Sprint - https://github.com/eclipse/che/issues/22027

### Sprint goals
- [x] Che-Theia removal
- [ ] Publish the initial version of the "Try in Dev Spaces" Browser extension to Safari, Chrome, and Firefox marketplaces
- [ ] Enable Smoke Test PR check against che-operator, dashboard, and che-server
- [ ] Use Dev Spaces Release Candidates on the Developer Sandbox staging cluster

| Team Availability Ratio  |     1      |
|----------|:-------------:|
| Story Points Planned | 179 |
| Velocity | 48 |
  
### Aditional Notes
- Developer+OpenShift Hack 'n' Hustle - **April 7th**
   - https://skaffold.dev/
   - Enable CI builds for che-incubator/configbump, including updated secrets #21988 @dmytro-ndp 

### https://github.com/eclipse/che/labels/area%2Fgit%2Foauth-services
- [ ] Private gitlab instance: workspace does not exist https://issues.redhat.com/browse/CRW-4102 ⭐ **2 sp**
- [ ] Support reading devfiles from private repos other than GitHub/GitLab/Bitbucket #21951
   - [ ] https://github.com/eclipse/che/issues/22025 **5 sp**
- [ ] Improving git configuration with PAT documentation https://github.com/eclipse/che/issues/21989 **2 sp** 
- [ ] 404 page not found" error when open workspace from BitBucket server public repo factory URL [CRW-3864](https://issues.redhat.com/browse/CRW-3864)  **5 sp**
- [x] [Git 'commit' fails when PAT is configured (because user name and email are not set)](https://issues.redhat.com/browse/CRW-4057) **3 sp**
- [x] https://github.com/eclipse/che/issues/22053 **1 sp**

### https://github.com/eclipse/che/labels/area%2Fdashboard
- [ ] https://github.com/eclipse/che/issues/21827 **13 sp**
- [x] https://github.com/eclipse/che/issues/21990 **3 sp**
- [ ] https://github.com/eclipse/che/issues/22039 **2 sp** 
- [ ] https://github.com/eclipse/che/issues/22083  **5 sp** 
- [ ] https://github.com/eclipse/che/issues/22057 **3 sp** 
- [ ] https://github.com/eclipse/che/issues/22011 **5 sp** 
- [x] https://github.com/eclipse/che/issues/21957 **1 sp** 
- [x] https://github.com/eclipse/che/issues/21664 **1 sp** 

###  https://github.com/eclipse/che/labels/area%2Fche-operator
- [x] https://github.com/eclipse/che/issues/22063  **3 sp**
   - [x] https://github.com/eclipse/che/issues/22064 
   - [x] Ensure smooth transition from old default editor (theia or che-code/insiders) to new default che-code/latest
https://issues.redhat.com/browse/CRW-4077

### https://github.com/eclipse/che/labels/kind%2Ftechnical-debt
- [x] https://github.com/eclipse/che/issues/21771
    - [x] #22090  **5 sp**
    - [x] #22091  **2 sp**
    - [x] [JIRA: Remove che-theia references from the plugin registries](https://issues.redhat.com/browse/CRW-4135) **2 sp**
    - [x] [JIRA: Remove che-theia references from the devfile registries](https://issues.redhat.com/browse/CRW-4134) **2 sp**

### https://github.com/eclipse/che/labels/area%2Fche-server
-  [x] https://github.com/eclipse/che/issues/22062  **8 sp**

### https://github.com/eclipse/che/labels/area%2Fplugin-registry
- [ ] [.NET debugger doesn't work](https://issues.redhat.com/browse/CRW-3563)  **3 sp** 

### https://github.com/eclipse/che/labels/area%2Fdevfile-registry
- [x] #22075 **8 sp**
- [x] #21979 **2 sp**

### https://github.com/eclipse/che/labels/area%2Fsamples
- N / A

### https://github.com/eclipse/che/labels/area%2Fimage-puller
- N / A

### https://github.com/eclipse/che/labels/area%2Fwebsite
- N / A

### https://github.com/eclipse/che/labels/area%2Fhosted-che 
- [ ] https://github.com/eclipse/che/issues/22069 **3 sp**
- [ ] [Use Dev Spaces RC on the Developer Sandbox staging](https://issues.redhat.com/browse/CRW-4132) **8 sp**

### Browser Extension
- [ ] https://github.com/eclipse/che/issues/11584 **8 sp**

### Try in Web IDE GitHub action
- [ ] release a new version / fix [CI Checks](https://github.com/redhat-actions/try-in-web-ide/actions/workflows/ci.yml) **1 sp**

### https://github.com/eclipse/che/labels/area%2Fqe + https://github.com/eclipse/che/labels/e2e-test%2Ffailure + [![image](https://user-images.githubusercontent.com/227597/214135832-6150cbf2-7b33-4cfe-96a7-6cc3c940a1c6.png)](https://issues.redhat.com/issues/?filter=12405916)
- [ ] https://github.com/eclipse/che/issues/21753 **5 sp**
- [x] https://github.com/eclipse/che/issues/22031 **3 sp**
- [ ] https://github.com/eclipse/che/issues/22045 **8 sp**
- [ ] https://github.com/eclipse/che/issues/22046 **2 sp**
- [ ] https://github.com/eclipse/che/issues/22047 **8 sp**
- [x] [CRW-4133: Run eclipse/che tests in Dev Spaces test pipelines](https://issues.redhat.com/browse/CRW-4133) **5sp**
- [ ] [CRW-4129: Switch testing pipelines to DS 3.6.0](https://issues.redhat.com/browse/CRW-4129) **5sp**
- [ ] [CRW-4131: Air gap should be tested without devspaces URL in proxy whitelist](https://issues.redhat.com/browse/CRW-4131) - **2sp**

### https://github.com/eclipse/che/labels/kind%2Frelease + https://github.com/eclipse/che/labels/area%2Fci + [![image](https://user-images.githubusercontent.com/227597/214135832-6150cbf2-7b33-4cfe-96a7-6cc3c940a1c6.png)](https://issues.redhat.com/browse/CRW-3868?filter=-1&jql=project%20in%20(CRW)%20and%20component%20in%20(%22productization%3A%20build%20%26%20internals%22%2C%20%22productization%3A%20security%20%26%20legal%22)%20and%20resolution%20%3D%20Unresolved)

- [ ] https://issues.redhat.com/browse/CRW-3196 migrate devfileregistry to cachito - Nick - WIP from previous sprint **13sp**
- [ ] https://issues.redhat.com/browse/CRW-3663 Removal of Che-Theia IDE as supported editor (updates to che-plugin-registry, then che-operator, then downstreaming) **2sp**
- [ ] https://issues.redhat.com/browse/CRW-4128 When pushing sources and dsc tarballs, use a unique CR folder each time **1sp**
- [ ] https://issues.redhat.com/browse/CRW-3868 support building OSBS scratch builds from midstream PRs **8sp** 

### https://github.com/eclipse/che/labels/area%2Fdoc
- [ ] https://github.com/eclipse/che/issues/22033 ⭐ **8 sp**
- [x] https://github.com/eclipse/che/issues/21970 **1 sp**
- [x] https://github.com/eclipse/che/issues/22088 **2 sp**

**Comment by nickboldt** [comment]
- [ ] https://issues.redhat.com/browse/CRW-3196 migrate devfileregistry to cachito - Nick - WIP from previous sprint **13sp**
- [ ] https://issues.redhat.com/browse/CRW-4077 Ensure smooth transition from old default editor (theia or che-code/insiders) to new default che-code/latest -- will need help from Dashboard, Server, Operator, Devfile Reg experts here; not sure who should own this blocker for 3.6 **13sp**
- [ ] https://issues.redhat.com/browse/CRW-4128 When pushing sources and dsc tarballs, use a unique CR folder each time
- [ ] https://issues.redhat.com/browse/CRW-3868 support building OSBS scratch builds from midstream PRs 8sp
- [ ] Enable CI builds for che-incubator/configbump, including updated secrets #21988 - Dmytro started this during last H&H **5sp**

**Comment by l0rd** [comment]
@ibuziuk something for this sprint if you have bandwidth https://github.com/eclipse/che/issues/22083

**Comment by ibuziuk** [comment]
regarding ^ not sure exactly how it is supposed to be fixed on the operator level, thought this is more DWO

**Comment by dmytro-ndp** [comment]
@ibuziuk : one more QE issue from @l0rd to consider: [CRW-4131:Air gap should be tested without devspaces URL in proxy whitelist](https://issues.redhat.com/browse/CRW-4131) - **2sp**

**Comment by nickboldt** [comment]
removal of Theia from plugin and devfile reg for up and downstream:
- [ ] https://github.com/eclipse/che/issues/22091
- [ ] https://github.com/eclipse/che/issues/22090
- [ ] [CRW-4134](https://issues.redhat.com/browse/CRW-4134) Remove che-theia references from the devfile registry
- [ ] [CRW-4135](https://issues.redhat.com/browse/CRW-4135) Remove che-theia references from the plugin registry
