### ISSUE TITLE
[Red Hat Dev Tools Week] Defining and using Eclipse Che Workspaces for Eclipse Che development

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22243]
- CONTRIBUTING.md in every repo
- devfile v2 in upstream and downstream repositories
- badge in upstream and downstream repositories with the link to the dogfooding instance and workspaces.openshift.com
- report issues for every problem you encounter during dogfooding

Che Team A:
- [x] https://github.com/eclipse/che e2e test @dmytro-ndp @ScrewTSW @nallikaea
- [ ] https://github.com/che-incubator/chectl @tolusha  
- [ ] https://github.com/eclipse-che/che-operator @tolusha 
- [ ] https://github.com/eclipse-che/che-server @vinokurig @artaleks9 
- [x] https://github.com/eclipse-che/che-dashboard @olexii4 @akurinnoy 
- [ ] https://github.com/eclipse-che/che-plugin-registry @svor 
   - [ ] https://github.com/redhat-developer/devspaces/tree/devspaces-3-rhel-8/dependencies/che-plugin-registry
- [ ] https://github.com/redhat-actions/try-in-web-ide @dkwon17 

Issues for dogfooding:
-  [ ] Eclipse Che / Dev Spaces Testing Overview @dmytro-ndp  
-  [ ] https://github.com/eclipse/che/issues/22480 @olexii4 
-  [ ] https://github.com/eclipse/che/issues/22483 @akurinnoy 
 - [ ] @olexii4 https://github.com/eclipse/che/issues/22237
    - [x] https://github.com/eclipse/che/issues/22481
 - [x] @ScrewTSW  https://github.com/eclipse/che/issues/22191
 - [x] https://github.com/eclipse/che/issues/22270
 - [x] @vinokurig https://github.com/eclipse/che/issues/21706
 - [x] @dkwon17 https://github.com/redhat-actions/try-in-web-ide/issues/28
 - [x] @dkwon17 https://github.com/redhat-actions/try-in-web-ide/issues/31

Other activities:
- [x] https://github.com/eclipse/che/issues/22215 @svor 
- [x] https://github.com/eclipse/che/issues/22490 @ScrewTSW 
- [ ] @ibuziuk EclipseCon 2023 preparations
     - [ ] https://www.eclipsecon.org/2023/sessions/pros-and-cons-using-kubernetes-development-platform
     - [ ] https://www.eclipsecon.org/2023/sessions/deploy-and-update-microservices-fly-eclipse-cloud-devtools
- [ ] https://github.com/eclipse/che/issues/22120 @nickboldt 
- [ ] @dkwon17 https://github.com/eclipse/che/issues/22492
- [ ] @dkwon17 https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/issues/3
- [x] @RomanNikitenko Kubernetes Training
- [ ] @vitaliy-guliy Build and develop Che-Code in Che
- [ ] @azatsarynnyy work on a blog post: "Using tcpdump + Wireshark for analyzing the network traffic in Che/DS"
- [ ] @AObuchow Replicate local development setup on Che, attempt to configure a new editor, test React development in Che
- [ ] @tolusha e2e tests to start a workspace using different git urls
    - [ ] one of the option would be investigation contract testing ([pact.io](https://pact.io/), [HAC-dev contract test introduction and demo](https://youtu.be/wavhtYnw8Bg?si=hMcob2ORYExwU0bi))

Che Team B:
- [ ] https://github.com/che-incubator/che-code @vitaliy-guliy 
- [ ] https://github.com/che-incubator/jetbrains-editor-images
- [ ] https://github.com/eclipse-che/che-machine-exec @l0rd 
- [ ] https://github.com/devfile/devworkspace-operator
- [ ] https://github.com/devfile/developer-images @l0rd 
- [ ] https://github.com/devfile/devworkspace-operator-docs
- [ ] https://github.com/che-incubator/che-api
- [ ] https://github.com/che-incubator/workspace-data-sync
- [ ] https://github.com/eclipse-che/blog
- [ ] https://github.com/eclipse-che/che-website
- [ ] [redhat-developer/devspaces-images/devspaces-pluginregistry](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/devspaces-pluginregistry) @SDawley 
- [ ] https://github.com/l0rd/devspaces-telemetry @l0rd 
- [ ] https://github.com/openshift/console.git
