### ISSUE TITLE
Document how to install Eclipse Che on major k8s providers

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#22392]
### Is your task related to a problem? Please describe

We don't have any docs describing how to install Eclipse Che on k8s cluster [1], but instead we have a lot of requests like this [2]. 

[1] https://eclipse.dev/che/docs/stable/administration-guide/installing-che/
[2] Eclipse che on Plain Kubernetes - Is it possible if so, detailed steps required. Minikube is NOT idel https://github.com/eclipse/che/issues/21743
[3] Document how to setup an OIDC provider https://github.com/eclipse/che/issues/21304

### Describe the solution you'd like

In general, we have to know a couple of things before deploying Eclipse Che on k8s cluster:
* kubernetes public domain
* OIDC provider url 
* client id
* client secret

1. Prepare patch file
```bash
cat >>cr-patch.yaml <<EOF
apiVersion: org.eclipse.che/v2
spec:
  networking:
    domain: <DOMAIN>
    auth:
      identityProviderURL: <IDENTITY_PROVIDER_URL>
      oAuthClientName: <CLIENT_ID>
      oAuthSecret: <CLIENT_SECRET>
EOF
```

2. Run command to deploy Eclipse Che
```
chectl server:deploy --platform k8s --che-operator-cr-patch-yaml cr-patch.yaml --skip-oidc-provider-check
```

The main problem is in configuring OIDC provider and users would like to have a clear doc how to do this. I found a couple of successful user's stories while going through similar issues [1] [2] [3] [4] [5]. The main idea is to translate those stories in the article for [che-docs](https://eclipse.dev/che/docs/stable/overview/introduction-to-eclipse-che/)

- [x] https://eclipse.dev/che/docs/stable/administration-guide/installing-che-on-microsoft-azure/ (AKS)
- [ ] https://github.com/eclipse/che/issues/21049#issuecomment-1022108499 (Rancher)
- [ ] https://github.com/eclipse/che/issues/21049#issuecomment-1067776895 (GKE)
- [ ] https://github.com/flavienbwk/eclipse-che-kubernetes (Kubeadm)
- [x] https://eclipse.dev/che/docs/next/administration-guide/installing-che-on-amazon-elastic-kubernetes-service/ (EKS)
- [ ] https://github.com/eclipse/che/issues/21378#issuecomment-1685410001 https://github.com/eclipse/che/issues/22445 (microk8s)

### Additional context

 - [x] EKS - https://github.com/eclipse-che/che/issues/23209 / https://github.com/eclipse-che/che/issues/22615
