### ISSUE TITLE
Dev Tools Week Q4 2023

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22670]
This issue collects the list of potential activities for the Dev Tools Week (Dec 11th  - Dec 15th):
- [x] [Contribute 'Ansible & Dev Spaces" Developer Sandbox activity](https://issues.redhat.com/browse/SANDBOX-460) @svor 
- [x] Blog Post - Advanced Authorization https://issues.redhat.com/browse/CRW-4805
- [x] [Document how to install Eclipse Che on major k8s providers](https://github.com/eclipse/che/issues/22392)
   - [x] AKS is a priority https://github.com/eclipse/che/issues/22665 @tolusha 
- [ ] [Git commit + push on workspace shutdown to backup unsaved workspace project changes](https://github.com/eclipse/che/issues/22308) @AObuchow 
- [ ] [Automatic deployment of the Eclipse Che instance from the PR check PoC](https://github.com/eclipse/che/issues/22689) @dmytro-ndp 
- [ ] [UD] Improve dogfooding development to run command yarn license:generate https://github.com/eclipse/che/issues/22480 @olexii4 
- [x] Update devfiles for [kubernetes-image-puller-operator](https://github.com/che-incubator/kubernetes-image-puller-operator) and [kubernetes-image-puller](https://github.com/che-incubator/kubernetes-image-puller-operator) @dkwon17 
- [ ] Investigate how to access local CRC from Eclipse Che from the dogfooding cluster @dkwon17 
- [x] Investigate the possibility of using `testing-library` to improve the stability of the happy-path test @akurinnoy @artaleks9 
- [ ] Che-server repository code base cleanup https://github.com/eclipse/che/issues/22710 @vinokurig 
- [ ] Contract Testing / pact.io use as PR checks
- [ ] Update [Getting Started](https://eclipse.dev/che/getting-started/) Eclipse Che website samples with devfiles from https://registry.devfile.io/viewer
- [ ] Use devfile `2.2.2` version in all the dogfooding / devfiles / samples etc.
