### ISSUE TITLE
Dashboard Makeover

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22784]
### Is your enhancement related to a problem? Please describe

Here are some recurring feedback on the getting started page in the dashboard:

- URL parameters are not "exposed" to users
- Users are guided to pick an example from the devfile registry but they should start using their own git repository right away instead and then customize the dev environment
- There is no customization guidance: users are missing the old devfile editor (although it wasn't loved, it provided a way to customize dev environments)
- It's not possible to select the editor when starting a workspace from a git URL

### Describe the solution you'd like
- [x] #22766
- [x] Expose URL parameters on user dashboard 
        https://github.com/eclipse-che/che/issues/22816
        https://github.com/eclipse-che/che/issues/22975
        https://github.com/eclipse-che/che/issues/23016
- [ ] Move the sample on a different page (not the getting started)
- [x] Add links to CDE and Editor customization guides

### Mockups

**With option collapsed (the default)**

![image](https://github.com/eclipse/che/assets/606959/ec163fe1-c2b4-426f-88b0-aa77c5eb6d7e)

**With option expanded (the user needs to click on the labels to expand)**

![image](https://github.com/eclipse/che/assets/606959/5656909f-b2e4-4666-addd-65f789141d3f)

**Samples from the devfile registry are moved to a dedicated page**

![image](https://github.com/eclipse/che/assets/606959/cd7a5ca6-1dc7-4992-bd9b-fe2e55e3c5a8)

**Comment by ibuziuk** [comment]
Closing as done, going to create a separate issue for the getting-started samples if needed
