### ISSUE TITLE
Dev Tools Week Q2 2024

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22999]
This issue collects the list of potential activities for the Dev Tools Week (June 17th - June 21st):

- [ ] Ollama Developer Sandbox activity -  https://issues.redhat.com/browse/SANDBOX-621 @ibuziuk 
- [ ] Usage of Cost Management OpenShift Operator for Eclipse Che - https://www.redhat.com/en/blog/whats-new-cost-management-metrics-operator-image-20 @ibuziuk
- [ ] [Web Terminal onboarding ](https://gitlab.cee.redhat.com/codeready-workspaces/devtools-productization/-/blob/main/web-terminal-operator/WTO-onboarding.adoc) 
- [ ] Kubernetes custom resource YAML editor that provides field documentation & validation @AObuchow 
- [ ] Enable https://github.com/renovatebot/renovate for Eclipse Che repos:
   - che-server
   - che-dashboard
   -  che-operator
- [ ] https://github.com/eclipse-che/che/issues/22782 @olexii4 
- [ ] [Learn how to Install test GitHub Enterprise Server instance on AWS](https://issues.redhat.com/browse/CRW-3509)  @SkorikSergey 

Blogs:
- [x] Write a blog post about Devfile AI Assistant in examples @tolusha 
- [ ] Write a blog post on the topic of "Adding support for a new editor to Eclipse Che (on the example of JetBrains IU via Gateway)" @azatsarynnyy 
- [ ] Publish a blog post about contributing to che-docs from Che https://github.com/eclipse-che/blog/pull/34 @deerskindoll 

Trainings:
- [ ] [Artificial Intelligence Foundations: Thinking Machines](https://www.linkedin.com/learning-login/share?account=2056732&forceAccount=false&redirect=https%3A%2F%2Fwww.linkedin.com%2Flearning%2Fartificial-intelligence-foundations-thinking-machines%3Ftrk%3Dshare_ent_url%26shareId%3DHyOQmkmZSXO2PdkcT0mwVA%253D%253D) @RomanNikitenko
