### ISSUE TITLE
Dev Tools Week Q4 2024

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#23266]
This issue collects the list of potential activities for the Dev Tools Week (December 16th - 20th):

- [x] LLModels as a Service - https://github.com/rh-aiservices-bu/models-aas @ibuziuk 
- [ ] [Advent of Code](https://adventofcode.com/) with Eclipse Che
        - 2020 - https://github.com/che-incubator/advent-of-code-2020  
- [ ] JHipster devfile - https://registry.devfile.io/viewer/devfiles/community/jhipster-online
    - [ ] https://www.youtube.com/watch?v=b7xbcTAGNIQ 
    - [ ] Add on the che-website @ibuziuk 
    - [ ] https://github.com/eclipse-che/che-website/pull/112
- [ ]  https://www.youtube.com/live/065Aog4SmLk?si=wJ9AWJ2f898zT8VJ 
- [ ]  Add more installation methods to the website AKS / EKS etc.  https://eclipse.dev/che/#StartNow @tolusha ? 
- [ ] Trainings @ibuziuk 
     - [ ] Dogfooding - use Eclipse Che for all the trainings that require coding exercises
- [ ] Stress Testing
- [ ] devcontainers.json integration @vitaliy-guliy 
- [ ] IDX Project - https://idx.dev/
- [ ] Marketing 
- [ ] Use Olama LLVM and OpenAI API, create a dedicated AI component which will be able to replace[ devfile assistant GPT chat ](http://chatgpt.com/g/g-Bm20CP2Rp-devfile-assistant) @tolusha 
- [x] Use Hive to create permanent disconnected airgap OCP 4.17 cluster on AWS @dmytro-ndp (_Conclusion: it turned out that Hive didn't support provisioning of airgap OCP clusters_)
- [x] Blogs:
     - [x] 2024 - https://gist.github.com/ibuziuk/8ca0a0d80f9efb7b063e168f8c80cf3f
     - [ ] 2025 - https://gist.github.com/ibuziuk/4e9f46dc7fff35e374f65e136d18b1ca 
- [ ] Devfile-less editors definition
- [x] [Use current project directory at Che terminal creation](https://github.com/eclipse-che/che/issues/23022) @RomanNikitenko 
- [ ] [Node: Authentication training](https://www.linkedin.com/learning-login/share?account=2056732&forceAccount=false&redirect=https%3A%2F%2Fwww.linkedin.com%2Flearning%2Fnode-authentication%3Ftrk%3Dshare_ent_url%26shareId%3DuUY7F0iVQ6W49L%252FX9AWa0g%253D%253D) @RomanNikitenko 
- [ ] Che/DS plugin for Jet Brains Toolbox @azatsarynnyy 
- [x] [How to deploy full-stack JavaScript applications in OpenShift](https://developers.redhat.com/learn/openshift/how-deploy-full-stack-javascript-applications-openshift) @svor
- [x] [Learn Kubernetes using the Developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/learn/openshift/learn-kubernetes-using-developer-sandbox-red-hat-openshift) @svor
